import { PlanKey, SpendingStyle } from '@rumtelo/contracts';

import { book } from './book-row';

/**
 * The rest of the Learn book shelf. Pointers only — author, cover, store edition.
 * Values only. Field names live in book().
 */
export const BOOK_PRESET_EXTRA = [
    book(
        'atomic-habits',
        'Atomic Habits',
        'James Clear',
        'Small changes, kept. The line that behaviour beats strategy is this book.',
        'MIND',
        PlanKey.BASIC,
        'MONEY',
        12539702,
        '9781698414683',
        'https://en.wikipedia.org/wiki/James_Clear'
    ),
    book(
        'power-of-habit',
        'The Power of Habit',
        'Charles Duhigg',
        'A habit is a loop. See the cue and the jar stops leaking by accident.',
        'MIND',
        PlanKey.BASIC,
        'MONEY',
        9078085,
        '9780812981605',
        'https://en.wikipedia.org/wiki/Charles_Duhigg'
    ),
    book(
        'mindset',
        'Mindset',
        'Carol S. Dweck',
        'A fixed story about talent is expensive. Skill is something you practise.',
        'MIND',
        PlanKey.BASIC,
        'MONEY',
        746414,
        '9781472139955',
        'https://en.wikipedia.org/wiki/Carol_S._Dweck'
    ),
    book(
        'deep-work',
        'Deep Work',
        'Cal Newport',
        'The hours that raise earning power are the ones with the door shut.',
        'MIND',
        PlanKey.PLUS,
        'MONEY',
        7988607,
        '9781455586691',
        'https://en.wikipedia.org/wiki/Cal_Newport'
    ),
    book(
        'grit',
        'Grit',
        'Angela Duckworth',
        'Persistence outruns a burst of motive. Finish the book you already started.',
        'MIND',
        PlanKey.BASIC,
        'MONEY',
        7438753,
        '9781501111105',
        'https://en.wikipedia.org/wiki/Angela_Duckworth'
    ),
    book(
        'thinking-fast-and-slow',
        'Thinking, Fast and Slow',
        'Daniel Kahneman',
        'The quick decision spends. The slow one is the one the jars need.',
        'MIND',
        PlanKey.PLUS,
        'MONEY',
        13290711,
        '9780385676519',
        'https://en.wikipedia.org/wiki/Daniel_Kahneman'
    ),
    book(
        'subtle-art',
        'The Subtle Art of Not Giving a F*ck',
        'Mark Manson',
        'You only get a few things to care about. Choose them before the month does.',
        'MIND',
        PlanKey.BASIC,
        'MONEY',
        8231990,
        '9780063228252',
        'https://en.wikipedia.org/wiki/Mark_Manson'
    ),
    book(
        'magic-of-thinking-big',
        'The Magic of Thinking Big',
        'David J. Schwartz',
        'Aim smaller than you can stand and the work stays small. This is the older version of that warning.',
        'MIND',
        PlanKey.BASIC,
        'MONEY',
        480539,
        '9780722509432',
        'https://en.wikipedia.org/wiki/David_J._Schwartz'
    ),
    book(
        'as-a-man-thinketh',
        'As a Man Thinketh',
        'James Allen',
        'A short book on the thought you rehearse. The aim, before the plan.',
        'MIND',
        PlanKey.BASIC,
        'MONEY',
        6268048,
        '9781453778258',
        'https://www.gutenberg.org/ebooks/4507'
    ),
    book(
        'mans-search-for-meaning',
        "Man's Search for Meaning",
        'Viktor E. Frankl',
        'The one thing nobody can take is the reason you keep going. Read it when the month is empty.',
        'MIND',
        PlanKey.BASIC,
        'MONEY',
        11203708,
        '9780807067994',
        'https://en.wikipedia.org/wiki/Viktor_E._Frankl'
    ),
    book(
        'seven-habits',
        'The 7 Habits of Highly Effective People',
        'Stephen R. Covey',
        'Put first things first. A week has room for the jar, or it has room for noise.',
        'MIND',
        PlanKey.BASIC,
        'MONEY',
        10079937,
        '9781797115092',
        'https://en.wikipedia.org/wiki/Stephen_R._Covey'
    ),
    book(
        'essentialism',
        'Essentialism',
        'Greg McKeown',
        'If it is not the thing, it is in the way. The Education jar is not a junk drawer.',
        'MIND',
        PlanKey.PLUS,
        'MONEY',
        7285986,
        '9780753555163',
        'https://en.wikipedia.org/wiki/Greg_McKeown'
    ),
    book(
        'the-one-thing',
        'The One Thing',
        'Gary Keller',
        'One priority. The rest of the list is how people stay busy and broke.',
        'MIND',
        PlanKey.PLUS,
        'MONEY',
        10351762,
        '9781848549241',
        'https://en.wikipedia.org/wiki/Gary_Keller'
    ),
    book(
        'make-your-bed',
        'Make Your Bed',
        'William H. McRaven',
        'Start with the small task you can finish. Momentum is a practice, not a mood.',
        'MIND',
        PlanKey.BASIC,
        'MONEY',
        7984714,
        '9781455570232',
        'https://en.wikipedia.org/wiki/William_H._McRaven'
    ),
    book(
        'cant-hurt-me',
        "Can't Hurt Me",
        'David Goggins',
        'The limit you feel is often the story. Useful when the work is boring and still necessary.',
        'MIND',
        PlanKey.PLUS,
        'MONEY',
        8305903,
        '9781544529127',
        'https://en.wikipedia.org/wiki/David_Goggins'
    ),
    book(
        'obstacle-is-the-way',
        'The Obstacle Is the Way',
        'Ryan Holiday',
        'The hard month is the material. Do not wait for an easier one.',
        'MIND',
        PlanKey.BASIC,
        'MONEY',
        14428233,
        '9781781252895',
        'https://en.wikipedia.org/wiki/Ryan_Holiday'
    ),
    book(
        'ego-is-the-enemy',
        'Ego Is the Enemy',
        'Ryan Holiday',
        'The story that you already know is how a person stops learning.',
        'MIND',
        PlanKey.PLUS,
        'MONEY',
        12447129,
        '9781781257029',
        'https://en.wikipedia.org/wiki/Ryan_Holiday'
    ),
    book(
        'stillness-is-the-key',
        'Stillness Is the Key',
        'Ryan Holiday',
        'A loud head spends. Quiet is where the next decision gets made.',
        'MIND',
        PlanKey.PLUS,
        'MONEY',
        9130310,
        '9780525538585',
        'https://en.wikipedia.org/wiki/Ryan_Holiday'
    ),
    book(
        'four-agreements',
        'The Four Agreements',
        'Don Miguel Ruiz',
        'Be impeccable with your word. A promise to yourself is still a promise.',
        'MIND',
        PlanKey.BASIC,
        'MONEY',
        924521,
        '9781417664917',
        'https://en.wikipedia.org/wiki/Don_Miguel_Ruiz'
    ),
    book(
        'daring-greatly',
        'Daring Greatly',
        'Brené Brown',
        'Shame keeps people small and quiet about money. Name it, then do the work anyway.',
        'MIND',
        PlanKey.PLUS,
        'MONEY',
        7367250,
        '9781592408412',
        'https://en.wikipedia.org/wiki/Bren%C3%A9_Brown'
    ),
    book(
        'start-with-why',
        'Start with Why',
        'Simon Sinek',
        'People follow a reason, not a feature. Say why the work exists before you sell it.',
        'MIND',
        PlanKey.BASIC,
        'MONEY',
        6395237,
        '9781514246764',
        'https://en.wikipedia.org/wiki/Simon_Sinek'
    ),
    book(
        'drive-pink',
        'Drive',
        'Daniel H. Pink',
        'Autonomy, mastery, purpose. Pay matters, and it is not the only fuel.',
        'EARN',
        PlanKey.PLUS,
        'MONEY',
        6404786,
        '9780143145080',
        'https://en.wikipedia.org/wiki/Daniel_H._Pink'
    ),
    book(
        'tiny-habits',
        'Tiny Habits',
        'BJ Fogg',
        'A habit that is too big dies on day three. Make the first step smaller than your excuse.',
        'MIND',
        PlanKey.PLUS,
        'MONEY',
        9261174,
        '9781713508212',
        'https://en.wikipedia.org/wiki/BJ_Fogg'
    ),
    book(
        'indistractable',
        'Indistractable',
        'Nir Eyal',
        'Attention is the raw material. If the feed has it, the skill does not.',
        'MIND',
        PlanKey.PLUS,
        'MONEY',
        9129784,
        '9781526610201',
        'https://en.wikipedia.org/wiki/Nir_Eyal'
    ),
    book(
        'flow',
        'Flow',
        'Mihaly Csikszentmihalyi',
        'The state where the work is the point. Earning power lives in those hours.',
        'MIND',
        PlanKey.MAX,
        'MONEY',
        11041932,
        '9780060162535',
        'https://en.wikipedia.org/wiki/Mihaly_Csikszentmihalyi'
    ),
    book(
        'leaders-eat-last',
        'Leaders Eat Last',
        'Simon Sinek',
        'A team that feels safe does the hard work. Fear makes people hide the number.',
        'EARN',
        PlanKey.PLUS,
        'MONEY',
        8246311,
        '9781480542570',
        'https://en.wikipedia.org/wiki/Simon_Sinek'
    ),
    book(
        'everything-is-figureoutable',
        'Everything Is Figureoutable',
        'Marie Forleo',
        'The skill you do not have yet is a search, not a verdict.',
        'MIND',
        PlanKey.PLUS,
        'MONEY',
        null,
        '9780241341032',
        'https://en.wikipedia.org/wiki/Marie_Forleo'
    ),
    book(
        'the-dip',
        'The Dip',
        'Seth Godin',
        'Quit the dead ends. Stay in the hard middle of the thing you actually chose.',
        'MIND',
        PlanKey.PLUS,
        'MONEY',
        1977228,
        '9781101216347',
        'https://en.wikipedia.org/wiki/Seth_Godin'
    ),
    book(
        'linchpin',
        'Linchpin',
        'Seth Godin',
        'Be the person the work cannot replace with a cheaper version.',
        'EARN',
        PlanKey.PLUS,
        'MONEY',
        8754365,
        '9780307705501',
        'https://en.wikipedia.org/wiki/Seth_Godin'
    ),
    book(
        'outliers',
        'Outliers',
        'Malcolm Gladwell',
        'Talent is practice plus the room you were given. Use both without the myth.',
        'MIND',
        PlanKey.PLUS,
        'MONEY',
        10021591,
        '9780316024976',
        'https://en.wikipedia.org/wiki/Malcolm_Gladwell'
    ),
    book(
        'range',
        'Range',
        'David Epstein',
        'A wide base beats an early cage. Sampling is how you find the skill worth the jar.',
        'MIND',
        PlanKey.PLUS,
        'MONEY',
        8782615,
        '9780735214484',
        'https://en.wikipedia.org/wiki/David_Epstein'
    ),
    book(
        'who-moved-my-cheese',
        'Who Moved My Cheese?',
        'Spencer Johnson',
        'A short parable for when the old way of earning stops working.',
        'MIND',
        PlanKey.BASIC,
        'MONEY',
        258839,
        '9780091816971',
        'https://en.wikipedia.org/wiki/Spencer_Johnson'
    ),
    book(
        'the-alchemist',
        'The Alchemist',
        'Paulo Coelho',
        'A story about going toward the thing you named. Not a plan. A reminder to start.',
        'MIND',
        PlanKey.BASIC,
        'MONEY',
        11556106,
        '9780007423200',
        'https://en.wikipedia.org/wiki/Paulo_Coelho'
    ),
    book(
        'greatest-salesman',
        'The Greatest Salesman in the World',
        'Og Mandino',
        'Scrolls on persistence and the way you treat the next person. Read one and live it.',
        'MIND',
        PlanKey.BASIC,
        'MONEY',
        8458650,
        '9780802725578',
        'https://en.wikipedia.org/wiki/Og_Mandino'
    ),
    book(
        'awaken-the-giant',
        'Awaken the Giant Within',
        'Tony Robbins',
        'Decisions, not conditions. Long, and useful if you take one rule and keep it.',
        'MIND',
        PlanKey.PLUS,
        'MONEY',
        4002352,
        '9780671711887',
        'https://en.wikipedia.org/wiki/Tony_Robbins'
    ),
    book(
        'compound-effect',
        'The Compound Effect',
        'Darren Hardy',
        'Small deposits, kept for years. The same math as the Freedom jar.',
        'SAVE',
        PlanKey.BASIC,
        'MONEY',
        7115046,
        '9780306924644',
        'https://en.wikipedia.org/wiki/Darren_Hardy',
        [SpendingStyle.SAVER, SpendingStyle.BALANCED]
    ),
    book(
        'eat-that-frog',
        'Eat That Frog!',
        'Brian Tracy',
        'Do the hard task first. The rest of the day stops negotiating with you.',
        'MIND',
        PlanKey.BASIC,
        'MONEY',
        847534,
        '9781605091068',
        'https://en.wikipedia.org/wiki/Brian_Tracy'
    ),
    book(
        'you-are-a-badass',
        'You Are a Badass',
        'Jen Sincero',
        'A blunt talk with the excuse. Use it to start, not as the whole plan.',
        'MIND',
        PlanKey.BASIC,
        'MONEY',
        7436635,
        '9781452615516',
        'https://en.wikipedia.org/wiki/Jen_Sincero'
    ),
    book(
        'war-of-art',
        'The War of Art',
        'Steven Pressfield',
        'Resistance shows up the day the work gets real. Name it and sit down anyway.',
        'EARN',
        PlanKey.PLUS,
        'MONEY',
        288439,
        '9781590710036',
        'https://en.wikipedia.org/wiki/Steven_Pressfield'
    ),
    book(
        'same-as-ever',
        'Same as Ever',
        'Morgan Housel',
        'What does not change is the useful part. People, risk, and time.',
        'MIND',
        PlanKey.PLUS,
        'MONEY',
        14157635,
        '9781804090633',
        'https://en.wikipedia.org/wiki/Morgan_Housel'
    ),
    book(
        'big-magic',
        'Big Magic',
        'Elizabeth Gilbert',
        'Make the thing without waiting to be chosen. A creative life is a practice.',
        'MIND',
        PlanKey.PLUS,
        'MONEY',
        7434843,
        '9781408866764',
        'https://en.wikipedia.org/wiki/Elizabeth_Gilbert'
    ),
    book(
        'meditations',
        'Meditations',
        'Marcus Aurelius',
        'A private notebook on doing the next right thing. Short pages. Read one in the morning.',
        'MIND',
        PlanKey.BASIC,
        'MONEY',
        211529,
        '9781497684300',
        'https://www.gutenberg.org/ebooks/2680'
    ),
    book(
        'little-book-common-sense',
        'The Little Book of Common Sense Investing',
        'John C. Bogle',
        'Own the market. Keep the fee tiny. Leave it alone for decades.',
        'SAVE',
        PlanKey.BASIC,
        'MONEY',
        1239500,
        '9781427201454',
        'https://en.wikipedia.org/wiki/John_C._Bogle',
        [SpendingStyle.SAVER]
    ),
    book(
        'random-walk',
        'A Random Walk Down Wall Street',
        'Burton G. Malkiel',
        'Most people cannot beat the market. The book is the case for not trying to.',
        'SAVE',
        PlanKey.PLUS,
        'MONEY',
        246978,
        '9780393047813',
        'https://en.wikipedia.org/wiki/Burton_G._Malkiel',
        [SpendingStyle.SAVER, SpendingStyle.BALANCED]
    ),
    book(
        'intelligent-investor',
        'The Intelligent Investor',
        'Benjamin Graham',
        'Price is what you pay. Value is what you get. The investing book the others stand on.',
        'SAVE',
        PlanKey.PLUS,
        'MONEY',
        36434,
        '9780060793838',
        'https://en.wikipedia.org/wiki/Benjamin_Graham',
        [SpendingStyle.SAVER]
    ),
    book(
        'bogleheads-guide',
        "The Bogleheads' Guide to Investing",
        'Taylor Larimore',
        'A plain plan: low cost, broad funds, and no heroics.',
        'SAVE',
        PlanKey.PLUS,
        'MONEY',
        306608,
        '9780471730330',
        'https://en.wikipedia.org/wiki/Taylor_Larimore',
        [SpendingStyle.SAVER]
    ),
    book(
        'millionaire-next-door',
        'The Millionaire Next Door',
        'Thomas J. Stanley',
        'The wealthy neighbour does not look wealthy. Income is not the same as keeping it.',
        'SAVE',
        PlanKey.BASIC,
        'MONEY',
        797467,
        '9780743517829',
        'https://en.wikipedia.org/wiki/Thomas_J._Stanley',
        [SpendingStyle.SAVER]
    ),
    book(
        'automatic-millionaire',
        'The Automatic Millionaire',
        'David Bach',
        'Pay yourself first, on the day the money arrives, before you can spend it.',
        'SAVE',
        PlanKey.BASIC,
        'MONEY',
        528682,
        '9780743538411',
        'https://en.wikipedia.org/wiki/David_Bach',
        [SpendingStyle.SAVER, SpendingStyle.BALANCED]
    ),
    book(
        'just-keep-buying',
        'Just Keep Buying',
        'Nick Maggiulli',
        'Saving rate beats the clever trade. Keep buying when the headline is loud.',
        'SAVE',
        PlanKey.PLUS,
        'MONEY',
        14561679,
        '9780857199713',
        'https://en.wikipedia.org/wiki/Nick_Maggiulli',
        [SpendingStyle.SAVER, SpendingStyle.BALANCED]
    ),
    book(
        'enough-bogle',
        'Enough',
        'John C. Bogle',
        'More is not the point. Know when the number is already the life.',
        'SAVE',
        PlanKey.MAX,
        'MONEY',
        6917229,
        '9780470441954',
        'https://en.wikipedia.org/wiki/John_C._Bogle',
        [SpendingStyle.SAVER]
    ),
    book(
        'set-for-life',
        'Set for Life',
        'Scott Trench',
        'The first pile of savings buys freedom of choice. Build that before the lifestyle.',
        'SAVE',
        PlanKey.PLUS,
        'MONEY',
        13236550,
        '9781947200807',
        'https://en.wikipedia.org/wiki/Scott_Trench',
        [SpendingStyle.SAVER]
    ),
    book(
        'quit-like-a-millionaire',
        'Quit Like a Millionaire',
        'Kristy Shen',
        'A couple who saved hard and left the job. The method is frugal, not magic.',
        'SAVE',
        PlanKey.MAX,
        'MONEY',
        11273312,
        '9780525538691',
        'https://en.wikipedia.org/wiki/Kristy_Shen',
        [SpendingStyle.SAVER]
    ),
    book(
        'barefoot-investor',
        'The Barefoot Investor',
        'Scott Pape',
        'Buckets, automation, and a date night for the money. Close to the jars.',
        'SAVE',
        PlanKey.BASIC,
        'MONEY',
        884884,
        '9781841127187',
        'https://en.wikipedia.org/wiki/Scott_Pape',
        [SpendingStyle.SAVER, SpendingStyle.BALANCED]
    ),
    book(
        'your-money-and-your-brain',
        'Your Money and Your Brain',
        'Jason Zweig',
        'The brain treats a loss as a threat. That is why people sell the plan.',
        'SAVE',
        PlanKey.PLUS,
        'MONEY',
        4698261,
        '9780285638044',
        'https://en.wikipedia.org/wiki/Jason_Zweig',
        [SpendingStyle.SAVER, SpendingStyle.BALANCED]
    ),
    book(
        'behavior-gap',
        'The Behavior Gap',
        'Carl Richards',
        'The return you get is the one you can sit through. Behaviour is the leak.',
        'SAVE',
        PlanKey.PLUS,
        'MONEY',
        10213246,
        '9781591844648',
        'https://en.wikipedia.org/wiki/Carl_Richards',
        [SpendingStyle.BALANCED]
    ),
    book(
        'one-page-financial-plan',
        'The One-Page Financial Plan',
        'Carl Richards',
        'One page. What the money is for, and the few moves that serve that.',
        'SAVE',
        PlanKey.BASIC,
        'MONEY',
        8976451,
        '9780241019443',
        'https://en.wikipedia.org/wiki/Carl_Richards',
        [SpendingStyle.BALANCED]
    ),
    book(
        'unshakeable',
        'Unshakeable',
        'Tony Robbins',
        'Stay in the market when you want to run. A short companion to the long one.',
        'SAVE',
        PlanKey.PLUS,
        'MONEY',
        8814861,
        '9781501164606',
        'https://en.wikipedia.org/wiki/Tony_Robbins',
        [SpendingStyle.SAVER]
    ),
    book(
        'algebra-of-wealth',
        'The Algebra of Wealth',
        'Scott Galloway',
        'Focus, stoicism, time, and diversification. Wealth as a formula, not a mood.',
        'SAVE',
        PlanKey.MAX,
        'MONEY',
        15104851,
        '9780593714027',
        'https://en.wikipedia.org/wiki/Scott_Galloway',
        [SpendingStyle.BALANCED]
    ),
    book(
        'millionaire-teacher',
        'Millionaire Teacher',
        'Andrew Hallam',
        'A teacher who got wealthy on a salary. Index funds and a life that is not a performance.',
        'SAVE',
        PlanKey.PLUS,
        'MONEY',
        9524594,
        '9780470830079',
        'https://en.wikipedia.org/wiki/Andrew_Hallam',
        [SpendingStyle.SAVER]
    ),
    book(
        'cashflow-quadrant',
        'Cashflow Quadrant',
        'Robert T. Kiyosaki',
        'Employee, self-employed, owner, investor. The point is which quadrant pays you while you sleep.',
        'EARN',
        PlanKey.PLUS,
        'MONEY',
        288183,
        '9780759561335',
        'https://en.wikipedia.org/wiki/Robert_T._Kiyosaki'
    ),
    book(
        'smart-women-finish-rich',
        'Smart Women Finish Rich',
        'David Bach',
        'A plan written for the person the money talk usually skips. Same jars. Clearer language.',
        'SAVE',
        PlanKey.PLUS,
        'MONEY',
        527569,
        '9780767910293',
        'https://en.wikipedia.org/wiki/David_Bach',
        [SpendingStyle.SAVER]
    ),
    book(
        'year-of-less',
        'The Year of Less',
        'Cait Flanders',
        'She stopped shopping for a year and wrote down what was left. A diary, not a rulebook.',
        'SPEND',
        PlanKey.BASIC,
        'MONEY',
        8801479,
        '9781401953515',
        'https://en.wikipedia.org/wiki/Cait_Flanders',
        [SpendingStyle.SAVER, SpendingStyle.SPENDER]
    ),
    book(
        'life-changing-magic',
        'The Life-Changing Magic of Tidying Up',
        'Marie Kondo',
        'Keep what you use. The rest was Play spending that stayed in the house.',
        'SPEND',
        PlanKey.BASIC,
        'MONEY',
        7367218,
        '9781607747307',
        'https://en.wikipedia.org/wiki/Marie_Kondo',
        [SpendingStyle.SPENDER]
    ),
    book(
        'goodbye-things',
        'Goodbye, Things',
        'Fumio Sasaki',
        'Fewer objects, fewer decisions. A spare room is a spare mind.',
        'SPEND',
        PlanKey.PLUS,
        'MONEY',
        10206062,
        '9781470862879',
        'https://en.wikipedia.org/wiki/Fumio_Sasaki',
        [SpendingStyle.SPENDER]
    ),
    book(
        'broke-millennial',
        'Broke Millennial',
        'Erin Lowry',
        'The first real salary, the first real leaks. Practical, and not ashamed of starting late.',
        'SPEND',
        PlanKey.BASIC,
        'MONEY',
        14626166,
        '9780143130406',
        'https://en.wikipedia.org/wiki/Erin_Lowry',
        [SpendingStyle.SPENDER]
    ),
    book(
        'all-your-worth',
        'All Your Worth',
        'Elizabeth Warren',
        'A split for needs, wants, and savings. Older than the jars, and the same idea.',
        'SPEND',
        PlanKey.PLUS,
        'MONEY',
        6724432,
        '9780743269872',
        'https://en.wikipedia.org/wiki/Elizabeth_Warren',
        [SpendingStyle.BALANCED]
    ),
    book(
        'financial-feminist',
        'Financial Feminist',
        'Tori Dunlap',
        'Money is not a personality. Learn the accounts so nobody else holds them for you.',
        'SPEND',
        PlanKey.PLUS,
        'MONEY',
        13192586,
        '9780063158238',
        'https://en.wikipedia.org/wiki/Tori_Dunlap',
        [SpendingStyle.SPENDER]
    ),
    book(
        'worry-free-money',
        'Worry-Free Money',
        'Shannon Lee Simmons',
        'A spending number you can live inside, so the rest can be saved without panic.',
        'SPEND',
        PlanKey.PLUS,
        'MONEY',
        null,
        '9781443454452',
        'https://en.wikipedia.org/wiki/Shannon_Lee_Simmons',
        [SpendingStyle.BALANCED]
    ),
    book(
        'happy-money',
        'Happy Money',
        'Elizabeth Dunn',
        'Buy experiences and time, not the thing that looks like a win for a week.',
        'SPEND',
        PlanKey.PLUS,
        'MONEY',
        7926235,
        '9781451665079',
        'https://en.wikipedia.org/wiki/Elizabeth_Dunn',
        [SpendingStyle.SPENDER, SpendingStyle.BALANCED]
    ),
    book(
        'love-your-life',
        'Love Your Life, Not Theirs',
        'Rachel Cruze',
        'The feed is a shop window. Spend for your life, not for the comparison.',
        'SPEND',
        PlanKey.PLUS,
        'MONEY',
        13800137,
        '9781666513936',
        'https://en.wikipedia.org/wiki/Rachel_Cruze',
        [SpendingStyle.SPENDER]
    ),
    book(
        'nudge',
        'Nudge',
        'Richard H. Thaler',
        'Defaults decide. Set the good choice as the one that happens if you do nothing.',
        'SPEND',
        PlanKey.PLUS,
        'MONEY',
        6402116,
        '9780143115267',
        'https://en.wikipedia.org/wiki/Richard_H._Thaler',
        [SpendingStyle.BALANCED]
    ),
    book(
        'predictably-irrational',
        'Predictably Irrational',
        'Dan Ariely',
        'Free, anchors, and the sale that is not a sale. See the trick before you pay it.',
        'SPEND',
        PlanKey.PLUS,
        'MONEY',
        2314080,
        '9780062018205',
        'https://en.wikipedia.org/wiki/Dan_Ariely',
        [SpendingStyle.SPENDER]
    ),
    book(
        'misbehaving',
        'Misbehaving',
        'Richard H. Thaler',
        'How economics finally admitted people are not spreadsheets. The story behind Nudge.',
        'MIND',
        PlanKey.MAX,
        'MONEY',
        8270508,
        '9780393352795',
        'https://en.wikipedia.org/wiki/Richard_H._Thaler'
    ),
    book(
        'thinking-in-bets',
        'Thinking in Bets',
        'Annie Duke',
        'A good decision can lose. Judge the choice, not only the outcome.',
        'MIND',
        PlanKey.MAX,
        'MONEY',
        8792782,
        '9780735216372',
        'https://en.wikipedia.org/wiki/Annie_Duke'
    ),
    book(
        'art-of-spending-money',
        'The Art of Spending Money',
        'Morgan Housel',
        'Spending well is a skill, the same as saving. The point of the money is the life.',
        'SPEND',
        PlanKey.MAX,
        'MONEY',
        15142229,
        '9781804091890',
        'https://en.wikipedia.org/wiki/Morgan_Housel',
        [SpendingStyle.SPENDER, SpendingStyle.BALANCED]
    ),
    book(
        'diary-of-a-ceo',
        'The Diary of a CEO',
        'Steven Bartlett',
        'Laws from a working diary: how a person stays in the work long enough to get paid for it.',
        'EARN',
        PlanKey.BASIC,
        'MONEY',
        15208285,
        '9781529146509',
        'https://en.wikipedia.org/wiki/Steven_Bartlett'
    ),
    book(
        'e-myth',
        'The E-Myth Revisited',
        'Michael E. Gerber',
        'A job you gave yourself is not a business. Build the system, or you bought a harder salary.',
        'EARN',
        PlanKey.BASIC,
        'MONEY',
        684209,
        '9780060574901',
        'https://en.wikipedia.org/wiki/Michael_E._Gerber'
    ),
    book(
        'company-of-one',
        'Company of One',
        'Paul Jarvis',
        'Growth is not the only goal. A small company that stays solvent is a success.',
        'EARN',
        PlanKey.PLUS,
        'MONEY',
        8796506,
        '9780241380239',
        'https://en.wikipedia.org/wiki/Paul_Jarvis'
    ),
    book(
        'hundred-dollar-startup',
        'The $100 Startup',
        'Chris Guillebeau',
        'Start with what people already ask you for. Small stake, real offer.',
        'EARN',
        PlanKey.PLUS,
        'MONEY',
        7257004,
        '9780307951526',
        'https://en.wikipedia.org/wiki/Chris_Guillebeau'
    ),
    book(
        'rework',
        'Rework',
        'Jason Fried',
        'Short chapters against busywork. Ship the thing. Meetings are not the product.',
        'EARN',
        PlanKey.PLUS,
        'MONEY',
        6679955,
        '9780307463760',
        'https://en.wikipedia.org/wiki/Jason_Fried'
    ),
    book(
        'lean-startup',
        'The Lean Startup',
        'Eric Ries',
        'Build a small version, learn, then spend. The opposite of betting the jar on a guess.',
        'EARN',
        PlanKey.PLUS,
        'MONEY',
        7104760,
        '9780670921621',
        'https://en.wikipedia.org/wiki/Eric_Ries'
    ),
    book(
        'zero-to-one',
        'Zero to One',
        'Peter Thiel',
        'Competition eats the margin. The useful question is what you can do that others will not.',
        'EARN',
        PlanKey.MAX,
        'MONEY',
        9002334,
        '9780753555194',
        'https://en.wikipedia.org/wiki/Peter_Thiel'
    ),
    book(
        'shoe-dog',
        'Shoe Dog',
        'Phil Knight',
        'Nike was a mess for years. Persistence with a product people already wanted.',
        'EARN',
        PlanKey.BASIC,
        'MONEY',
        8858487,
        '9781508254737',
        'https://en.wikipedia.org/wiki/Phil_Knight'
    ),
    book(
        'built-to-sell',
        'Built to Sell',
        'John Warrillow',
        'If the business dies when you take a week off, you own a job. Make it sellable.',
        'EARN',
        PlanKey.PLUS,
        'MONEY',
        15162903,
        '9781591843979',
        'https://en.wikipedia.org/wiki/John_Warrillow'
    ),
    book(
        'personal-mba',
        'The Personal MBA',
        'Josh Kaufman',
        'The business ideas that matter, without the degree. A map, then you go do one of them.',
        'EARN',
        PlanKey.BASIC,
        'MONEY',
        6713257,
        '9780670919512',
        'https://en.wikipedia.org/wiki/Josh_Kaufman'
    ),
    book(
        'four-hour-workweek',
        'The 4-Hour Workweek',
        'Timothy Ferriss',
        'Question the default week. Take the tactics. Leave the fantasy that work disappears.',
        'EARN',
        PlanKey.PLUS,
        'MONEY',
        539652,
        '9781407061962',
        'https://en.wikipedia.org/wiki/Timothy_Ferriss'
    ),
    book(
        'clockwork',
        'Clockwork',
        'Mike Michalowicz',
        'Design the business so it runs when you are not in the room. The next book after Profit First.',
        'EARN',
        PlanKey.PLUS,
        'MONEY',
        13984143,
        '9780593538173',
        'https://en.wikipedia.org/wiki/Mike_Michalowicz'
    ),
    book(
        'pumpkin-plan',
        'The Pumpkin Plan',
        'Mike Michalowicz',
        'Keep the best clients. Fire the ones that eat the week and pay the least.',
        'EARN',
        PlanKey.MAX,
        'MONEY',
        8711922,
        '9781591844884',
        'https://en.wikipedia.org/wiki/Mike_Michalowicz'
    ),
    book(
        'fix-this-next',
        'Fix This Next',
        'Mike Michalowicz',
        'Sales, profit, order, impact, legacy. Fix the floor you are actually on.',
        'EARN',
        PlanKey.PLUS,
        'MONEY',
        null,
        '9780593084410',
        'https://en.wikipedia.org/wiki/Mike_Michalowicz'
    ),
    book(
        'buy-back-your-time',
        'Buy Back Your Time',
        'Dan Martell',
        'Hire for the tasks that are not your skill. Your hour has a price. Spend it on the work only you do.',
        'EARN',
        PlanKey.MAX,
        'MONEY',
        13239151,
        '9780593422977',
        'https://en.wikipedia.org/wiki/Dan_Martell'
    ),
    book(
        '100m-offers',
        '$100M Offers',
        'Alex Hormozi',
        'Make the offer so clear that the price is not the argument. A system, not a personality.',
        'EARN',
        PlanKey.MAX,
        'MONEY',
        11948182,
        '9781963349030',
        'https://en.wikipedia.org/wiki/Alex_Hormozi'
    ),
    book(
        '100m-leads',
        '$100M Leads',
        'Alex Hormozi',
        'How strangers find the offer. Advertising, content, and the list. Use the method, ignore the volume.',
        'EARN',
        PlanKey.MAX,
        'MARKETING',
        14796132,
        '9781963349047',
        'https://en.wikipedia.org/wiki/Alex_Hormozi'
    ),
    book(
        'almanack-naval',
        'The Almanack of Naval Ravikant',
        'Eric Jorgenson',
        'Specific knowledge, leverage, and accountability. His notes, arranged so you can read them.',
        'EARN',
        PlanKey.PLUS,
        'MONEY',
        10449931,
        '9781544514215',
        'https://www.navalmanack.com/'
    ),
    book(
        'side-hustle',
        'Side Hustle',
        'Chris Guillebeau',
        'A small offer beside the job. Test it in a week, not in a business plan.',
        'EARN',
        PlanKey.PLUS,
        'MONEY',
        10293860,
        '9781524758844',
        'https://en.wikipedia.org/wiki/Chris_Guillebeau'
    ),
    book(
        'so-good',
        "So Good They Can't Ignore You",
        'Cal Newport',
        'Passion follows skill. Get rare and valuable before you quit the salary.',
        'EARN',
        PlanKey.PLUS,
        'MONEY',
        9215292,
        '9780349415871',
        'https://en.wikipedia.org/wiki/Cal_Newport'
    ),
    book(
        'measure-what-matters',
        'Measure What Matters',
        'John Doerr',
        'One objective, a few numbers. A company that tracks everything tracks nothing.',
        'EARN',
        PlanKey.MAX,
        'MONEY',
        9254540,
        '9780241290873',
        'https://en.wikipedia.org/wiki/John_Doerr'
    ),
    book(
        'hard-thing',
        'The Hard Thing About Hard Things',
        'Ben Horowitz',
        'The part after the launch, when people and cash are the problem. No slogans.',
        'EARN',
        PlanKey.MAX,
        'MONEY',
        7279515,
        '9780062273215',
        'https://en.wikipedia.org/wiki/Ben_Horowitz'
    ),
    book(
        'good-to-great',
        'Good to Great',
        'Jim Collins',
        'Discipline and the right people. Read it for the standard, not for the companies that later failed.',
        'EARN',
        PlanKey.PLUS,
        'MONEY',
        7431270,
        '9780694526079',
        'https://en.wikipedia.org/wiki/Jim_Collins'
    ),
    book(
        'high-output-management',
        'High Output Management',
        'Andrew S. Grove',
        'A manager’s output is the output of the team. Meetings, decisions, and leverage.',
        'EARN',
        PlanKey.MAX,
        'MONEY',
        421244,
        '9780330289634',
        'https://en.wikipedia.org/wiki/Andrew_S._Grove'
    ),
    book(
        'ten-x-rule',
        'The 10X Rule',
        'Grant Cardone',
        'Set the target higher than feels polite, then do ten times the activity. Loud, and sometimes useful.',
        'EARN',
        PlanKey.MAX,
        'MONEY',
        9978588,
        '9781283052948',
        'https://en.wikipedia.org/wiki/Grant_Cardone'
    ),
    book(
        'get-different',
        'Get Different',
        'Mike Michalowicz',
        'If you look like everyone else, you compete on price. Be the one they can describe.',
        'EARN',
        PlanKey.MAX,
        'MARKETING',
        10828754,
        '9780593330630',
        'https://en.wikipedia.org/wiki/Mike_Michalowicz'
    ),
    book(
        'never-split',
        'Never Split the Difference',
        'Chris Voss',
        'Tactical empathy for the conversation where the number, or the no, actually matters.',
        'MIND',
        PlanKey.BASIC,
        'COMMUNICATION',
        8365942,
        '9781847941497',
        'https://en.wikipedia.org/wiki/Chris_Voss'
    ),
    book(
        'how-to-win-friends',
        'How to Win Friends and Influence People',
        'Dale Carnegie',
        'Remember the name. Talk about their interest. The room is a skill, not a gift.',
        'MIND',
        PlanKey.BASIC,
        'COMMUNICATION',
        13314878,
        '9781535045865',
        'https://en.wikipedia.org/wiki/Dale_Carnegie'
    ),
    book(
        'crucial-conversations',
        'Crucial Conversations',
        'Kerry Patterson',
        'The talk you have been avoiding is the one that changes the result. Stay in it without the fight.',
        'MIND',
        PlanKey.PLUS,
        'COMMUNICATION',
        1711809,
        '9781260474183',
        'https://en.wikipedia.org/wiki/Kerry_Patterson'
    ),
    book(
        'difficult-conversations',
        'Difficult Conversations',
        'Douglas Stone',
        'What happened, what you feel, and what it means. Separate them or the talk fails.',
        'MIND',
        PlanKey.PLUS,
        'COMMUNICATION',
        2555094,
        '9780553525687',
        'https://en.wikipedia.org/wiki/Douglas_Stone'
    ),
    book(
        'nonviolent-communication',
        'Nonviolent Communication',
        'Marshall B. Rosenberg',
        'Observation, feeling, need, request. A way to ask that does not attack.',
        'MIND',
        PlanKey.PLUS,
        'COMMUNICATION',
        940686,
        '9781892005540',
        'https://en.wikipedia.org/wiki/Marshall_B._Rosenberg'
    ),
    book(
        'talk-like-ted',
        'Talk Like TED',
        'Carmine Gallo',
        'One idea, a story, and a reason to care. For the pitch and the dinner table.',
        'MIND',
        PlanKey.PLUS,
        'COMMUNICATION',
        7316010,
        '9781250041128',
        'https://en.wikipedia.org/wiki/Carmine_Gallo'
    ),
    book(
        'made-to-stick',
        'Made to Stick',
        'Chip Heath',
        'Simple, unexpected, concrete, credible, emotional, story. Why a message survives the week.',
        'MIND',
        PlanKey.PLUS,
        'COMMUNICATION',
        7004880,
        '9780812982008',
        'https://en.wikipedia.org/wiki/Chip_Heath'
    ),
    book(
        'exactly-what-to-say',
        'Exactly What to Say',
        'Phil M. Jones',
        'Short lines for the moment you usually freeze. Magic words, used with care.',
        'MIND',
        PlanKey.BASIC,
        'COMMUNICATION',
        15092604,
        '9781989025000',
        'https://en.wikipedia.org/wiki/Phil_M._Jones'
    ),
    book(
        'how-to-talk-to-anyone',
        'How to Talk to Anyone',
        'Leil Lowndes',
        'Small behaviours that make a stranger stay in the conversation. Practice, not charm.',
        'MIND',
        PlanKey.PLUS,
        'COMMUNICATION',
        58950,
        '9781593160265',
        'https://en.wikipedia.org/wiki/Leil_Lowndes'
    ),
    book(
        'quiet',
        'Quiet',
        'Susan Cain',
        'The loud room is not the only way to lead. Introverts have a way of working. Use it.',
        'MIND',
        PlanKey.PLUS,
        'COMMUNICATION',
        7079753,
        '9780141029191',
        'https://en.wikipedia.org/wiki/Susan_Cain'
    ),
    book(
        'captivate',
        'Captivate',
        'Vanessa Van Edwards',
        'How people read you in the first minutes, and how to be readable on purpose.',
        'MIND',
        PlanKey.MAX,
        'COMMUNICATION',
        10951273,
        '9781524750961',
        'https://en.wikipedia.org/wiki/Vanessa_Van_Edwards'
    ),
    book(
        'thank-you-for-arguing',
        'Thank You for Arguing',
        'Jay Heinrichs',
        'Rhetoric for everyday fights. Win the future relationship, not only the point.',
        'MIND',
        PlanKey.PLUS,
        'COMMUNICATION',
        167966,
        '9780307450562',
        'https://en.wikipedia.org/wiki/Jay_Heinrichs'
    ),
    book(
        'just-listen',
        'Just Listen',
        'Mark Goulston',
        'People cannot hear you until they feel heard. Listening is the first move.',
        'MIND',
        PlanKey.MAX,
        'COMMUNICATION',
        8082622,
        '9780814414040',
        'https://en.wikipedia.org/wiki/Mark_Goulston'
    ),
    book(
        'charisma-myth',
        'The Charisma Myth',
        'Olivia Fox Cabane',
        'Presence, power, and warmth. Charisma is a set of behaviours you can train.',
        'MIND',
        PlanKey.MAX,
        'COMMUNICATION',
        13882953,
        '9781591845942',
        'https://en.wikipedia.org/wiki/Olivia_Fox_Cabane'
    ),
    book(
        'how-to-win-friends-business',
        'How to Stop Worrying and Start Living',
        'Dale Carnegie',
        'Worry spends the night and changes nothing. A method for putting the problem down.',
        'MIND',
        PlanKey.PLUS,
        'COMMUNICATION',
        10829208,
        '9780671349004',
        'https://en.wikipedia.org/wiki/Dale_Carnegie'
    ),
    book(
        'influence',
        'Influence',
        'Robert B. Cialdini',
        'Why a person says yes. Reciprocity, commitment, proof. See it in others before you use it.',
        'EARN',
        PlanKey.BASIC,
        'MARKETING',
        431011,
        '9781886746763',
        'https://en.wikipedia.org/wiki/Robert_B._Cialdini'
    ),
    book(
        'pre-suasion',
        'Pre-Suasion',
        'Robert B. Cialdini',
        'What happens before the ask decides the ask. Set the frame, then speak.',
        'EARN',
        PlanKey.PLUS,
        'MARKETING',
        7880005,
        '9781501109812',
        'https://en.wikipedia.org/wiki/Robert_B._Cialdini'
    ),
    book(
        'storybrand',
        'Building a StoryBrand',
        'Donald Miller',
        'The customer is the hero. You are the guide. One clear message, or they leave.',
        'EARN',
        PlanKey.BASIC,
        'MARKETING',
        8458703,
        '9781400201839',
        'https://en.wikipedia.org/wiki/Donald_Miller'
    ),
    book(
        'they-ask-you-answer',
        'They Ask, You Answer',
        'Marcus Sheridan',
        'Answer the questions people already type. That is the useful kind of being found.',
        'EARN',
        PlanKey.BASIC,
        'MARKETING',
        13158050,
        '9781119611028',
        'https://en.wikipedia.org/wiki/Marcus_Sheridan'
    ),
    book(
        'contagious',
        'Contagious',
        'Jonah Berger',
        'Why some things get repeated. Social currency, stories, and a reason to pass it on.',
        'EARN',
        PlanKey.PLUS,
        'MARKETING',
        9039370,
        '9781471111709',
        'https://en.wikipedia.org/wiki/Jonah_Berger'
    ),
    book(
        'positioning',
        'Positioning',
        'Al Ries',
        'You own a word in their head, or you own nothing. Be first in the category you can win.',
        'EARN',
        PlanKey.PLUS,
        'MARKETING',
        55745,
        '9781932378252',
        'https://en.wikipedia.org/wiki/Al_Ries'
    ),
    book(
        'twenty-two-laws',
        'The 22 Immutable Laws of Marketing',
        'Al Ries',
        'Short laws. The category is the battle. A me-too name loses before the ad runs.',
        'EARN',
        PlanKey.PLUS,
        'MARKETING',
        4009958,
        '9780887305924',
        'https://en.wikipedia.org/wiki/Al_Ries'
    ),
    book(
        'obviously-awesome',
        'Obviously Awesome',
        'April Dunford',
        'Positioning as a process, not a slogan. Who it is for, and what else they would buy.',
        'EARN',
        PlanKey.MAX,
        'MARKETING',
        10194369,
        '9781999023003',
        'https://en.wikipedia.org/wiki/April_Dunford'
    ),
    book(
        'ogilvy-advertising',
        'Ogilvy on Advertising',
        'David Ogilvy',
        'The ad has a job. Do the research. Respect the reader. Still the standard.',
        'EARN',
        PlanKey.PLUS,
        'MARKETING',
        4222376,
        '9781853756153',
        'https://en.wikipedia.org/wiki/David_Ogilvy'
    ),
    book(
        'everybody-writes',
        'Everybody Writes',
        'Ann Handley',
        'The words on the page are the product now. Write like a person, then edit.',
        'EARN',
        PlanKey.PLUS,
        'MARKETING',
        8449611,
        '9781322110233',
        'https://en.wikipedia.org/wiki/Ann_Handley'
    ),
    book(
        'traction',
        'Traction',
        'Gabriel Weinberg',
        'Nineteen ways to be found. Test a few. Do not fall in love with the channel that feels busy.',
        'EARN',
        PlanKey.PLUS,
        'MARKETING',
        9364675,
        '9780241242544',
        'https://en.wikipedia.org/wiki/Gabriel_Weinberg'
    ),
    book(
        'hooked',
        'Hooked',
        'Nir Eyal',
        'How products form habits. Read it to build something useful, and to see when an app is using you.',
        'EARN',
        PlanKey.PLUS,
        'MARKETING',
        12511799,
        '9780670069323',
        'https://en.wikipedia.org/wiki/Nir_Eyal'
    ),
    book(
        'to-sell-is-human',
        'To Sell Is Human',
        'Daniel H. Pink',
        'Everyone is in sales now. Moving someone from no to yes is a craft, not a costume.',
        'EARN',
        PlanKey.PLUS,
        'MARKETING',
        10297418,
        '9781594631900',
        'https://en.wikipedia.org/wiki/Daniel_H._Pink'
    ),
    book(
        'spin-selling',
        'SPIN Selling',
        'Neil Rackham',
        'Situation, problem, implication, need-payoff. Questions that sell the large thing.',
        'EARN',
        PlanKey.MAX,
        'MARKETING',
        55114,
        '9781565112605',
        'https://en.wikipedia.org/wiki/Neil_Rackham'
    ),
    book(
        'challenger-sale',
        'The Challenger Sale',
        'Matthew Dixon',
        'Teach, tailor, take control. The rep who only agrees does not win the hard sale.',
        'EARN',
        PlanKey.MAX,
        'MARKETING',
        7970492,
        '9780670922857',
        'https://en.wikipedia.org/wiki/Matthew_Dixon'
    ),
    book(
        'permission-marketing',
        'Permission Marketing',
        'Seth Godin',
        'Earn the right to talk to them again. Interruption is expensive and tired.',
        'EARN',
        PlanKey.PLUS,
        'MARKETING',
        427916,
        '9780743510127',
        'https://en.wikipedia.org/wiki/Seth_Godin'
    ),
    book(
        'purple-cow',
        'Purple Cow',
        'Seth Godin',
        'Remarkable or invisible. Safe products do not get talked about.',
        'EARN',
        PlanKey.PLUS,
        'MARKETING',
        866008,
        '9781101179741',
        'https://en.wikipedia.org/wiki/Seth_Godin'
    ),
    book(
        'this-is-marketing',
        'This Is Marketing',
        'Seth Godin',
        'Marketing is the generous act of helping someone solve a problem. Not a trick.',
        'EARN',
        PlanKey.PLUS,
        'MARKETING',
        14624926,
        '9780525540830',
        'https://en.wikipedia.org/wiki/Seth_Godin'
    ),
    book(
        'tribes',
        'Tribes',
        'Seth Godin',
        'People want to belong to something. Lead the group that already agrees with the work.',
        'EARN',
        PlanKey.PLUS,
        'MARKETING',
        3371417,
        '9781440644467',
        'https://en.wikipedia.org/wiki/Seth_Godin'
    ),
    book(
        'jab-jab',
        'Jab, Jab, Jab, Right Hook',
        'Gary Vaynerchuk',
        'Give more than you ask. The right hook only lands if the jabs were useful.',
        'EARN',
        PlanKey.PLUS,
        'MARKETING',
        11955993,
        '9780062273062',
        'https://en.wikipedia.org/wiki/Gary_Vaynerchuk'
    ),
    book(
        'crushing-it',
        'Crushing It!',
        'Gary Vaynerchuk',
        'A personal brand is a distribution channel. Show the work. Stay at it.',
        'EARN',
        PlanKey.PLUS,
        'MARKETING',
        8815124,
        '9780062674692',
        'https://en.wikipedia.org/wiki/Gary_Vaynerchuk'
    ),
    book(
        'dotcom-secrets',
        'DotCom Secrets',
        'Russell Brunson',
        'Funnels, in plain diagrams. A machine for an offer. Do not confuse the machine with the product.',
        'EARN',
        PlanKey.MAX,
        'MARKETING',
        13442898,
        '9781469938134',
        'https://en.wikipedia.org/wiki/Russell_Brunson'
    ),
    book(
        'expert-secrets',
        'Expert Secrets',
        'Russell Brunson',
        'How an expert teaches a movement. Story, then the offer. Use it if you actually know the thing.',
        'EARN',
        PlanKey.MAX,
        'MARKETING',
        14464680,
        '9781788178563',
        'https://en.wikipedia.org/wiki/Russell_Brunson'
    ),
    book(
        'content-inc',
        'Content Inc.',
        'Joe Pulizzi',
        'Build the audience before the product. Content is the rent you pay for attention.',
        'EARN',
        PlanKey.PLUS,
        'MARKETING',
        12962196,
        '9781259589652',
        'https://en.wikipedia.org/wiki/Joe_Pulizzi'
    ),
    book(
        'hey-whipple',
        'Hey, Whipple, Squeeze This',
        'Luke Sullivan',
        'A working book on ads that do not insult the reader. Craft, not a template.',
        'EARN',
        PlanKey.MAX,
        'MARKETING',
        13222382,
        '9781119819691',
        'https://en.wikipedia.org/wiki/Luke_Sullivan'
    ),
    book(
        'breakthrough-advertising',
        'Breakthrough Advertising',
        'Eugene M. Schwartz',
        'Awareness and desire. The old book the modern copywriters still steal from.',
        'EARN',
        PlanKey.MAX,
        'MARKETING',
        11942597,
        '9780998503509',
        'https://en.wikipedia.org/wiki/Eugene_M._Schwartz'
    ),
    book(
        'scientific-advertising',
        'Scientific Advertising',
        'Claude C. Hopkins',
        'Test the headline. Measure the result. Advertising as a record, not a guess.',
        'EARN',
        PlanKey.BASIC,
        'MARKETING',
        3337286,
        '9781684112869',
        'https://www.gutenberg.org/ebooks/55738'
    ),
    book(
        'cashvertising',
        'Cashvertising',
        'Drew Eric Whitman',
        'The psychological buttons in a page of copy. Know them so you are harder to fool.',
        'EARN',
        PlanKey.PLUS,
        'MARKETING',
        8537250,
        '9781601630322',
        'https://en.wikipedia.org/wiki/Drew_Eric_Whitman'
    ),
    book(
        'mom-test',
        'The Mom Test',
        'Rob Fitzpatrick',
        'Ask about their life, not your idea. Compliments are not customers.',
        'EARN',
        PlanKey.PLUS,
        'MARKETING',
        10660557,
        '9781492180746',
        'https://en.wikipedia.org/wiki/Rob_Fitzpatrick'
    ),
    book(
        'fanatical-prospecting',
        'Fanatical Prospecting',
        'Jeb Blount',
        'The pipeline is a daily practice. Waiting for inbound is how a month goes quiet.',
        'EARN',
        PlanKey.MAX,
        'MARKETING',
        12685538,
        '9781119144779',
        'https://en.wikipedia.org/wiki/Jeb_Blount'
    ),
    book(
        'gap-selling',
        'Gap Selling',
        'Keenan',
        'The sale is the gap between where they are and where they need to be. Find the gap first.',
        'EARN',
        PlanKey.MAX,
        'MARKETING',
        9670355,
        '9781732891029',
        'https://en.wikipedia.org/wiki/Keenan'
    ),
    book(
        'new-sales-simplified',
        'New Sales. Simplified.',
        'Mike Weinberg',
        'A simple story, a target list, and the calls. No theatre.',
        'EARN',
        PlanKey.MAX,
        'MARKETING',
        12519199,
        '9781469099613',
        'https://en.wikipedia.org/wiki/Mike_Weinberg'
    ),
    book(
        'pitch-anything',
        'Pitch Anything',
        'Oren Klaff',
        'Frame control for the room with the money. Strong medicine. Do not become the cartoon.',
        'EARN',
        PlanKey.MAX,
        'MARKETING',
        7304551,
        '9780071332484',
        'https://en.wikipedia.org/wiki/Oren_Klaff'
    ),
    book(
        'psychology-of-selling',
        'The Psychology of Selling',
        'Brian Tracy',
        'Ask, listen, and close without the flinch. A straightforward sales book.',
        'EARN',
        PlanKey.PLUS,
        'MARKETING',
        13270498,
        '9781418513788',
        'https://en.wikipedia.org/wiki/Brian_Tracy'
    ),
    book(
        'sell-or-be-sold',
        'Sell or Be Sold',
        'Grant Cardone',
        'Selling as a life skill, said at volume. Take the insistence. Leave the contempt.',
        'EARN',
        PlanKey.MAX,
        'MARKETING',
        13181453,
        '9780615399249',
        'https://en.wikipedia.org/wiki/Grant_Cardone'
    ),
    book(
        'show-your-work',
        'Show Your Work!',
        'Austin Kleon',
        'Share the process, not only the finished thing. That is how the right people find you.',
        'EARN',
        PlanKey.PLUS,
        'MARKETING',
        7284188,
        '9780761178972',
        'https://en.wikipedia.org/wiki/Austin_Kleon'
    ),
    book(
        'blue-ocean',
        'Blue Ocean Strategy',
        'W. Chan Kim',
        'Stop fighting in the crowded category. Make the comparison irrelevant.',
        'EARN',
        PlanKey.MAX,
        'MARKETING',
        8219313,
        '9781591396192',
        'https://en.wikipedia.org/wiki/W._Chan_Kim'
    ),
    book(
        'crossing-the-chasm',
        'Crossing the Chasm',
        'Geoffrey A. Moore',
        'Early fans are not the market. The next group needs proof, not vision.',
        'EARN',
        PlanKey.MAX,
        'MARKETING',
        684159,
        '9780887307171',
        'https://en.wikipedia.org/wiki/Geoffrey_A._Moore'
    ),
];
