import { PlanKey, SpendingStyle } from '@rumtelo/contracts';

import { film, type WatchSeedRow } from './watch-row';

/**
 * Films we recommend — trailer on YouTube, stream/rent via JustWatch.
 */
export const WATCH_FILM_SEED: readonly WatchSeedRow[] = [
    film({
        key: 'pursuit-of-happyness',
        name: 'The Pursuit of Happyness',
        creator: 'Gabriele Muccino',
        description:
            'Persistence when the month is empty. A trailer, not the film — we point at it, we do not host it.',
        topic: 'MIND',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: 'DMOBlEcRuw8',
        url: 'https://www.youtube.com/watch?v=DMOBlEcRuw8',
        watchUrl: 'https://www.justwatch.com/nl/movie/the-pursuit-of-happyness',
    }),
    film({
        key: 'minimalism',
        name: 'Minimalism',
        creator: 'The Minimalists',
        description:
            'Keep what you actually use. The rest was never the Education jar. The film itself is on YouTube.',
        topic: 'SAVE',
        minPlan: PlanKey.BASIC,
        spendingStyles: [SpendingStyle.SAVER],
        youtubeId: 'J8DGjUv-Vjc',
        url: 'https://www.youtube.com/watch?v=J8DGjUv-Vjc',
        watchUrl: null,
    }),
    film({
        key: 'the-big-short',
        name: 'The Big Short',
        creator: 'Adam McKay',
        description: 'What spending looks like when nobody names the risk until it is too late.',
        topic: 'SPEND',
        minPlan: PlanKey.PLUS,
        spendingStyles: [SpendingStyle.SPENDER, SpendingStyle.BALANCED],
        youtubeId: 'vgqG3ITMv1Q',
        url: 'https://www.youtube.com/watch?v=vgqG3ITMv1Q',
        watchUrl: 'https://www.justwatch.com/nl/movie/the-big-short',
    }),
    film({
        key: 'the-founder',
        name: 'The Founder',
        creator: 'John Lee Hancock',
        description: 'Persistence, and the cost of it. Own the ground the work sits on.',
        topic: 'EARN',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        youtubeId: 'AX2uz2XYkbo',
        url: 'https://www.youtube.com/watch?v=AX2uz2XYkbo',
        watchUrl: 'https://www.justwatch.com/nl/movie/the-founder',
    }),
    film({
        key: 'moneyball',
        name: 'Moneyball',
        creator: 'Bennett Miller',
        description: 'A small budget beats a loud one when the numbers are honest.',
        topic: 'EARN',
        minPlan: PlanKey.MAX,
        spendingStyles: [],
        youtubeId: 'D1R-LwHbld4',
        url: 'https://www.youtube.com/watch?v=D1R-LwHbld4',
        watchUrl: 'https://www.justwatch.com/nl/movie/moneyball',
    }),
    film({
        key: 'groundhog-day',
        name: 'Groundhog Day',
        creator: 'Harold Ramis',
        description:
            'The same day until the behavior changes. A film about the loop, not a lecture on habits.',
        topic: 'MIND',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: 'GncQtURdcE4',
        url: 'https://www.youtube.com/watch?v=GncQtURdcE4',
        watchUrl: 'https://www.justwatch.com/nl/movie/groundhog-day',
    }),
    film({
        key: 'the-social-network',
        name: 'The Social Network',
        creator: 'David Fincher',
        description: 'A product gets known, and the room that built it does not stay friendly.',
        topic: 'EARN',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: 'lB95KLmpLR4',
        url: 'https://www.youtube.com/watch?v=lB95KLmpLR4',
        watchUrl: 'https://www.justwatch.com/nl/movie/the-social-network',
    }),
    film({
        key: 'hidden-figures',
        name: 'Hidden Figures',
        creator: 'Theodore Melfi',
        description:
            'The work was already good. Getting it seen, and paid, was the rest of the job.',
        topic: 'EARN',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        youtubeId: 'RK8xHq6dfAo',
        url: 'https://www.youtube.com/watch?v=RK8xHq6dfAo',
        watchUrl: 'https://www.justwatch.com/nl/movie/hidden-figures',
    }),
    film({
        key: 'ford-v-ferrari',
        name: 'Ford v Ferrari',
        creator: 'James Mangold',
        description: 'A budget, a deadline, and a craft that will not be rushed for the sponsor.',
        topic: 'EARN',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        youtubeId: 'I3h9Z89U9ZA',
        url: 'https://www.youtube.com/watch?v=I3h9Z89U9ZA',
        watchUrl: 'https://www.justwatch.com/nl/movie/ford-v-ferrari',
    }),
    film({
        key: 'margin-call',
        name: 'Margin Call',
        creator: 'J. C. Chandor',
        description: 'One night when the risk has a number and nobody wants to say it out loud.',
        topic: 'SPEND',
        minPlan: PlanKey.PLUS,
        spendingStyles: [SpendingStyle.SPENDER, SpendingStyle.BALANCED],
        youtubeId: 'IjZ-ke1kJrA',
        url: 'https://www.youtube.com/watch?v=IjZ-ke1kJrA',
        watchUrl: 'https://www.justwatch.com/nl/movie/margin-call',
    }),
    film({
        key: 'inside-job',
        name: 'Inside Job',
        creator: 'Charles Ferguson',
        description: 'Who got paid when the system broke. A warning, not a how-to.',
        topic: 'SPEND',
        minPlan: PlanKey.PLUS,
        spendingStyles: [SpendingStyle.SPENDER],
        youtubeId: 'FzrBurlJUNk',
        url: 'https://www.youtube.com/watch?v=FzrBurlJUNk',
        watchUrl: 'https://www.justwatch.com/nl/movie/inside-job',
    }),
    film({
        key: 'the-farewell',
        name: 'The Farewell',
        creator: 'Lulu Wang',
        description: 'What a family says, and what it refuses to say, when the news is bad.',
        topic: 'RELATIONSHIPS',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        youtubeId: 'RofpAjqwMa8',
        url: 'https://www.youtube.com/watch?v=RofpAjqwMa8',
        watchUrl: 'https://www.justwatch.com/nl/movie/the-farewell',
    }),
    film({
        key: 'free-solo',
        name: 'Free Solo',
        creator: 'Elizabeth Chai Vasarhelyi, Jimmy Chin',
        description: 'Preparation is the whole sport. The climb is the part people film.',
        topic: 'HEALTH',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        youtubeId: 'urRVZ4SW7WU',
        url: 'https://www.youtube.com/watch?v=urRVZ4SW7WU',
        watchUrl: 'https://www.justwatch.com/nl/movie/free-solo',
    }),
    film({
        key: 'steve-jobs',
        name: 'Steve Jobs',
        creator: 'Danny Boyle',
        description: 'A product launch is a conversation. This one shows the cost of winning it.',
        topic: 'EARN',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: 'aEr6K1bwIVs',
        url: 'https://www.youtube.com/watch?v=aEr6K1bwIVs',
        watchUrl: 'https://www.justwatch.com/nl/movie/steve-jobs',
    }),
    film({
        key: 'air',
        name: 'Air',
        creator: 'Ben Affleck',
        description:
            'One deal, one athlete, one bet the company almost refused. How a shoe became a name.',
        topic: 'EARN',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: 'os2tIykAqNA',
        url: 'https://www.youtube.com/watch?v=os2tIykAqNA',
        watchUrl: 'https://www.justwatch.com/nl/movie/air',
    }),
    film({
        key: 'tetris',
        name: 'Tetris',
        creator: 'Jon S. Baird',
        description:
            'Rights, regimes, and a game that would not stay in one country. Dealmaking under pressure.',
        topic: 'EARN',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: '-BLM1naCfME',
        url: 'https://www.youtube.com/watch?v=-BLM1naCfME',
        watchUrl: 'https://www.justwatch.com/nl/movie/tetris',
    }),
    film({
        key: 'joy',
        name: 'Joy',
        creator: 'David O. Russell',
        description:
            'An inventor who had to sell the thing, not only invent it. The Education jar as a door.',
        topic: 'EARN',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: 'uNGlfsRYXG4',
        url: 'https://www.youtube.com/watch?v=uNGlfsRYXG4',
        watchUrl: 'https://www.justwatch.com/nl/movie/joy-2015',
    }),
    film({
        key: 'whiplash',
        name: 'Whiplash',
        creator: 'Damien Chazelle',
        description:
            'Excellence has a cost. How hard you push is a choice — this film refuses to make it soft.',
        topic: 'MIND',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: 'Df1xkYYbYrY',
        url: 'https://www.youtube.com/watch?v=Df1xkYYbYrY',
        watchUrl: 'https://www.justwatch.com/nl/movie/whiplash',
    }),
    film({
        key: 'too-big-to-fail',
        name: 'Too Big to Fail',
        creator: 'Curtis Hanson',
        description: 'A weekend when the system almost ate itself. Who got the call, and who paid.',
        topic: 'SPEND',
        minPlan: PlanKey.PLUS,
        spendingStyles: [SpendingStyle.SPENDER, SpendingStyle.BALANCED],
        youtubeId: '1G4isv_Fylg',
        url: 'https://www.youtube.com/watch?v=1G4isv_Fylg',
        watchUrl: 'https://www.justwatch.com/nl/movie/too-big-to-fail',
    }),
    film({
        key: 'chef',
        name: 'Chef',
        creator: 'Jon Favreau',
        description:
            'Leave the big kitchen, build a small one that feeds people. A business you can taste.',
        topic: 'EARN',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: '6Od4GdC5a8E',
        url: 'https://www.youtube.com/watch?v=6Od4GdC5a8E',
        watchUrl: 'https://www.justwatch.com/nl/movie/chef',
    }),
];
