import { PlanKey, SpendingStyle } from '@rumtelo/contracts';

import { video, type WatchSeedRow } from './watch-row';

/**
 * Standalone talks and clips — the url is the work. We do not host it.
 */
export const WATCH_VIDEO_SEED: readonly WatchSeedRow[] = [
    video({
        key: 'housel-talk',
        name: 'The Psychology of Money, told',
        creator: 'Morgan Housel',
        description:
            'The same idea as the book, said out loud. Time is the part people refuse to wait for.',
        topic: 'SAVE',
        minPlan: PlanKey.PLUS,
        spendingStyles: [SpendingStyle.SAVER, SpendingStyle.BALANCED],
        youtubeId: 'z5W74QC3v2I',
        url: 'https://www.youtube.com/watch?v=z5W74QC3v2I',
        watchUrl: null,
    }),
    video({
        key: 'naval-rich',
        name: 'How to Get Rich (without getting lucky)',
        creator: 'Naval Ravikant',
        description:
            'Specific knowledge, leverage, and accountability. His own notes, not a summary channel.',
        topic: 'EARN',
        minPlan: PlanKey.MAX,
        spendingStyles: [],
        youtubeId: null,
        url: 'https://nav.al/rich',
        watchUrl: null,
    }),
    video({
        key: 'brene-vulnerability',
        name: 'The Power of Vulnerability',
        creator: 'Brené Brown',
        description: 'The talk on what happens when you stop performing and say the true thing.',
        topic: 'RELATIONSHIPS',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: 'iCvmsMzlF7o',
        url: 'https://www.youtube.com/watch?v=iCvmsMzlF7o',
        watchUrl: null,
    }),
    video({
        key: 'sinek-why',
        name: 'How Great Leaders Inspire Action',
        creator: 'Simon Sinek',
        description:
            'Start with why. A short talk on the sentence people can repeat after you leave the room.',
        skill: 'LEADERSHIP',
        topic: 'EARN',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: 'qp0HIF3SfI4',
        url: 'https://www.youtube.com/watch?v=qp0HIF3SfI4',
        watchUrl: null,
    }),
    video({
        key: 'duckworth-grit',
        name: 'Grit',
        creator: 'Angela Duckworth',
        description:
            'Passion and perseverance, said plainly. The long game is a practice, not a mood.',
        topic: 'MIND',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: 'H14bBuluwB8',
        url: 'https://www.youtube.com/watch?v=H14bBuluwB8',
        watchUrl: null,
    }),
    video({
        key: 'achor-better-work',
        name: 'The Happy Secret to Better Work',
        creator: 'Shawn Achor',
        description: 'The advantage is not the next win. It is the state you work from.',
        topic: 'MIND',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: 'fLJsdqxnZb0',
        url: 'https://www.youtube.com/watch?v=fLJsdqxnZb0',
        watchUrl: null,
    }),
    video({
        key: 'mcgonigal-stress',
        name: 'How to Make Stress Your Friend',
        creator: 'Kelly McGonigal',
        description: 'Stress is a signal, not a verdict. A short talk before the week gets loud.',
        topic: 'HEALTH',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        youtubeId: 'RcGyVTAoXEU',
        url: 'https://www.youtube.com/watch?v=RcGyVTAoXEU',
        watchUrl: null,
    }),
    video({
        key: 'walker-sleep',
        name: 'Sleep Is Your Superpower',
        creator: 'Matthew Walker',
        description: 'The same case as the book, in one sitting. The night is part of the work.',
        topic: 'HEALTH',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        youtubeId: '5MuIMqhT8DM',
        url: 'https://www.youtube.com/watch?v=5MuIMqhT8DM',
        watchUrl: null,
    }),
    video({
        key: 'ariely-decisions',
        name: 'Are We in Control of Our Decisions?',
        creator: 'Dan Ariely',
        description: 'Why the sensible choice loses to the one that was placed in front of you.',
        topic: 'SPEND',
        minPlan: PlanKey.PLUS,
        spendingStyles: [SpendingStyle.SPENDER, SpendingStyle.BALANCED],
        youtubeId: '9X68dm92HVI',
        url: 'https://www.youtube.com/watch?v=9X68dm92HVI',
        watchUrl: null,
    }),
    video({
        key: 'cain-introverts',
        name: 'The Power of Introverts',
        creator: 'Susan Cain',
        description:
            'The quiet person in the room is not behind. A talk on how the work actually gets made.',
        topic: 'MIND',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        youtubeId: 'c0KYU2j0TM4',
        url: 'https://www.youtube.com/watch?v=c0KYU2j0TM4',
        watchUrl: null,
    }),
    video({
        key: 'perel-desire',
        name: 'The Secret to Desire in a Long-term Relationship',
        creator: 'Esther Perel',
        description:
            'Closeness and wanting are not the same job. A talk for the relationship, not the calendar.',
        topic: 'RELATIONSHIPS',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        youtubeId: 'sa0RUmGTCYY',
        url: 'https://www.youtube.com/watch?v=sa0RUmGTCYY',
        watchUrl: null,
    }),
    video({
        key: 'clear-atomic',
        name: 'Atomic Habits, told',
        creator: 'James Clear',
        description: 'One percent, said by the person who wrote the book. Not a summary channel.',
        topic: 'MIND',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        youtubeId: 'U_nzqnXWvSo',
        url: 'https://www.youtube.com/watch?v=U_nzqnXWvSo',
        watchUrl: null,
    }),
    video({
        key: 'voss-negotiate',
        name: 'Never Split the Difference, told',
        creator: 'Chris Voss',
        description: 'Tactical empathy from the person who wrote it. A talk, not a clip account.',
        topic: 'EARN',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        youtubeId: 'guZa7mQV1l0',
        url: 'https://www.youtube.com/watch?v=guZa7mQV1l0',
        watchUrl: null,
    }),
    video({
        key: 'godin-ideas',
        name: 'How to Get Your Ideas to Spread',
        creator: 'Seth Godin',
        description: 'Remarkable is a choice about who the work is for, not a louder ad.',
        topic: 'EARN',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        youtubeId: 'xBIVlM435Zg',
        url: 'https://www.youtube.com/watch?v=xBIVlM435Zg',
        watchUrl: null,
    }),
    video({
        key: 'kwik-limitless',
        name: 'Limitless',
        creator: 'Jim Kwik',
        description:
            'The boy with the broken brain, said by him. How to learn faster when school left you behind.',
        topic: 'MIND',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: 'Wq93se1kI00',
        url: 'https://www.youtube.com/watch?v=Wq93se1kI00',
        watchUrl: null,
    }),
    video({
        key: 'kwik-fast-learn',
        name: 'Speed Learning: Learn In Half The Time',
        creator: 'Jim Kwik',
        description:
            'Forget, Active, State, Teach. A short drill for the Education jar, not a shortcut ad.',
        topic: 'MIND',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: '0r1LTe5KkSA',
        url: 'https://www.youtube.com/watch?v=0r1LTe5KkSA',
        watchUrl: null,
    }),
    video({
        key: 'dweck-yet',
        name: 'The Power of Believing That You Can Improve',
        creator: 'Carol Dweck',
        description: 'Not yet. The sentence that turns a closed door into the next attempt.',
        topic: 'MIND',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: '_X0mgOOSpLU',
        url: 'https://www.youtube.com/watch?v=_X0mgOOSpLU',
        watchUrl: null,
    }),
    video({
        key: 'robbins-five-seconds',
        name: 'How to Stop Screwing Yourself Over',
        creator: 'Mel Robbins',
        description:
            'Five seconds between the impulse and the brake. Act before the mind kills the idea.',
        topic: 'MIND',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: 'Lp7E973zozc',
        url: 'https://www.youtube.com/watch?v=Lp7E973zozc',
        watchUrl: null,
    }),
    video({
        key: 'ferriss-fears',
        name: 'Why You Should Define Your Fears Instead of Your Goals',
        creator: 'Tim Ferriss',
        description:
            'Fear-setting before goal-setting. Name the worst case so the next move is smaller.',
        topic: 'EARN',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        youtubeId: '5J6jAC6XxAI',
        url: 'https://www.youtube.com/watch?v=5J6jAC6XxAI',
        watchUrl: null,
    }),
    video({
        key: 'pollan-plants',
        name: "A Plant's-Eye View",
        creator: 'Michael Pollan',
        description:
            'What we eat is not only about us. A talk that makes the plate a relationship, not a diet war.',
        topic: 'HEALTH',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: 'p54VVLSS6Qk',
        url: 'https://www.youtube.com/watch?v=p54VVLSS6Qk',
        watchUrl: null,
    }),
    video({
        key: 'pollan-cooked',
        name: 'Cooked',
        creator: 'Michael Pollan',
        description:
            'Cooking is the work that turns ingredients into a household meal. Talks at Google.',
        topic: 'HEALTH',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        youtubeId: 'lVyo712BBRk',
        url: 'https://www.youtube.com/watch?v=lVyo712BBRk',
        watchUrl: null,
    }),
    video({
        key: 'greger-food-medicine',
        name: 'Food as Medicine',
        creator: 'Michael Greger',
        description: 'Diet as the largest risk we still control. A TEDx talk — not a prescription.',
        topic: 'HEALTH',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        youtubeId: 'xnKaOL2IBPY',
        url: 'https://www.youtube.com/watch?v=xnKaOL2IBPY',
        watchUrl: null,
    }),
    video({
        key: 'jobs-live',
        name: 'How to Live Before You Die',
        creator: 'Steve Jobs',
        description:
            'The Stanford talk almost every “successful people watch this” list still opens with. Connect the dots looking back.',
        topic: 'MIND',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: 'UF8uR6Z6KLc',
        url: 'https://www.youtube.com/watch?v=UF8uR6Z6KLc',
        watchUrl: null,
    }),
    video({
        key: 'pink-motivation',
        name: 'The Puzzle of Motivation',
        creator: 'Dan Pink',
        description:
            'Autonomy, mastery, purpose. Why the carrot and stick fails for work that needs a brain.',
        topic: 'EARN',
        skill: 'LEADERSHIP',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: 'rrkrvAUbU9Y',
        url: 'https://www.youtube.com/watch?v=rrkrvAUbU9Y',
        watchUrl: null,
    }),
    video({
        key: 'urban-procrastinate',
        name: 'Inside the Mind of a Master Procrastinator',
        creator: 'Tim Urban',
        description:
            'The Instant Gratification Monkey. The panic that only shows up when the deadline is close.',
        topic: 'MIND',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: 'arj7oStGLkU',
        url: 'https://www.youtube.com/watch?v=arj7oStGLkU',
        watchUrl: null,
    }),
    video({
        key: 'robinson-creativity',
        name: 'Do Schools Kill Creativity?',
        creator: 'Ken Robinson',
        description:
            'The most-watched TED talk for a reason. Creativity is not a hobby at the edge of a useful life.',
        topic: 'MIND',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: 'iG9CE55wbtY',
        url: 'https://www.youtube.com/watch?v=iG9CE55wbtY',
        watchUrl: null,
    }),
    video({
        key: 'sivers-movement',
        name: 'How to Start a Movement',
        creator: 'Derek Sivers',
        description:
            'The first follower turns a lone nut into a leader. Three minutes every founder list still shares.',
        topic: 'EARN',
        skill: 'LEADERSHIP',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: 'V74AxCqOTvg',
        url: 'https://www.youtube.com/watch?v=V74AxCqOTvg',
        watchUrl: null,
    }),
    video({
        key: 'sivers-goals',
        name: 'Keep Your Goals to Yourself',
        creator: 'Derek Sivers',
        description:
            'Saying the goal out loud can feel like doing it. Quiet work until it is real.',
        topic: 'MIND',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: 'NHopJHSlVo4',
        url: 'https://www.youtube.com/watch?v=NHopJHSlVo4',
        watchUrl: null,
    }),
    video({
        key: 'grant-givers',
        name: 'Are You a Giver or a Taker?',
        creator: 'Adam Grant',
        description:
            'Givers finish first when takers are weeded out. The five-minute favor that builds a network.',
        topic: 'EARN',
        skill: 'LEADERSHIP',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        youtubeId: 'YyXRYgjQXX0',
        url: 'https://www.youtube.com/watch?v=YyXRYgjQXX0',
        watchUrl: null,
    }),
    video({
        key: 'treasure-speak',
        name: 'How to Speak So That People Want to Listen',
        creator: 'Julian Treasure',
        description:
            'HAIL: honesty, authenticity, integrity, love. How the voice lands before the idea does.',
        topic: 'MIND',
        skill: 'COMMUNICATION',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        youtubeId: 'eIho2S0ZahI',
        url: 'https://www.youtube.com/watch?v=eIho2S0ZahI',
        watchUrl: null,
    }),
    video({
        key: 'gilbert-genius',
        name: 'Your Elusive Creative Genius',
        creator: 'Elizabeth Gilbert',
        description:
            'Show up for your part of the job. Genius is not a personality you have to carry alone.',
        topic: 'MIND',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: '86x-u-tz0MA',
        url: 'https://www.youtube.com/watch?v=86x-u-tz0MA',
        watchUrl: null,
    }),
    video({
        key: 'jiang-rejection',
        name: 'What I Learned from 100 Days of Rejection',
        creator: 'Jia Jiang',
        description:
            'Ask anyway. Rejection therapy for the fear that keeps a pitch, a raise, or a sale unsaid.',
        topic: 'EARN',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: 'iwl-Pe0FbSg',
        url: 'https://www.youtube.com/watch?v=iwl-Pe0FbSg',
        watchUrl: null,
    }),
    video({
        key: 'vanderkam-time',
        name: 'How to Gain Control of Your Free Time',
        creator: 'Laura Vanderkam',
        description:
            '168 hours. Busy people still have edges — the week is larger than the story you tell about it.',
        topic: 'MIND',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        youtubeId: 'n3kNlFMXslo',
        url: 'https://www.youtube.com/watch?v=n3kNlFMXslo',
        watchUrl: null,
    }),
    video({
        key: 'robbins-why',
        name: 'Why We Do What We Do',
        creator: 'Tony Robbins',
        description: 'The six needs under every decision. A classic on drive, not a seminar pitch.',
        topic: 'MIND',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        youtubeId: 'BwFOwyoH-3g',
        url: 'https://www.youtube.com/watch?v=BwFOwyoH-3g',
        watchUrl: null,
    }),
    video({
        key: 'watts-on-being',
        name: 'Alan Watts — talks on being',
        creator: 'Alan Watts',
        description:
            'Lectures on presence and the self. Start at the foundation that keeps the recordings in print.',
        topic: 'MIND',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        youtubeId: null,
        url: 'https://alanwatts.org/',
        watchUrl: null,
    }),
];
