import { PlanKey } from '@rumtelo/contracts';

import { podcast, type WatchSeedRow } from './watch-row';

/**
 * Show-level podcast pointers — Spotify to listen, show page as secondary.
 */
export const WATCH_PODCAST_SEED: readonly WatchSeedRow[] = [
    podcast({
        key: 'diary-of-a-ceo-podcast',
        name: 'The Diary of a CEO',
        creator: 'Steven Bartlett',
        description:
            'Long interviews with people who built something. Listen for the decision, not the highlight reel.',
        topic: 'EARN',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: null,
        url: 'https://www.youtube.com/@TheDiaryOfACEO',
        watchUrl: 'https://open.spotify.com/show/7iQXmUT7XGuZSzAMjoNWlX',
    }),
    podcast({
        key: 'how-i-built-this',
        name: 'How I Built This',
        creator: 'Guy Raz',
        description:
            'The messy middle of building a company — the near-misses, not the victory lap.',
        topic: 'EARN',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: null,
        url: 'https://www.npr.org/podcasts/510313/how-i-built-this',
        watchUrl: 'https://open.spotify.com/show/6E709HRH7XaiZrMfgtNCun',
    }),
    podcast({
        key: 'tim-ferriss-show',
        name: 'The Tim Ferriss Show',
        creator: 'Tim Ferriss',
        description:
            'Long-form tactics from people who ship. Steal the process, skip the guru glow.',
        topic: 'MIND',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: null,
        url: 'https://tim.blog/podcast/',
        watchUrl: 'https://open.spotify.com/show/5qSUyCrk9KR69lEiXbjwXM',
    }),
    podcast({
        key: 'acquired-podcast',
        name: 'Acquired',
        creator: 'Ben Gilbert & David Rosenthal',
        description:
            'Company history as a playbook. How the winners were built — and what almost killed them.',
        topic: 'EARN',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: null,
        url: 'https://www.acquired.fm/',
        watchUrl: 'https://open.spotify.com/show/7Fj0XEuUQLUqoMZQdsLXqp',
    }),
    podcast({
        key: 'huberman-lab',
        name: 'Huberman Lab',
        creator: 'Andrew Huberman',
        description: 'Science you can act on — sleep, focus, stress. Tools first, ego second.',
        topic: 'HEALTH',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: null,
        url: 'https://www.hubermanlab.com/',
        watchUrl: 'https://open.spotify.com/show/79CkJF3UJTHFV8Dse3Oy0P',
    }),
    podcast({
        key: 'masters-of-scale',
        name: 'Masters of Scale',
        creator: 'Reid Hoffman',
        description:
            'How operators grew past the first floor. Steal the pattern, skip the victory lap.',
        topic: 'EARN',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: null,
        url: 'https://mastersofscale.com/',
        watchUrl: 'https://open.spotify.com/show/1bJRgaFZHuzifad4IAApFR',
    }),
    podcast({
        key: 'founders-podcast',
        name: 'Founders',
        creator: 'David Senra',
        description:
            'Biographies of people who built. History as a playbook — what they repeated, what they cut.',
        topic: 'EARN',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: null,
        url: 'https://www.founderspodcast.com/',
        watchUrl: 'https://open.spotify.com/show/7txiovdzPARhjm18NwMUYj',
    }),
    podcast({
        key: 'my-first-million',
        name: 'My First Million',
        creator: 'Sam Parr & Shaan Puri',
        description: 'Idea velocity with a cash filter. Listen for the wedge, not the hype stack.',
        topic: 'EARN',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: null,
        url: 'https://www.mfmpod.com/',
        watchUrl: 'https://open.spotify.com/show/3mliji9352UAk3XnWElnDV',
    }),
    podcast({
        key: 'knowledge-project',
        name: 'The Knowledge Project',
        creator: 'Shane Parrish',
        description: 'Clear thinking under pressure. Decision quality before the next move.',
        topic: 'MIND',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: null,
        url: 'https://fs.blog/knowledge-project-podcast/',
        watchUrl: 'https://open.spotify.com/show/1VyK52NSZHaDKeMJzT4TSM',
    }),
    podcast({
        key: 'lex-fridman-podcast',
        name: 'Lex Fridman Podcast',
        creator: 'Lex Fridman',
        description:
            'Long conversations with builders and researchers. Stay for the trade-offs, leave the mythology.',
        topic: 'MIND',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: null,
        url: 'https://lexfridman.com/podcast/',
        watchUrl: 'https://open.spotify.com/show/2MAi0BvDc6GTFvKFPXnkCL',
    }),
    podcast({
        key: 'planet-money',
        name: 'Planet Money',
        creator: 'NPR',
        description:
            'How money moves in the real world — short stories that make the system visible.',
        topic: 'SAVE',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: null,
        url: 'https://www.npr.org/sections/money/',
        watchUrl: 'https://open.spotify.com/show/4FYpq3lSeQMAhqNI81O0Cn',
    }),
    podcast({
        key: 'lennys-podcast',
        name: "Lenny's Podcast",
        creator: 'Lenny Rachitsky',
        description:
            'Product and growth from people who shipped. Steal the process, ignore the brand deck.',
        topic: 'EARN',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        youtubeId: null,
        url: 'https://www.lennyspodcast.com/',
        watchUrl: 'https://open.spotify.com/show/2dR1MUZEHCOnz1LVfNac0j',
    }),
    podcast({
        key: 'invest-like-the-best',
        name: 'Invest Like the Best',
        creator: "Patrick O'Shaughnessy",
        description:
            'Operators and investors on how they allocate time and capital. Ideas first, ticker second.',
        topic: 'EARN',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        youtubeId: null,
        url: 'https://colossus.com/series/invest-like-the-best/',
        watchUrl: 'https://open.spotify.com/show/22fi0RqfoBACCuQDv97wFO',
    }),
];
