import { PlanKey } from '@rumtelo/contracts';

import { course, type WatchSeedRow } from './watch-row';

/**
 * Course pointers — Udemy on Basic/Plus, MasterClass on Max (merchantKey filter on the client).
 * merchantKey is MerchantPreset.key (UDEMY, MASTERCLASS, …). We do not host the class.
 */
export const WATCH_COURSE_SEED: readonly WatchSeedRow[] = [
    course({
        key: 'udemy-communication',
        name: 'Communication Skills Master Class',
        creator: 'TJ Walker',
        description:
            'Interviews, raises, rooms, and the one-to-one. A practical class, not a lecture series.',
        skill: 'COMMUNICATION',
        topic: 'MIND',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: null,
        url: 'https://www.udemy.com/course/the-complete-communication-skills-master-class-for-life/',
        watchUrl: null,
        merchantKey: 'UDEMY',
    }),
    course({
        key: 'udemy-marketing',
        name: 'Marketing Strategy: Winning Messages',
        creator: 'TJ Walker',
        description: 'Cut a hundred messages down to the three a stranger can repeat.',
        skill: 'MARKETING',
        topic: 'EARN',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: null,
        url: 'https://www.udemy.com/course/how-to-create-winning-messages/',
        watchUrl: null,
        merchantKey: 'UDEMY',
    }),
    course({
        key: 'udemy-digital-marketing',
        name: 'The Complete Digital Marketing Course',
        creator: 'Rob Percival',
        description:
            'Search, ads, and the page a stranger lands on. Practical, not a brand manifesto.',
        skill: 'MARKETING',
        topic: 'EARN',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: null,
        url: 'https://www.udemy.com/course/the-complete-digital-marketing-course-12-courses-in-1/',
        watchUrl: null,
        merchantKey: 'UDEMY',
    }),
    course({
        key: 'mc-voss',
        name: 'The Art of Negotiation',
        creator: 'Chris Voss',
        description:
            'Tactical empathy for the conversations where the number, or the no, actually matters.',
        skill: 'COMMUNICATION',
        topic: 'MIND',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: null,
        url: 'https://www.masterclass.com/classes/chris-voss-teaches-the-art-of-negotiation',
        watchUrl: null,
        merchantKey: 'MASTERCLASS',
    }),
    course({
        key: 'mc-pink',
        name: 'Sales and Persuasion',
        creator: 'Daniel Pink',
        description: 'How to frame an offer so the right person can say yes without being pushed.',
        skill: 'MARKETING',
        topic: 'EARN',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: null,
        url: 'https://www.masterclass.com/classes/daniel-pink-teaches-sales-and-persuasion',
        watchUrl: null,
        merchantKey: 'MASTERCLASS',
    }),
    course({
        key: 'mc-blakely',
        name: 'Self-Made Entrepreneurship',
        creator: 'Sara Blakely',
        description: 'Invent, sell, and get a product known — bootstrapped, not borrowed.',
        skill: 'MONEY',
        topic: 'EARN',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: null,
        url: 'https://www.masterclass.com/classes/sara-blakely-teaches-self-made-entrepreneurship',
        watchUrl: null,
        merchantKey: 'MASTERCLASS',
    }),
    course({
        key: 'mc-iger',
        name: 'Business Strategy and Leadership',
        creator: 'Bob Iger',
        description:
            'Three priorities, then the capital follows. How Disney was steered, not decorated.',
        skill: 'LEADERSHIP',
        topic: 'EARN',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: null,
        url: 'https://www.masterclass.com/classes/bob-iger-teaches-business-strategy-and-leadership',
        watchUrl: null,
        merchantKey: 'MASTERCLASS',
    }),
    course({
        key: 'mc-wintour',
        name: 'Creativity and Leadership',
        creator: 'Anna Wintour',
        description:
            'A point of view, a room that can hold it, and the edit that makes the work recognizable.',
        skill: 'LEADERSHIP',
        topic: 'EARN',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: null,
        url: 'https://www.masterclass.com/classes/anna-wintour-teaches-creativity-and-leadership',
        watchUrl: null,
        merchantKey: 'MASTERCLASS',
    }),
    course({
        key: 'mc-gladwell',
        name: 'Writing',
        creator: 'Malcolm Gladwell',
        description: 'How a strange fact becomes a sentence someone else can retell.',
        skill: 'COMMUNICATION',
        topic: 'MIND',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: null,
        url: 'https://www.masterclass.com/classes/malcolm-gladwell-teaches-writing',
        watchUrl: null,
        merchantKey: 'MASTERCLASS',
    }),
    course({
        key: 'mc-sorkin',
        name: 'Screenwriting',
        creator: 'Aaron Sorkin',
        description: 'Intention and obstacle. The same shape as a hard conversation.',
        skill: 'COMMUNICATION',
        topic: 'MIND',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: null,
        url: 'https://www.masterclass.com/classes/aaron-sorkin-teaches-screenwriting',
        watchUrl: null,
        merchantKey: 'MASTERCLASS',
    }),
    course({
        key: 'mc-rhimes',
        name: 'Writing for Television',
        creator: 'Shonda Rhimes',
        description: 'Say the thing, then say it so the room stays. A class on holding attention.',
        skill: 'COMMUNICATION',
        topic: 'MIND',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: null,
        url: 'https://www.masterclass.com/classes/shonda-rhimes-teaches-writing-for-television',
        watchUrl: null,
        merchantKey: 'MASTERCLASS',
    }),
    course({
        key: 'mc-dvf',
        name: 'Building a Fashion Business',
        creator: 'Diane von Furstenberg',
        description: 'One product people can name, then the discipline to keep it that.',
        skill: 'MARKETING',
        topic: 'EARN',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: null,
        url: 'https://www.masterclass.com/classes/diane-von-furstenberg-teaches-building-a-fashion-business',
        watchUrl: null,
        merchantKey: 'MASTERCLASS',
    }),
];
