import { LearnWatchKind, PlanKey, SpendingStyle, type LearnWatchPreset } from '@rumtelo/contracts';

/**
 * Canonical Learn watch shelf — films, YouTube, and series.
 * Loaded into backoffice.reference_growth_watch_preset.
 * A YouTube id is the poster. The url is the trailer or talk. watchUrl is where to
 * stream or rent it (JustWatch, NL). Null when the url already is the full work. We do not host the work.
 */
export const WATCH_PRESET_SEED: readonly (Omit<LearnWatchPreset, 'sortOrder' | 'skill'> & {
    skill?: string;
})[] = [
    {
        key: 'pursuit-of-happyness',
        name: 'The Pursuit of Happyness',
        creator: 'Gabriele Muccino',
        description:
            'Persistence when the month is empty. A trailer, not the film — we point at it, we do not host it.',
        topic: 'MIND',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        format: LearnWatchKind.FILM,
        youtubeId: 'DMOBlEcRuw8',
        url: 'https://www.youtube.com/watch?v=DMOBlEcRuw8',
        watchUrl: 'https://www.justwatch.com/nl/movie/the-pursuit-of-happyness',
    },
    {
        key: 'minimalism',
        name: 'Minimalism',
        creator: 'The Minimalists',
        description:
            'Keep what you actually use. The rest was never the Education jar. The film itself is on YouTube.',
        topic: 'SAVE',
        minPlan: PlanKey.BASIC,
        spendingStyles: [SpendingStyle.SAVER],
        format: LearnWatchKind.FILM,
        youtubeId: 'J8DGjUv-Vjc',
        url: 'https://www.youtube.com/watch?v=J8DGjUv-Vjc',
        watchUrl: null,
    },
    {
        key: 'the-big-short',
        name: 'The Big Short',
        creator: 'Adam McKay',
        description: 'What spending looks like when nobody names the risk until it is too late.',
        topic: 'SPEND',
        minPlan: PlanKey.PLUS,
        spendingStyles: [SpendingStyle.SPENDER, SpendingStyle.BALANCED],
        format: LearnWatchKind.FILM,
        youtubeId: 'vgqG3ITMv1Q',
        url: 'https://www.youtube.com/watch?v=vgqG3ITMv1Q',
        watchUrl: 'https://www.justwatch.com/nl/movie/the-big-short',
    },
    {
        key: 'the-founder',
        name: 'The Founder',
        creator: 'John Lee Hancock',
        description: 'Persistence, and the cost of it. Own the ground the work sits on.',
        topic: 'EARN',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        format: LearnWatchKind.FILM,
        youtubeId: 'AX2uz2XYkbo',
        url: 'https://www.youtube.com/watch?v=AX2uz2XYkbo',
        watchUrl: 'https://www.justwatch.com/nl/movie/the-founder',
    },
    {
        key: 'housel-talk',
        name: 'The Psychology of Money, told',
        creator: 'Morgan Housel',
        description:
            'The same idea as the book, said out loud. Time is the part people refuse to wait for.',
        topic: 'SAVE',
        minPlan: PlanKey.PLUS,
        spendingStyles: [SpendingStyle.SAVER, SpendingStyle.BALANCED],
        format: LearnWatchKind.VIDEO,
        youtubeId: 'z5W74QC3v2I',
        url: 'https://www.youtube.com/watch?v=z5W74QC3v2I',
        watchUrl: null,
    },
    {
        key: 'how-to-get-rich',
        name: 'How to Get Rich',
        creator: 'Ramit Sethi',
        description:
            'Spend on what you named. Cut what you did not. A series about that split, not a lecture.',
        topic: 'SPEND',
        minPlan: PlanKey.PLUS,
        spendingStyles: [SpendingStyle.SPENDER, SpendingStyle.BALANCED],
        format: LearnWatchKind.SERIES,
        youtubeId: 'QlyDIP9jEck',
        url: 'https://www.youtube.com/watch?v=QlyDIP9jEck',
        watchUrl: 'https://www.justwatch.com/nl/tv-series/how-to-get-rich',
    },
    {
        key: 'moneyball',
        name: 'Moneyball',
        creator: 'Bennett Miller',
        description: 'A small budget beats a loud one when the numbers are honest.',
        topic: 'EARN',
        minPlan: PlanKey.MAX,
        spendingStyles: [],
        format: LearnWatchKind.FILM,
        youtubeId: 'D1R-LwHbld4',
        url: 'https://www.youtube.com/watch?v=D1R-LwHbld4',
        watchUrl: 'https://www.justwatch.com/nl/movie/moneyball',
    },
    {
        key: 'naval-rich',
        name: 'How to Get Rich (without getting lucky)',
        creator: 'Naval Ravikant',
        description:
            'Specific knowledge, leverage, and accountability. His own notes, not a summary channel.',
        topic: 'EARN',
        minPlan: PlanKey.MAX,
        spendingStyles: [],
        format: LearnWatchKind.VIDEO,
        youtubeId: null,
        url: 'https://nav.al/rich',
        watchUrl: null,
    },
    {
        key: 'the-fixer',
        name: 'The Fixer',
        creator: 'Marcus Lemonis',
        description:
            'A business is a set of leaks. This is someone walking the floor and naming them.',
        topic: 'SPEND',
        minPlan: PlanKey.MAX,
        spendingStyles: [SpendingStyle.SPENDER],
        format: LearnWatchKind.SERIES,
        youtubeId: 'janFurHb8t0',
        url: 'https://www.youtube.com/watch?v=janFurHb8t0',
        watchUrl: null,
    },
    {
        key: 'groundhog-day',
        name: 'Groundhog Day',
        creator: 'Harold Ramis',
        description:
            'The same day until the behaviour changes. A film about the loop, not a lecture on habits.',
        topic: 'MIND',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        format: LearnWatchKind.FILM,
        youtubeId: 'GncQtURdcE4',
        url: 'https://www.youtube.com/watch?v=GncQtURdcE4',
        watchUrl: 'https://www.justwatch.com/nl/movie/groundhog-day',
    },
    {
        key: 'the-social-network',
        name: 'The Social Network',
        creator: 'David Fincher',
        description: 'A product gets known, and the room that built it does not stay friendly.',
        topic: 'EARN',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        format: LearnWatchKind.FILM,
        youtubeId: 'lB95KLmpLR4',
        url: 'https://www.youtube.com/watch?v=lB95KLmpLR4',
        watchUrl: 'https://www.justwatch.com/nl/movie/the-social-network',
    },
    {
        key: 'hidden-figures',
        name: 'Hidden Figures',
        creator: 'Theodore Melfi',
        description:
            'The work was already good. Getting it seen, and paid, was the rest of the job.',
        topic: 'EARN',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        format: LearnWatchKind.FILM,
        youtubeId: 'RK8xHq6dfAo',
        url: 'https://www.youtube.com/watch?v=RK8xHq6dfAo',
        watchUrl: 'https://www.justwatch.com/nl/movie/hidden-figures',
    },
    {
        key: 'ford-v-ferrari',
        name: 'Ford v Ferrari',
        creator: 'James Mangold',
        description: 'A budget, a deadline, and a craft that will not be rushed for the sponsor.',
        topic: 'EARN',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        format: LearnWatchKind.FILM,
        youtubeId: 'I3h9Z89U9ZA',
        url: 'https://www.youtube.com/watch?v=I3h9Z89U9ZA',
        watchUrl: 'https://www.justwatch.com/nl/movie/ford-v-ferrari',
    },
    {
        key: 'margin-call',
        name: 'Margin Call',
        creator: 'J. C. Chandor',
        description: 'One night when the risk has a number and nobody wants to say it out loud.',
        topic: 'SPEND',
        minPlan: PlanKey.PLUS,
        spendingStyles: [SpendingStyle.SPENDER, SpendingStyle.BALANCED],
        format: LearnWatchKind.FILM,
        youtubeId: 'IjZ-ke1kJrA',
        url: 'https://www.youtube.com/watch?v=IjZ-ke1kJrA',
        watchUrl: 'https://www.justwatch.com/nl/movie/margin-call',
    },
    {
        key: 'inside-job',
        name: 'Inside Job',
        creator: 'Charles Ferguson',
        description: 'Who got paid when the system broke. A warning, not a how-to.',
        topic: 'SPEND',
        minPlan: PlanKey.PLUS,
        spendingStyles: [SpendingStyle.SPENDER],
        format: LearnWatchKind.FILM,
        youtubeId: 'FzrBurlJUNk',
        url: 'https://www.youtube.com/watch?v=FzrBurlJUNk',
        watchUrl: 'https://www.justwatch.com/nl/movie/inside-job',
    },
    {
        key: 'the-farewell',
        name: 'The Farewell',
        creator: 'Lulu Wang',
        description: 'What a family says, and what it refuses to say, when the news is bad.',
        topic: 'RELATIONSHIPS',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        format: LearnWatchKind.FILM,
        youtubeId: 'RofpAjqwMa8',
        url: 'https://www.youtube.com/watch?v=RofpAjqwMa8',
        watchUrl: 'https://www.justwatch.com/nl/movie/the-farewell',
    },
    {
        key: 'free-solo',
        name: 'Free Solo',
        creator: 'Elizabeth Chai Vasarhelyi, Jimmy Chin',
        description: 'Preparation is the whole sport. The climb is the part people film.',
        topic: 'HEALTH',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        format: LearnWatchKind.FILM,
        youtubeId: 'urRVZ4SW7WU',
        url: 'https://www.youtube.com/watch?v=urRVZ4SW7WU',
        watchUrl: 'https://www.justwatch.com/nl/movie/free-solo',
    },
    {
        key: 'steve-jobs',
        name: 'Steve Jobs',
        creator: 'Danny Boyle',
        description: 'A product launch is a conversation. This one shows the cost of winning it.',
        topic: 'EARN',
        minPlan: PlanKey.MAX,
        spendingStyles: [],
        format: LearnWatchKind.FILM,
        youtubeId: 'aEr6K1bwIVs',
        url: 'https://www.youtube.com/watch?v=aEr6K1bwIVs',
        watchUrl: 'https://www.justwatch.com/nl/movie/steve-jobs',
    },
    {
        key: 'succession',
        name: 'Succession',
        creator: 'Jesse Armstrong',
        description:
            'Who holds the company when the founder will not let go. A warning about power, not a model.',
        skill: 'LEADERSHIP',
        topic: 'EARN',
        minPlan: PlanKey.MAX,
        spendingStyles: [],
        format: LearnWatchKind.SERIES,
        youtubeId: 'OzYxJV_rmE8',
        url: 'https://www.youtube.com/watch?v=OzYxJV_rmE8',
        watchUrl: 'https://www.justwatch.com/nl/tv-series/succession',
    },
    {
        key: 'silicon-valley',
        name: 'Silicon Valley',
        creator: 'Mike Judge',
        description:
            'A small team, a loud market, and the bills that arrive before the product does.',
        topic: 'EARN',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        format: LearnWatchKind.SERIES,
        youtubeId: '69V__a49xtw',
        url: 'https://www.youtube.com/watch?v=69V__a49xtw',
        watchUrl: 'https://www.justwatch.com/nl/tv-series/silicon-valley',
    },
    {
        key: 'ted-lasso',
        name: 'Ted Lasso',
        creator: 'Bill Lawrence',
        description:
            'A room gets better when the person in charge stops performing and starts listening.',
        skill: 'LEADERSHIP',
        topic: 'EARN',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        format: LearnWatchKind.SERIES,
        youtubeId: '3u7EIiohs6U',
        url: 'https://www.youtube.com/watch?v=3u7EIiohs6U',
        watchUrl: 'https://www.justwatch.com/nl/tv-series/ted-lasso',
    },
    {
        key: 'the-bear',
        name: 'The Bear',
        creator: 'Christopher Storer',
        description:
            'A kitchen with a clock on the money. Craft, cost, and the people who keep the doors open.',
        topic: 'EARN',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        format: LearnWatchKind.SERIES,
        youtubeId: 'vOyRo-Yjr2Q',
        url: 'https://www.youtube.com/watch?v=vOyRo-Yjr2Q',
        watchUrl: 'https://www.justwatch.com/nl/tv-series/the-bear',
    },
    {
        key: 'mad-men',
        name: 'Mad Men',
        creator: 'Matthew Weiner',
        description: 'How a message is made, and what it costs the people who make it.',
        topic: 'EARN',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        format: LearnWatchKind.SERIES,
        youtubeId: 'aLvQyu9oguE',
        url: 'https://www.youtube.com/watch?v=aLvQyu9oguE',
        watchUrl: 'https://www.justwatch.com/nl/tv-series/mad-men',
    },
    {
        key: 'halt-and-catch-fire',
        name: 'Halt and Catch Fire',
        creator: 'Christopher Cantwell',
        description:
            'Building the next machine before the market has a name for it. Ambition with a payroll.',
        topic: 'EARN',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        format: LearnWatchKind.SERIES,
        youtubeId: '4NqNvBV8TCs',
        url: 'https://www.youtube.com/watch?v=4NqNvBV8TCs',
        watchUrl: 'https://www.justwatch.com/nl/tv-series/halt-and-catch-fire',
    },
    {
        key: 'money-explained',
        name: 'Money, Explained',
        creator: 'Vox',
        description: 'Debt, cards, and the tricks that make spending feel smaller than it is.',
        topic: 'SAVE',
        minPlan: PlanKey.BASIC,
        spendingStyles: [SpendingStyle.SAVER, SpendingStyle.SPENDER],
        format: LearnWatchKind.SERIES,
        youtubeId: 'lJHu-KCY9Fc',
        url: 'https://www.youtube.com/watch?v=lJHu-KCY9Fc',
        watchUrl: 'https://www.justwatch.com/nl/tv-series/money-explained',
    },
    {
        key: 'brene-vulnerability',
        name: 'The Power of Vulnerability',
        creator: 'Brené Brown',
        description: 'The talk on what happens when you stop performing and say the true thing.',
        topic: 'RELATIONSHIPS',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        format: LearnWatchKind.VIDEO,
        youtubeId: 'iCvmsMzlF7o',
        url: 'https://www.youtube.com/watch?v=iCvmsMzlF7o',
        watchUrl: null,
    },
    {
        key: 'sinek-why',
        name: 'How Great Leaders Inspire Action',
        creator: 'Simon Sinek',
        description:
            'Start with why. A short talk on the sentence people can repeat after you leave the room.',
        skill: 'LEADERSHIP',
        topic: 'EARN',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        format: LearnWatchKind.VIDEO,
        youtubeId: 'qp0HIF3SfI4',
        url: 'https://www.youtube.com/watch?v=qp0HIF3SfI4',
        watchUrl: null,
    },
    {
        key: 'duckworth-grit',
        name: 'Grit',
        creator: 'Angela Duckworth',
        description:
            'Passion and perseverance, said plainly. The long game is a practice, not a mood.',
        topic: 'MIND',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        format: LearnWatchKind.VIDEO,
        youtubeId: 'H14bBuluwB8',
        url: 'https://www.youtube.com/watch?v=H14bBuluwB8',
        watchUrl: null,
    },
    {
        key: 'achor-better-work',
        name: 'The Happy Secret to Better Work',
        creator: 'Shawn Achor',
        description: 'The advantage is not the next win. It is the state you work from.',
        topic: 'MIND',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        format: LearnWatchKind.VIDEO,
        youtubeId: 'fLJsdqxnZb0',
        url: 'https://www.youtube.com/watch?v=fLJsdqxnZb0',
        watchUrl: null,
    },
    {
        key: 'mcgonigal-stress',
        name: 'How to Make Stress Your Friend',
        creator: 'Kelly McGonigal',
        description: 'Stress is a signal, not a verdict. A short talk before the week gets loud.',
        topic: 'HEALTH',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        format: LearnWatchKind.VIDEO,
        youtubeId: 'RcGyVTAoXEU',
        url: 'https://www.youtube.com/watch?v=RcGyVTAoXEU',
        watchUrl: null,
    },
    {
        key: 'walker-sleep',
        name: 'Sleep Is Your Superpower',
        creator: 'Matthew Walker',
        description: 'The same case as the book, in one sitting. The night is part of the work.',
        topic: 'HEALTH',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        format: LearnWatchKind.VIDEO,
        youtubeId: '5MuIMqhT8DM',
        url: 'https://www.youtube.com/watch?v=5MuIMqhT8DM',
        watchUrl: null,
    },
    {
        key: 'ariely-decisions',
        name: 'Are We in Control of Our Decisions?',
        creator: 'Dan Ariely',
        description: 'Why the sensible choice loses to the one that was placed in front of you.',
        topic: 'SPEND',
        minPlan: PlanKey.PLUS,
        spendingStyles: [SpendingStyle.SPENDER, SpendingStyle.BALANCED],
        format: LearnWatchKind.VIDEO,
        youtubeId: '9X68dm92HVI',
        url: 'https://www.youtube.com/watch?v=9X68dm92HVI',
        watchUrl: null,
    },
    {
        key: 'cain-introverts',
        name: 'The Power of Introverts',
        creator: 'Susan Cain',
        description:
            'The quiet person in the room is not behind. A talk on how the work actually gets made.',
        topic: 'MIND',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        format: LearnWatchKind.VIDEO,
        youtubeId: 'c0KYU2j0TM4',
        url: 'https://www.youtube.com/watch?v=c0KYU2j0TM4',
        watchUrl: null,
    },
    {
        key: 'perel-desire',
        name: 'The Secret to Desire in a Long-term Relationship',
        creator: 'Esther Perel',
        description:
            'Closeness and wanting are not the same job. A talk for the relationship, not the calendar.',
        topic: 'RELATIONSHIPS',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        format: LearnWatchKind.VIDEO,
        youtubeId: 'sa0RUmGTCYY',
        url: 'https://www.youtube.com/watch?v=sa0RUmGTCYY',
        watchUrl: null,
    },
    {
        key: 'clear-atomic',
        name: 'Atomic Habits, told',
        creator: 'James Clear',
        description: 'One percent, said by the person who wrote the book. Not a summary channel.',
        topic: 'MIND',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        format: LearnWatchKind.VIDEO,
        youtubeId: 'U_nzqnXWvSo',
        url: 'https://www.youtube.com/watch?v=U_nzqnXWvSo',
        watchUrl: null,
    },
    {
        key: 'voss-negotiate',
        name: 'Never Split the Difference, told',
        creator: 'Chris Voss',
        description: 'Tactical empathy from the person who wrote it. A talk, not a clip account.',
        topic: 'EARN',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        format: LearnWatchKind.VIDEO,
        youtubeId: 'guZa7mQV1l0',
        url: 'https://www.youtube.com/watch?v=guZa7mQV1l0',
        watchUrl: null,
    },
    {
        key: 'godin-ideas',
        name: 'How to Get Your Ideas to Spread',
        creator: 'Seth Godin',
        description: 'Remarkable is a choice about who the work is for, not a louder ad.',
        topic: 'EARN',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        format: LearnWatchKind.VIDEO,
        youtubeId: 'xBIVlM435Zg',
        url: 'https://www.youtube.com/watch?v=xBIVlM435Zg',
        watchUrl: null,
    },
];
