import { PlanKey, SpendingStyle } from '@rumtelo/contracts';

import { series, type WatchSeedRow } from './watch-row';

/**
 * Series we recommend — trailer on YouTube, stream via JustWatch.
 */
export const WATCH_SERIES_SEED: readonly WatchSeedRow[] = [
    series({
        key: 'how-to-get-rich',
        name: 'How to Get Rich',
        creator: 'Ramit Sethi',
        description:
            'Spend on what you named. Cut what you did not. A series about that split, not a lecture.',
        topic: 'SPEND',
        minPlan: PlanKey.PLUS,
        spendingStyles: [SpendingStyle.SPENDER, SpendingStyle.BALANCED],
        youtubeId: 'QlyDIP9jEck',
        url: 'https://www.youtube.com/watch?v=QlyDIP9jEck',
        watchUrl: 'https://www.justwatch.com/nl/tv-series/how-to-get-rich',
    }),
    series({
        key: 'the-fixer',
        name: 'The Fixer',
        creator: 'Marcus Lemonis',
        description:
            'A business is a set of leaks. This is someone walking the floor and naming them.',
        topic: 'SPEND',
        minPlan: PlanKey.MAX,
        spendingStyles: [SpendingStyle.SPENDER],
        youtubeId: 'janFurHb8t0',
        url: 'https://www.youtube.com/watch?v=janFurHb8t0',
        watchUrl: null,
    }),
    series({
        key: 'succession',
        name: 'Succession',
        creator: 'Jesse Armstrong',
        description:
            'Who holds the company when the founder will not let go. A warning about power, not a model.',
        skill: 'LEADERSHIP',
        topic: 'EARN',
        minPlan: PlanKey.MAX,
        spendingStyles: [],
        youtubeId: 'OzYxJV_rmE8',
        url: 'https://www.youtube.com/watch?v=OzYxJV_rmE8',
        watchUrl: 'https://www.justwatch.com/nl/tv-series/succession',
    }),
    series({
        key: 'silicon-valley',
        name: 'Silicon Valley',
        creator: 'Mike Judge',
        description:
            'A small team, a loud market, and the bills that arrive before the product does.',
        topic: 'EARN',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        youtubeId: '69V__a49xtw',
        url: 'https://www.youtube.com/watch?v=69V__a49xtw',
        watchUrl: 'https://www.justwatch.com/nl/tv-series/silicon-valley',
    }),
    series({
        key: 'ted-lasso',
        name: 'Ted Lasso',
        creator: 'Bill Lawrence',
        description:
            'A room gets better when the person in charge stops performing and starts listening.',
        skill: 'LEADERSHIP',
        topic: 'EARN',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        youtubeId: '3u7EIiohs6U',
        url: 'https://www.youtube.com/watch?v=3u7EIiohs6U',
        watchUrl: 'https://www.justwatch.com/nl/tv-series/ted-lasso',
    }),
    series({
        key: 'the-bear',
        name: 'The Bear',
        creator: 'Christopher Storer',
        description:
            'A kitchen with a clock on the money. Craft, cost, and the people who keep the doors open.',
        topic: 'EARN',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        youtubeId: 'vOyRo-Yjr2Q',
        url: 'https://www.youtube.com/watch?v=vOyRo-Yjr2Q',
        watchUrl: 'https://www.justwatch.com/nl/tv-series/the-bear',
    }),
    series({
        key: 'mad-men',
        name: 'Mad Men',
        creator: 'Matthew Weiner',
        description: 'How a message is made, and what it costs the people who make it.',
        topic: 'EARN',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        youtubeId: 'aLvQyu9oguE',
        url: 'https://www.youtube.com/watch?v=aLvQyu9oguE',
        watchUrl: 'https://www.justwatch.com/nl/tv-series/mad-men',
    }),
    series({
        key: 'halt-and-catch-fire',
        name: 'Halt and Catch Fire',
        creator: 'Christopher Cantwell',
        description:
            'Building the next machine before the market has a name for it. Ambition with a payroll.',
        topic: 'EARN',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        youtubeId: '4NqNvBV8TCs',
        url: 'https://www.youtube.com/watch?v=4NqNvBV8TCs',
        watchUrl: 'https://www.justwatch.com/nl/tv-series/halt-and-catch-fire',
    }),
    series({
        key: 'money-explained',
        name: 'Money, Explained',
        creator: 'Vox',
        description: 'Debt, cards, and the tricks that make spending feel smaller than it is.',
        topic: 'SAVE',
        minPlan: PlanKey.BASIC,
        spendingStyles: [SpendingStyle.SAVER, SpendingStyle.SPENDER],
        youtubeId: 'lJHu-KCY9Fc',
        url: 'https://www.youtube.com/watch?v=lJHu-KCY9Fc',
        watchUrl: 'https://www.justwatch.com/nl/tv-series/money-explained',
    }),
    series({
        key: 'shark-tank',
        name: 'Shark Tank',
        creator: 'Mark Burnett',
        description:
            'A pitch, a price, and a room that will say no. Watch how ownership gets traded — and why.',
        topic: 'EARN',
        minPlan: PlanKey.BASIC,
        spendingStyles: [],
        youtubeId: 'LiQJF9-IULI',
        url: 'https://www.youtube.com/watch?v=LiQJF9-IULI',
        watchUrl: 'https://www.justwatch.com/nl/tv-series/shark-tank',
    }),
    series({
        key: 'wecrashed',
        name: 'WeCrashed',
        creator: 'Lee Eisenberg',
        description:
            'A story sold faster than the company could hold. Charisma, cash, and the bill that arrived.',
        topic: 'EARN',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        youtubeId: 'UREIAoL0Spk',
        url: 'https://www.youtube.com/watch?v=UREIAoL0Spk',
        watchUrl: 'https://www.justwatch.com/nl/tv-series/wecrashed',
    }),
    series({
        key: 'the-dropout',
        name: 'The Dropout',
        creator: 'Elizabeth Meriwether',
        description:
            'A company built on a story that outran the product. Belief is not a balance sheet.',
        topic: 'EARN',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        youtubeId: 'W7rlZLw9m10',
        url: 'https://www.youtube.com/watch?v=W7rlZLw9m10',
        watchUrl: 'https://www.justwatch.com/nl/tv-series/the-dropout',
    }),
    series({
        key: 'billions',
        name: 'Billions',
        creator: 'Brian Koppelman',
        description:
            'Money as a weapon and a scoreboard. A warning about power, not a how-to for the desk.',
        topic: 'EARN',
        minPlan: PlanKey.MAX,
        spendingStyles: [],
        youtubeId: 'E_EF_IfnPgk',
        url: 'https://www.youtube.com/watch?v=E_EF_IfnPgk',
        watchUrl: 'https://www.justwatch.com/nl/tv-series/billions',
    }),
    series({
        key: 'industry',
        name: 'Industry',
        creator: 'Mickey Down & Konrad Kay',
        description:
            'Graduates on a trading floor. The hours, the politics, and what the bonus actually costs.',
        topic: 'EARN',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        youtubeId: 'QoWOCGZxN0c',
        url: 'https://www.youtube.com/watch?v=QoWOCGZxN0c',
        watchUrl: 'https://www.justwatch.com/nl/tv-series/industry',
    }),
    series({
        key: 'severance',
        name: 'Severance',
        creator: 'Dan Erickson',
        description:
            'Work that never leaves the building — and a mind that pays the rent for both halves.',
        topic: 'MIND',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        youtubeId: 'xEQP4VVuyrY',
        url: 'https://www.youtube.com/watch?v=xEQP4VVuyrY',
        watchUrl: 'https://www.justwatch.com/nl/tv-series/severance',
    }),
    series({
        key: 'chefs-table',
        name: "Chef's Table",
        creator: 'David Gelb',
        description:
            'Craft before the plate. Cost, obsession, and the people who keep a kitchen alive.',
        topic: 'EARN',
        minPlan: PlanKey.PLUS,
        spendingStyles: [],
        youtubeId: 'qKqj85oo2wI',
        url: 'https://www.youtube.com/watch?v=qKqj85oo2wI',
        watchUrl: 'https://www.justwatch.com/nl/tv-series/chefs-table',
    }),
];
