import type { MerchantSeed } from '../types';
import { play } from '../types';

/** Alcohol — slijterij (not groceries). */
export const ALCOHOL_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'GALL_AND_GALL',
        name: 'Gall & Gall',
        matchValue: 'Gall & Gall',
        aliases: ['Gall & Gall', 'Gall and Gall', 'GALL & GALL', 'Gall&Gall'],
        mcc: '5921',
        jarKey: play,
        categoryTemplateKey: 'ALCOHOL',
        logoDomain: 'gall.nl',
        website: 'https://gall.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'MITRA',
        name: 'Mitra',
        matchValue: 'Mitra',
        aliases: ['Mitra', 'MITRA', 'Mitra Slijterij'],
        mcc: '5921',
        jarKey: play,
        categoryTemplateKey: 'ALCOHOL',
        logoDomain: 'mitra.nl',
        website: 'https://mitra.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'DRANKDOZIJN',
        name: 'Drankdozijn',
        matchValue: 'Drankdozijn',
        aliases: ['Drankdozijn', 'DRANKDOZIJN', 'Drank Dozijn'],
        mcc: '5921',
        jarKey: play,
        categoryTemplateKey: 'ALCOHOL',
        logoDomain: 'drankdozijn.nl',
        website: 'https://drankdozijn.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'WHISKYBASE',
        name: 'Whiskybase',
        matchValue: 'Whiskybase',
        aliases: ['Whiskybase', 'WHISKYBASE', 'Whisky Base'],
        mcc: '5921',
        jarKey: play,
        categoryTemplateKey: 'ALCOHOL',
        logoDomain: 'whiskybase.com',
        website: 'https://whiskybase.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];
