import type { MerchantSeed } from '../types';
import { necessities } from '../types';

/** banking merchant presets */
export const BANKING_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'ING',
        name: 'ING',
        matchValue: 'ING',
        aliases: ['ING Bank', 'ING BANK NV', 'ING '],
        mcc: '6012',
        jarKey: necessities,
        categoryTemplateKey: 'BANKING',
        logoDomain: 'ing.nl',
        website: 'https://ing.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ABN_AMRO',
        name: 'ABN AMRO',
        matchValue: 'ABN AMRO',
        aliases: ['ABN AMRO', 'ABNAMRO', 'ABN-AMRO'],
        mcc: '6012',
        jarKey: necessities,
        categoryTemplateKey: 'BANKING',
        logoDomain: 'abnamro.nl',
        website: 'https://abnamro.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'RABOBANK',
        name: 'Rabobank',
        matchValue: 'Rabobank',
        aliases: ['Rabobank', 'RABOBANK', 'Coöperatieve Rabobank'],
        mcc: '6012',
        jarKey: necessities,
        categoryTemplateKey: 'BANKING',
        logoDomain: 'rabobank.nl',
        website: 'https://rabobank.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BUNQ',
        name: 'bunq',
        matchValue: 'bunq',
        aliases: ['bunq', 'BUNQ BV', 'bunq B.V.'],
        mcc: '6012',
        jarKey: necessities,
        categoryTemplateKey: 'BANKING',
        logoDomain: 'bunq.com',
        website: 'https://bunq.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'REVOLUT',
        name: 'Revolut',
        matchValue: 'Revolut',
        aliases: ['Revolut', 'REVOLUT'],
        mcc: '6012',
        jarKey: necessities,
        categoryTemplateKey: 'BANKING',
        logoDomain: 'revolut.com',
        website: 'https://revolut.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'N26',
        name: 'N26',
        matchValue: 'N26',
        aliases: ['N26', 'N26 Bank'],
        mcc: '6012',
        jarKey: necessities,
        categoryTemplateKey: 'BANKING',
        logoDomain: 'n26.com',
        website: 'https://n26.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'TRIODOS',
        name: 'Triodos',
        matchValue: 'Triodos',
        aliases: ['Triodos', 'TRIODOS', 'Triodos Bank'],
        mcc: '6012',
        jarKey: necessities,
        categoryTemplateKey: 'BANKING',
        logoDomain: 'triodos.nl',
        website: 'https://triodos.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ASN_BANK',
        name: 'ASN Bank',
        matchValue: 'ASN Bank',
        aliases: ['ASN Bank', 'ASN BANK', 'ASN'],
        mcc: '6012',
        jarKey: necessities,
        categoryTemplateKey: 'BANKING',
        logoDomain: 'asnbank.nl',
        website: 'https://asnbank.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'SNS',
        name: 'SNS',
        matchValue: 'SNS',
        aliases: ['SNS Bank', 'SNS ', 'SNS Bank NV'],
        mcc: '6012',
        jarKey: necessities,
        categoryTemplateKey: 'BANKING',
        logoDomain: 'snsbank.nl',
        website: 'https://snsbank.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'REGIOBANK',
        name: 'RegioBank',
        matchValue: 'RegioBank',
        aliases: ['RegioBank', 'REGIOBANK'],
        mcc: '6012',
        jarKey: necessities,
        categoryTemplateKey: 'BANKING',
        logoDomain: 'regiobank.nl',
        website: 'https://regiobank.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'KNAB',
        name: 'Knab',
        matchValue: 'Knab',
        aliases: ['Knab', 'KNAB'],
        mcc: '6012',
        jarKey: necessities,
        categoryTemplateKey: 'BANKING',
        logoDomain: 'knab.nl',
        website: 'https://knab.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'OPENBANK',
        name: 'Openbank',
        matchValue: 'Openbank',
        aliases: ['Openbank', 'OPENBANK'],
        mcc: '6012',
        jarKey: necessities,
        categoryTemplateKey: 'BANKING',
        logoDomain: 'openbank.nl',
        website: 'https://openbank.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'WISE',
        name: 'Wise',
        matchValue: 'Wise',
        aliases: ['Wise', 'WISE*', 'TransferWise'],
        mcc: '6012',
        jarKey: necessities,
        categoryTemplateKey: 'BANKING',
        logoDomain: 'wise.com',
        website: 'https://wise.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'PAYPAL',
        name: 'PayPal',
        matchValue: 'PayPal',
        aliases: ['PayPal', 'PAYPAL*', 'PayPal Europe'],
        mcc: '6012',
        jarKey: necessities,
        categoryTemplateKey: 'BANKING',
        logoDomain: 'paypal.com',
        website: 'https://paypal.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'IDEAL',
        name: 'iDEAL',
        matchValue: 'iDEAL',
        aliases: ['iDEAL', 'IDEAL', 'Currence iDEAL'],
        mcc: '6012',
        jarKey: necessities,
        categoryTemplateKey: 'BANKING',
        logoDomain: 'ideal.nl',
        website: 'https://ideal.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'KLARNA',
        name: 'Klarna',
        matchValue: 'Klarna',
        aliases: ['Klarna', 'KLARNA*', 'Klarna Bank'],
        mcc: '5999',
        jarKey: necessities,
        categoryTemplateKey: 'BANKING',
        logoDomain: 'klarna.com',
        website: 'https://klarna.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'AFTERPAY',
        name: 'Afterpay / Riverty',
        matchValue: 'Afterpay',
        aliases: ['Afterpay', 'Riverty', 'AFTERPAY', 'RIVERTY'],
        mcc: '5999',
        jarKey: necessities,
        categoryTemplateKey: 'BANKING',
        logoDomain: 'riverty.com',
        website: 'https://riverty.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];
