import type { MerchantSeed } from '../types';
import { play } from '../types';

/**
 * Cosmetics retail (BEAUTY) + optional chain chips for HAIR / NAILS.
 * Most households free-type their local salon — categories are the primary pick.
 */
export const BEAUTY_MERCHANTS: readonly MerchantSeed[] = [
    // ── Cosmetics retail → BEAUTY ─────────────────────────────────────
    {
        key: 'ICI_PARIS_XL',
        name: 'ICI Paris XL',
        matchValue: 'ICI Paris XL',
        aliases: ['ICI Paris XL', 'ICI PARIS', 'Iciparisxl'],
        mcc: '5977',
        jarKey: play,
        categoryTemplateKey: 'BEAUTY',
        logoDomain: 'iciparisxl.nl',
        website: 'https://iciparisxl.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'DOUGLAS',
        name: 'Douglas',
        matchValue: 'Douglas',
        aliases: ['Douglas', 'DOUGLAS'],
        mcc: '5977',
        jarKey: play,
        categoryTemplateKey: 'BEAUTY',
        logoDomain: 'douglas.nl',
        website: 'https://douglas.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'THE_BODY_SHOP',
        name: 'The Body Shop',
        matchValue: 'The Body Shop',
        aliases: ['The Body Shop', 'Body Shop', 'THE BODY SHOP'],
        mcc: '5977',
        jarKey: play,
        categoryTemplateKey: 'BEAUTY',
        logoDomain: 'thebodyshop.com',
        website: 'https://thebodyshop.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BEAUTY_BY_ROOS',
        name: 'Beauty by Roos',
        matchValue: 'Beauty by Roos',
        aliases: ['Beauty by Roos', 'BeautybyRoos', 'BEAUTY BY ROOS'],
        mcc: '7230',
        jarKey: play,
        categoryTemplateKey: 'BEAUTY',
        logoDomain: 'beautybyroos.nl',
        website: 'https://beautybyroos.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'PERFECT_BROW_BAR',
        name: 'Perfect Brow Bar',
        matchValue: 'Perfect Brow Bar',
        aliases: ['Perfect Brow Bar', 'Perfect Brow', 'PERFECT BROW BAR'],
        mcc: '7230',
        jarKey: play,
        categoryTemplateKey: 'BEAUTY',
        logoDomain: 'perfectbrowbar.nl',
        website: 'https://perfectbrowbar.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'LASERCLINICS',
        name: 'LaserClinics',
        matchValue: 'LaserClinics',
        aliases: ['LaserClinics', 'Laser Clinics', 'LASERCLINICS', 'Laser Clinic'],
        mcc: '7298',
        jarKey: play,
        categoryTemplateKey: 'BEAUTY',
        logoDomain: 'laserclinics.nl',
        website: 'https://laserclinics.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'CONTOUR_CLINIC',
        name: 'Contour Clinic',
        matchValue: 'Contour Clinic',
        aliases: ['Contour Clinic', 'ContourClinic', 'CONTOUR CLINIC'],
        mcc: '7298',
        jarKey: play,
        categoryTemplateKey: 'BEAUTY',
        logoDomain: 'contourclinic.nl',
        website: 'https://contourclinic.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },

    // ── Hair → HAIR (optional chips; local shops are free-typed) ───────
    {
        key: 'HIZI_HAIR',
        name: 'Hizi Hair',
        matchValue: 'Hizi Hair',
        aliases: ['Hizi Hair', 'Hizi', 'HIZI HAIR', 'HiziHair'],
        mcc: '7230',
        jarKey: play,
        categoryTemplateKey: 'HAIR',
        logoDomain: 'hizihair.nl',
        website: 'https://hizihair.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ROB_PEETOOM',
        name: 'Rob Peetoom',
        matchValue: 'Rob Peetoom',
        aliases: ['Rob Peetoom', 'ROB PEETOOM', 'Peetoom'],
        mcc: '7230',
        jarKey: play,
        categoryTemplateKey: 'HAIR',
        logoDomain: 'robpeetoom.com',
        website: 'https://robpeetoom.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'KINKI_KAPPERS',
        name: 'Kinki Kappers',
        matchValue: 'Kinki Kappers',
        aliases: ['Kinki Kappers', 'Kinki', 'KINKI KAPPERS'],
        mcc: '7230',
        jarKey: play,
        categoryTemplateKey: 'HAIR',
        logoDomain: 'kinkikappers.nl',
        website: 'https://kinkikappers.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'AMI_KAPPERS',
        name: 'AMI Kappers',
        matchValue: 'AMI Kappers',
        aliases: ['AMI Kappers', 'AMI', 'Ami Kappers', 'AMI KAPPERS'],
        mcc: '7230',
        jarKey: play,
        categoryTemplateKey: 'HAIR',
        logoDomain: 'amikappers.nl',
        website: 'https://amikappers.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'TONI_AND_GUY',
        name: 'TONI&GUY',
        matchValue: 'TONI&GUY',
        aliases: ['TONI&GUY', 'Toni and Guy', 'Toni & Guy', 'TONI AND GUY'],
        mcc: '7230',
        jarKey: play,
        categoryTemplateKey: 'HAIR',
        logoDomain: 'toniandguy.com',
        website: 'https://toniandguy.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BRAINWASH_KAPPERS',
        name: 'Brainwash',
        matchValue: 'Brainwash',
        aliases: ['Brainwash', 'Brainwash Kappers', 'BRAINWASH'],
        mcc: '7230',
        jarKey: play,
        categoryTemplateKey: 'HAIR',
        logoDomain: 'brainwash.nl',
        website: 'https://brainwash.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'SJENKELS',
        name: 'Sjenkels',
        matchValue: 'Sjenkels',
        aliases: ['Sjenkels', 'SJENKELS', 'Sjenkels Kappers'],
        mcc: '7230',
        jarKey: play,
        categoryTemplateKey: 'HAIR',
        logoDomain: 'sjenkels.nl',
        website: 'https://sjenkels.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'HAIRAPP',
        name: 'HairApp',
        matchValue: 'HairApp',
        aliases: ['HairApp', 'Hair App', 'HAIRAPP'],
        mcc: '7230',
        jarKey: play,
        categoryTemplateKey: 'HAIR',
        logoDomain: 'hairapp.nl',
        website: 'https://hairapp.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'CUT_THROAT_CLUB',
        name: 'Cut Throat Club',
        matchValue: 'Cut Throat Club',
        aliases: ['Cut Throat Club', 'CutThroat', 'CUT THROAT CLUB'],
        mcc: '7230',
        jarKey: play,
        categoryTemplateKey: 'HAIR',
        logoDomain: 'cutthroatclub.nl',
        website: 'https://cutthroatclub.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },

    // ── Nails → NAILS ─────────────────────────────────────────────────
    {
        key: 'NAIL_ART_CARE',
        name: 'Nail Art Care',
        matchValue: 'Nail Art Care',
        aliases: ['Nail Art Care', 'NailArtCare', 'NAIL ART CARE'],
        mcc: '7230',
        jarKey: play,
        categoryTemplateKey: 'NAILS',
        logoDomain: 'nailartcare.nl',
        website: 'https://nailartcare.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'HAPPY_NAILS',
        name: 'Happy Nails',
        matchValue: 'Happy Nails',
        aliases: ['Happy Nails', 'HappyNails', 'HAPPY NAILS'],
        mcc: '7230',
        jarKey: play,
        categoryTemplateKey: 'NAILS',
        logoDomain: 'happynails.nl',
        website: 'https://happynails.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'NAIL_PALACE',
        name: 'Nail Palace',
        matchValue: 'Nail Palace',
        aliases: ['Nail Palace', 'NailPalace', 'NAIL PALACE'],
        mcc: '7230',
        jarKey: play,
        categoryTemplateKey: 'NAILS',
        logoDomain: 'nailpalace.nl',
        website: 'https://nailpalace.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'GLOSSY_NAILS',
        name: 'Glossy Nails',
        matchValue: 'Glossy Nails',
        aliases: ['Glossy Nails', 'GlossyNails', 'GLOSSY NAILS'],
        mcc: '7230',
        jarKey: play,
        categoryTemplateKey: 'NAILS',
        logoDomain: 'glossynails.nl',
        website: 'https://glossynails.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'NAILSTORY',
        name: 'Nailstory',
        matchValue: 'Nailstory',
        aliases: ['Nailstory', 'Nail Story', 'NAILSTORY'],
        mcc: '7230',
        jarKey: play,
        categoryTemplateKey: 'NAILS',
        logoDomain: 'nailstory.nl',
        website: 'https://nailstory.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'THE_NAIL_LOUNGE',
        name: 'The Nail Lounge',
        matchValue: 'The Nail Lounge',
        aliases: ['The Nail Lounge', 'Nail Lounge', 'NAIL LOUNGE'],
        mcc: '7230',
        jarKey: play,
        categoryTemplateKey: 'NAILS',
        logoDomain: 'thenailounge.nl',
        website: 'https://thenailounge.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];
