import type { MerchantSeed } from '../types';
import { necessities } from '../types';

/** care merchant presets */
export const CARE_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'ETOS',
        name: 'Etos',
        matchValue: 'Etos',
        aliases: ['Etos', 'ETOS BV'],
        mcc: '5912',
        jarKey: necessities,
        categoryTemplateKey: 'CARE',
        logoDomain: 'etos.nl',
        website: 'https://etos.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'KRUIDVAT',
        name: 'Kruidvat',
        matchValue: 'Kruidvat',
        aliases: ['Kruidvat', 'KRUIDVAT'],
        mcc: '5912',
        jarKey: necessities,
        categoryTemplateKey: 'CARE',
        logoDomain: 'kruidvat.nl',
        website: 'https://kruidvat.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'DA',
        name: 'DA',
        matchValue: 'DA ',
        aliases: ['DA Drogisterij', 'DA ', 'D.A. '],
        mcc: '5912',
        jarKey: necessities,
        categoryTemplateKey: 'CARE',
        logoDomain: 'da.nl',
        website: 'https://da.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'HOLLAND_AND_BARRETT',
        name: 'Holland & Barrett',
        matchValue: 'Holland & Barrett',
        aliases: ['Holland & Barrett', 'Holland and Barrett', 'H&B '],
        mcc: '5499',
        jarKey: necessities,
        categoryTemplateKey: 'CARE',
        logoDomain: 'hollandandbarrett.nl',
        website: 'https://hollandandbarrett.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'TREKPLEISTER',
        name: 'Trekpleister',
        matchValue: 'Trekpleister',
        aliases: ['Trekpleister', 'TREKPLEISTER'],
        mcc: '5912',
        jarKey: necessities,
        categoryTemplateKey: 'CARE',
        logoDomain: 'trekpleister.nl',
        website: 'https://trekpleister.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'DI_DROGIST',
        name: 'Di',
        matchValue: 'Di Drogist',
        aliases: ['Di Drogist', 'Di ', 'DI DROGIST'],
        mcc: '5912',
        jarKey: necessities,
        categoryTemplateKey: 'CARE',
        logoDomain: 'di.nl',
        website: 'https://di.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BOOTS',
        name: 'Boots',
        matchValue: 'Boots',
        aliases: ['Boots', 'BOOTS'],
        mcc: '5912',
        jarKey: necessities,
        categoryTemplateKey: 'CARE',
        logoDomain: 'boots.com',
        website: 'https://boots.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'APOTHEEK',
        name: 'Apotheek',
        matchValue: 'Apotheek',
        aliases: ['Apotheek', 'APOTHEEK', 'Service Apotheek'],
        mcc: '5912',
        jarKey: necessities,
        categoryTemplateKey: 'CARE',
        logoDomain: 'apotheek.nl',
        website: 'https://apotheek.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'MEDIQ',
        name: 'Mediq',
        matchValue: 'Mediq',
        aliases: ['Mediq', 'MEDIQ'],
        mcc: '5912',
        jarKey: necessities,
        categoryTemplateKey: 'CARE',
        logoDomain: 'mediq.com',
        website: 'https://mediq.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BODY_AND_FIT',
        name: 'Body & Fit',
        matchValue: 'Body & Fit',
        aliases: ['Body & Fit', 'Body and Fit', 'BODYFIT'],
        mcc: '5499',
        jarKey: necessities,
        categoryTemplateKey: 'CARE',
        logoDomain: 'bodyandfit.com',
        website: 'https://bodyandfit.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];
