import type { MerchantSeed } from '../types';
import { necessities } from '../types';

/** Drugstore — NL drogist / OTC + toiletries */
export const DRUGSTORE_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'ETOS',
        name: 'Etos',
        matchValue: 'Etos',
        aliases: ['Etos', 'ETOS BV'],
        mcc: '5912',
        jarKey: necessities,
        categoryTemplateKey: 'DRUGSTORE',
        logoDomain: 'etos.nl',
        website: 'https://etos.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'KRUIDVAT',
        name: 'Kruidvat',
        matchValue: 'Kruidvat',
        aliases: ['Kruidvat', 'KRUIDVAT'],
        mcc: '5912',
        jarKey: necessities,
        categoryTemplateKey: 'DRUGSTORE',
        logoDomain: 'kruidvat.nl',
        website: 'https://kruidvat.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'DA',
        name: 'DA',
        matchValue: 'DA ',
        aliases: ['DA Drogisterij', 'DA ', 'D.A. '],
        mcc: '5912',
        jarKey: necessities,
        categoryTemplateKey: 'DRUGSTORE',
        logoDomain: 'da.nl',
        website: 'https://da.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'TREKPLEISTER',
        name: 'Trekpleister',
        matchValue: 'Trekpleister',
        aliases: ['Trekpleister', 'TREKPLEISTER'],
        mcc: '5912',
        jarKey: necessities,
        categoryTemplateKey: 'DRUGSTORE',
        logoDomain: 'trekpleister.nl',
        website: 'https://trekpleister.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'DI_DROGIST',
        name: 'Di',
        matchValue: 'Di Drogist',
        aliases: ['Di Drogist', 'Di ', 'DI DROGIST'],
        mcc: '5912',
        jarKey: necessities,
        categoryTemplateKey: 'DRUGSTORE',
        logoDomain: 'di.nl',
        website: 'https://di.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BOOTS',
        name: 'Boots',
        matchValue: 'Boots',
        aliases: ['Boots', 'BOOTS'],
        mcc: '5912',
        jarKey: necessities,
        categoryTemplateKey: 'DRUGSTORE',
        logoDomain: 'boots.com',
        website: 'https://boots.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];
