import type { MerchantSeed } from '../types';
import { play } from '../types';

/** eating-out merchant presets */
export const EATING_OUT_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'THUISBEZORGD',
        name: 'Thuisbezorgd',
        matchValue: 'Thuisbezorgd',
        aliases: ['Thuisbezorgd', 'Just Eat', 'JE*THUISBEZORGD'],
        mcc: '5812',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
        logoDomain: 'thuisbezorgd.nl',
        website: 'https://thuisbezorgd.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 1,
        isActive: true,
    },
    {
        key: 'UBER_EATS',
        name: 'Uber Eats',
        matchValue: 'Uber Eats',
        aliases: ['Uber Eats', 'UBER *EATS', 'UBEREATS'],
        mcc: '5812',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
        logoDomain: 'ubereats.com',
        website: 'https://ubereats.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 1,
        isActive: true,
    },
    {
        key: 'DELIVEROO',
        name: 'Deliveroo',
        matchValue: 'Deliveroo',
        aliases: ['Deliveroo', 'DELIVEROO'],
        mcc: '5812',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
        logoDomain: 'deliveroo.nl',
        website: 'https://deliveroo.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'STARBUCKS',
        name: 'Starbucks',
        matchValue: 'Starbucks',
        aliases: ['Starbucks', 'STARBUCKS', 'SBUX'],
        mcc: '5814',
        jarKey: play,
        categoryTemplateKey: 'COFFEE',
        logoDomain: 'starbucks.com',
        website: 'https://starbucks.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BAGELS_AND_BEANS',
        name: 'Bagels & Beans',
        matchValue: 'Bagels & Beans',
        aliases: ['Bagels & Beans', 'Bagels and Beans', 'B&B Coffee'],
        mcc: '5814',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
        logoDomain: 'bagelsbeans.nl',
        website: 'https://bagelsbeans.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'DOUWE_EGBERTS_CAFE',
        name: 'Douwe Egberts Café',
        matchValue: 'Douwe Egberts',
        aliases: ['Douwe Egberts Café', 'Douwe Egberts Cafe', 'DE Café'],
        mcc: '5814',
        jarKey: play,
        categoryTemplateKey: 'COFFEE',
        logoDomain: 'douwe-egberts.com',
        website: 'https://douwe-egberts.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'COFFEECOMPANY',
        name: 'Coffeecompany',
        matchValue: 'Coffeecompany',
        aliases: ['Coffeecompany', 'Coffee Company', 'COFFEECOMPANY'],
        mcc: '5814',
        jarKey: play,
        categoryTemplateKey: 'COFFEE',
        logoDomain: 'coffeecompany.nl',
        website: 'https://coffeecompany.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'MCDONALDS',
        name: "McDonald's",
        matchValue: "McDonald's",
        aliases: ['McDonalds', "MCDONALD'S", 'McD'],
        mcc: '5814',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
        logoDomain: 'mcdonalds.com',
        website: 'https://mcdonalds.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BURGER_KING',
        name: 'Burger King',
        matchValue: 'Burger King',
        aliases: ['Burger King', 'BURGER KING', 'BK '],
        mcc: '5814',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
        logoDomain: 'burgerking.nl',
        website: 'https://burgerking.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'KFC',
        name: 'KFC',
        matchValue: 'KFC',
        aliases: ['KFC', 'Kentucky Fried Chicken'],
        mcc: '5814',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
        logoDomain: 'kfc.nl',
        website: 'https://kfc.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'DOMINOS',
        name: "Domino's",
        matchValue: "Domino's",
        aliases: ['Dominos', "DOMINO'S PIZZA"],
        mcc: '5814',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
        logoDomain: 'dominos.nl',
        website: 'https://dominos.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'NEW_YORK_PIZZA',
        name: 'New York Pizza',
        matchValue: 'New York Pizza',
        aliases: ['New York Pizza', 'NYP', 'NEW YORK PIZZA'],
        mcc: '5814',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
        logoDomain: 'newyorkpizza.nl',
        website: 'https://newyorkpizza.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'SUBWAY',
        name: 'Subway',
        matchValue: 'Subway',
        aliases: ['Subway', 'SUBWAY'],
        mcc: '5814',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
        logoDomain: 'subway.com',
        website: 'https://subway.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'FEBO',
        name: 'FEBO',
        matchValue: 'FEBO',
        aliases: ['FEBO', 'Febo'],
        mcc: '5814',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
        logoDomain: 'febo.nl',
        website: 'https://febo.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'WOK_TO_GO',
        name: 'Wok to Walk',
        matchValue: 'Wok to Walk',
        aliases: ['Wok to Walk', 'Wok to Go', 'WOK TO WALK'],
        mcc: '5814',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
        logoDomain: 'woktowalk.com',
        website: 'https://woktowalk.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BURGERME',
        name: 'Burgerme',
        matchValue: 'Burgerme',
        aliases: ['Burgerme', 'BURGERME', 'Burger Me'],
        mcc: '5814',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
        logoDomain: 'burgerme.nl',
        website: 'https://burgerme.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'COFFEE_FELLOWS',
        name: 'Coffee Fellows',
        matchValue: 'Coffee Fellows',
        aliases: ['Coffee Fellows', 'COFFEE FELLOWS'],
        mcc: '5814',
        jarKey: play,
        categoryTemplateKey: 'COFFEE',
        logoDomain: 'coffee-fellows.com',
        website: 'https://coffee-fellows.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'SMULLERS',
        name: 'Smullers',
        matchValue: 'Smullers',
        aliases: ['Smullers', 'SMULLERS', 'NS Smullers'],
        mcc: '5814',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
        logoDomain: 'smullers.nl',
        website: 'https://smullers.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'JULIAS',
        name: "Julia's",
        matchValue: "Julia's",
        aliases: ["Julia's", 'Julias', 'JULIAS', "Luca's by Julia's"],
        mcc: '5814',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
        logoDomain: 'julias.nl',
        website: 'https://julias.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'TRECK',
        name: 'TRECK',
        matchValue: 'TRECK',
        aliases: ['TRECK', 'Treck', 'Broodzaak', 'BROODZAAK', "C'est du Pain"],
        mcc: '5814',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
        logoDomain: 'treck.nl',
        website: 'https://treck.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'NS_KIOSK',
        name: 'Kiosk',
        matchValue: 'Kiosk',
        aliases: ['Kiosk', 'NS Kiosk', 'KIOSK NS', 'Stations Kiosk'],
        mcc: '5499',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
        logoDomain: 'ns.nl',
        website: 'https://ns.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'STATIONSHUISKAMER',
        name: 'StationsHuiskamer',
        matchValue: 'StationsHuiskamer',
        aliases: ['StationsHuiskamer', 'Stationshuiskamer', 'Stations Huiskamer'],
        mcc: '5814',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
        logoDomain: 'ns.nl',
        website: 'https://ns.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'LA_PLACE',
        name: 'La Place',
        matchValue: 'La Place',
        aliases: ['La Place', 'LA PLACE', 'La Place Express'],
        mcc: '5812',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
        logoDomain: 'laplace.com',
        website: 'https://laplace.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BACKWERK',
        name: 'BackWerk',
        matchValue: 'BackWerk',
        aliases: ['BackWerk', 'BACKWERK', 'Back Werk'],
        mcc: '5814',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
        logoDomain: 'back-werk.nl',
        website: 'https://back-werk.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BAKKER_BART',
        name: 'Bakker Bart',
        matchValue: 'Bakker Bart',
        aliases: ['Bakker Bart', 'BAKKER BART', 'Bakker Bart To Go'],
        mcc: '5814',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
        logoDomain: 'bakkerbart.nl',
        website: 'https://bakkerbart.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'AH_TO_GO',
        name: 'AH to go',
        matchValue: 'AH to go',
        aliases: ['AH to go', 'AH TO GO', 'AHtoGo', 'Albert Heijn to go'],
        mcc: '5411',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
        logoDomain: 'ah.nl',
        website: 'https://ah.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 1,
        isActive: true,
    },
    {
        key: 'BURGERIJ',
        name: 'Burgerij',
        matchValue: 'Burgerij',
        aliases: ['Burgerij', 'BURGERIJ'],
        mcc: '5814',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
        logoDomain: 'burgerij.nl',
        website: 'https://burgerij.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'DUNKIN',
        name: "Dunkin'",
        matchValue: 'Dunkin',
        aliases: ["Dunkin'", 'Dunkin', 'DUNKIN', 'Dunkin Donuts'],
        mcc: '5814',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
        logoDomain: 'dunkin.nl',
        website: 'https://dunkin.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'PRET_A_MANGER',
        name: 'Pret A Manger',
        matchValue: 'Pret',
        aliases: ['Pret A Manger', 'Pret', 'PRET A MANGER'],
        mcc: '5814',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
        logoDomain: 'pret.com',
        website: 'https://pret.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];
