import type { MerchantSeed } from '../types';
import { play } from '../types';

/** eating-out merchant presets */
export const EATING_OUT_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'THUISBEZORGD',
        name: 'Thuisbezorgd',
        matchValue: 'Thuisbezorgd',
        aliases: ['Thuisbezorgd', 'Just Eat', 'JE*THUISBEZORGD'],
        mcc: '5812',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
        logoDomain: 'thuisbezorgd.nl',
        website: 'https://thuisbezorgd.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 1,
        isActive: true,
    },
    {
        key: 'UBER_EATS',
        name: 'Uber Eats',
        matchValue: 'Uber Eats',
        aliases: ['Uber Eats', 'UBER *EATS', 'UBEREATS'],
        mcc: '5812',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
        logoDomain: 'ubereats.com',
        website: 'https://ubereats.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 1,
        isActive: true,
    },
    {
        key: 'DELIVEROO',
        name: 'Deliveroo',
        matchValue: 'Deliveroo',
        aliases: ['Deliveroo', 'DELIVEROO'],
        mcc: '5812',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
        logoDomain: 'deliveroo.nl',
        website: 'https://deliveroo.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'STARBUCKS',
        name: 'Starbucks',
        matchValue: 'Starbucks',
        aliases: ['Starbucks', 'STARBUCKS', 'SBUX'],
        mcc: '5814',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
        logoDomain: 'starbucks.com',
        website: 'https://starbucks.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BAGELS_AND_BEANS',
        name: 'Bagels & Beans',
        matchValue: 'Bagels & Beans',
        aliases: ['Bagels & Beans', 'Bagels and Beans', 'B&B Coffee'],
        mcc: '5814',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
        logoDomain: 'bagelsbeans.nl',
        website: 'https://bagelsbeans.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'DOUWE_EGBERTS_CAFE',
        name: 'Douwe Egberts Café',
        matchValue: 'Douwe Egberts',
        aliases: ['Douwe Egberts Café', 'Douwe Egberts Cafe', 'DE Café'],
        mcc: '5814',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
        logoDomain: 'douwe-egberts.com',
        website: 'https://douwe-egberts.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'COFFEECOMPANY',
        name: 'Coffeecompany',
        matchValue: 'Coffeecompany',
        aliases: ['Coffeecompany', 'Coffee Company', 'COFFEECOMPANY'],
        mcc: '5814',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
        logoDomain: 'coffeecompany.nl',
        website: 'https://coffeecompany.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'MCDONALDS',
        name: "McDonald's",
        matchValue: "McDonald's",
        aliases: ['McDonalds', "MCDONALD'S", 'McD'],
        mcc: '5814',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
        logoDomain: 'mcdonalds.com',
        website: 'https://mcdonalds.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BURGER_KING',
        name: 'Burger King',
        matchValue: 'Burger King',
        aliases: ['Burger King', 'BURGER KING', 'BK '],
        mcc: '5814',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
        logoDomain: 'burgerking.nl',
        website: 'https://burgerking.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'KFC',
        name: 'KFC',
        matchValue: 'KFC',
        aliases: ['KFC', 'Kentucky Fried Chicken'],
        mcc: '5814',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
        logoDomain: 'kfc.nl',
        website: 'https://kfc.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'DOMINOS',
        name: "Domino's",
        matchValue: "Domino's",
        aliases: ['Dominos', "DOMINO'S PIZZA"],
        mcc: '5814',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
        logoDomain: 'dominos.nl',
        website: 'https://dominos.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'NEW_YORK_PIZZA',
        name: 'New York Pizza',
        matchValue: 'New York Pizza',
        aliases: ['New York Pizza', 'NYP', 'NEW YORK PIZZA'],
        mcc: '5814',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
        logoDomain: 'newyorkpizza.nl',
        website: 'https://newyorkpizza.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'SUBWAY',
        name: 'Subway',
        matchValue: 'Subway',
        aliases: ['Subway', 'SUBWAY'],
        mcc: '5814',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
        logoDomain: 'subway.com',
        website: 'https://subway.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'FEBO',
        name: 'FEBO',
        matchValue: 'FEBO',
        aliases: ['FEBO', 'Febo'],
        mcc: '5814',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
        logoDomain: 'febo.nl',
        website: 'https://febo.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'WOK_TO_GO',
        name: 'Wok to Walk',
        matchValue: 'Wok to Walk',
        aliases: ['Wok to Walk', 'Wok to Go', 'WOK TO WALK'],
        mcc: '5814',
        jarKey: play,
        categoryTemplateKey: 'EATING_OUT',
        logoDomain: 'woktowalk.com',
        website: 'https://woktowalk.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];
