import type { MerchantSeed } from '../types';
import { education } from '../types';

/** education merchant presets */
export const EDUCATION_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'BRUNA',
        name: 'Bruna',
        matchValue: 'Bruna',
        aliases: ['Bruna', 'BRUNA NL', 'Bruna Boeken'],
        mcc: '5942',
        jarKey: education,
        categoryTemplateKey: 'BOOKS',
        logoDomain: 'bruna.nl',
        website: 'https://bruna.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'AKO',
        name: 'AKO',
        matchValue: 'AKO',
        aliases: ['AKO', 'AKO Boeken'],
        mcc: '5942',
        jarKey: education,
        categoryTemplateKey: 'BOOKS',
        logoDomain: 'ako.nl',
        website: 'https://ako.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'LIBRIS',
        name: 'Libris',
        matchValue: 'Libris',
        aliases: ['Libris', 'LIBRIS'],
        mcc: '5942',
        jarKey: education,
        categoryTemplateKey: 'BOOKS',
        logoDomain: 'libris.nl',
        website: 'https://libris.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BOEKHANDEL_DONNER',
        name: 'Donner',
        matchValue: 'Donner',
        aliases: ['Donner', 'Boekhandel Donner', 'DONNER'],
        mcc: '5942',
        jarKey: education,
        categoryTemplateKey: 'BOOKS',
        logoDomain: 'donner.nl',
        website: 'https://donner.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'AMERICAN_BOOK_CENTER',
        name: 'American Book Center',
        matchValue: 'American Book Center',
        aliases: ['American Book Center', 'ABC Amsterdam', 'American Bookstore'],
        mcc: '5942',
        jarKey: education,
        categoryTemplateKey: 'BOOKS',
        logoDomain: 'abc.nl',
        website: 'https://abc.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'AUDIBLE',
        name: 'Audible',
        matchValue: 'Audible',
        aliases: ['Audible', 'AUDIBLE'],
        mcc: '5815',
        jarKey: education,
        categoryTemplateKey: 'BOOKS',
        logoDomain: 'audible.nl',
        website: 'https://audible.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'STORYTEL',
        name: 'Storytel',
        matchValue: 'Storytel',
        aliases: ['Storytel', 'STORYTEL'],
        mcc: '5815',
        jarKey: education,
        categoryTemplateKey: 'BOOKS',
        logoDomain: 'storytel.com',
        website: 'https://storytel.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'UDEMY',
        name: 'Udemy',
        matchValue: 'Udemy',
        aliases: ['Udemy', 'UDEMY'],
        mcc: '8299',
        jarKey: education,
        categoryTemplateKey: 'COURSES',
        logoDomain: 'udemy.com',
        website: 'https://udemy.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'COURSERA',
        name: 'Coursera',
        matchValue: 'Coursera',
        aliases: ['Coursera', 'COURSERA'],
        mcc: '8299',
        jarKey: education,
        categoryTemplateKey: 'COURSES',
        logoDomain: 'coursera.org',
        website: 'https://coursera.org',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'LINKEDIN_LEARNING',
        name: 'LinkedIn Learning',
        matchValue: 'LinkedIn Learning',
        aliases: ['LinkedIn Learning', 'LYNDA', 'LinkedIn Learn'],
        mcc: '8299',
        jarKey: education,
        categoryTemplateKey: 'COURSES',
        logoDomain: 'linkedin.com',
        website: 'https://linkedin.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'SKILLSHARE',
        name: 'Skillshare',
        matchValue: 'Skillshare',
        aliases: ['Skillshare', 'SKILLSHARE'],
        mcc: '8299',
        jarKey: education,
        categoryTemplateKey: 'COURSES',
        logoDomain: 'skillshare.com',
        website: 'https://skillshare.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'MASTERCLASS',
        name: 'MasterClass',
        matchValue: 'MasterClass',
        aliases: ['MasterClass', 'MASTERCLASS'],
        mcc: '8299',
        jarKey: education,
        categoryTemplateKey: 'COURSES',
        logoDomain: 'masterclass.com',
        website: 'https://masterclass.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'OPEN_UNIVERSITEIT',
        name: 'Open Universiteit',
        matchValue: 'Open Universiteit',
        aliases: ['Open Universiteit', 'OU ', 'Open University NL'],
        mcc: '8220',
        jarKey: education,
        categoryTemplateKey: 'COURSES',
        logoDomain: 'ou.nl',
        website: 'https://ou.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'NTI',
        name: 'NTI',
        matchValue: 'NTI',
        aliases: ['NTI', 'NTI Opleidingen'],
        mcc: '8299',
        jarKey: education,
        categoryTemplateKey: 'COURSES',
        logoDomain: 'nti.nl',
        website: 'https://nti.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'LOI',
        name: 'LOI',
        matchValue: 'LOI',
        aliases: ['LOI', 'Leidse Onderwijsinstellingen'],
        mcc: '8299',
        jarKey: education,
        categoryTemplateKey: 'COURSES',
        logoDomain: 'loi.nl',
        website: 'https://loi.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'STUDIELINK',
        name: 'Studielink',
        matchValue: 'Studielink',
        aliases: ['Studielink', 'STUDIELINK'],
        mcc: '8220',
        jarKey: education,
        categoryTemplateKey: 'TUITION',
        logoDomain: 'studielink.nl',
        website: 'https://studielink.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'UNIVERSITEIT_VAN_AMSTERDAM',
        name: 'Universiteit van Amsterdam',
        matchValue: 'Universiteit van Amsterdam',
        aliases: ['Universiteit van Amsterdam', 'UvA', 'UVA'],
        mcc: '8220',
        jarKey: education,
        categoryTemplateKey: 'TUITION',
        logoDomain: 'uva.nl',
        website: 'https://uva.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'CANVA',
        name: 'Canva',
        matchValue: 'Canva',
        aliases: ['Canva', 'CANVA'],
        mcc: '5734',
        jarKey: education,
        categoryTemplateKey: 'TOOLS',
        logoDomain: 'canva.com',
        website: 'https://canva.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'NOTION',
        name: 'Notion',
        matchValue: 'Notion',
        aliases: ['Notion', 'NOTION'],
        mcc: '5734',
        jarKey: education,
        categoryTemplateKey: 'TOOLS',
        logoDomain: 'notion.so',
        website: 'https://notion.so',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'FIGMA',
        name: 'Figma',
        matchValue: 'Figma',
        aliases: ['Figma', 'FIGMA'],
        mcc: '5734',
        jarKey: education,
        categoryTemplateKey: 'TOOLS',
        logoDomain: 'figma.com',
        website: 'https://figma.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'MIDJOURNEY',
        name: 'Midjourney',
        matchValue: 'Midjourney',
        aliases: ['Midjourney', 'MIDJOURNEY'],
        mcc: '5734',
        jarKey: education,
        categoryTemplateKey: 'TOOLS',
        logoDomain: 'midjourney.com',
        website: 'https://midjourney.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];
