import type { MerchantSeed } from '../types';
import { play } from '../types';

/** Electronics — Coolblue / MediaMarkt / BCC / Apple. */
export const ELECTRONICS_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'COOLBLUE',
        name: 'Coolblue',
        matchValue: 'Coolblue',
        aliases: ['Coolblue', 'COOLBLUE', 'Coolblue BV'],
        mcc: '5732',
        jarKey: play,
        categoryTemplateKey: 'ELECTRONICS',
        logoDomain: 'coolblue.nl',
        website: 'https://coolblue.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'MEDIAMARKT',
        name: 'MediaMarkt',
        matchValue: 'MediaMarkt',
        aliases: ['MediaMarkt', 'MEDIA MARKT', 'Media Markt'],
        mcc: '5732',
        jarKey: play,
        categoryTemplateKey: 'ELECTRONICS',
        logoDomain: 'mediamarkt.nl',
        website: 'https://mediamarkt.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BCC',
        name: 'BCC',
        matchValue: 'BCC',
        aliases: ['BCC', 'BCC Elektro'],
        mcc: '5732',
        jarKey: play,
        categoryTemplateKey: 'ELECTRONICS',
        logoDomain: 'bcc.nl',
        website: 'https://bcc.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'APPLE_STORE',
        name: 'Apple Store',
        matchValue: 'Apple Store',
        aliases: ['Apple Store', 'APPLE STORE', 'Apple.com/nl'],
        mcc: '5732',
        jarKey: play,
        categoryTemplateKey: 'ELECTRONICS',
        logoDomain: 'apple.com',
        website: 'https://apple.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];
