import type { MerchantSeed } from '../types';
import { play } from '../types';

/** events merchant presets */
export const EVENTS_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'TICKETMASTER',
        name: 'Ticketmaster',
        matchValue: 'Ticketmaster',
        aliases: ['Ticketmaster', 'TICKETMASTER'],
        mcc: '7922',
        jarKey: play,
        categoryTemplateKey: 'EVENTS',
        logoDomain: 'ticketmaster.nl',
        website: 'https://ticketmaster.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'EVENTIM',
        name: 'Eventim',
        matchValue: 'Eventim',
        aliases: ['Eventim', 'EVENTIM'],
        mcc: '7922',
        jarKey: play,
        categoryTemplateKey: 'EVENTS',
        logoDomain: 'eventim.nl',
        website: 'https://eventim.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'PATHE',
        name: 'Pathé',
        matchValue: 'Pathé',
        aliases: ['Pathé', 'Pathe', 'PATHÉ'],
        mcc: '7832',
        jarKey: play,
        categoryTemplateKey: 'EVENTS',
        logoDomain: 'pathe.nl',
        website: 'https://pathe.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'TICKETSWAP',
        name: 'Ticketswap',
        matchValue: 'Ticketswap',
        aliases: ['Ticketswap', 'TICKETSWAP'],
        mcc: '7922',
        jarKey: play,
        categoryTemplateKey: 'EVENTS',
        logoDomain: 'ticketswap.com',
        website: 'https://ticketswap.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];
