import type { MerchantSeed } from '../types';
import { necessities } from '../types';

/** family merchant presets */
export const FAMILY_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'PRENATAL',
        name: 'Prenatal',
        matchValue: 'Prenatal',
        aliases: ['Prenatal', 'PRÉNATAL', 'Prenatal NL'],
        mcc: '5641',
        jarKey: necessities,
        categoryTemplateKey: 'FAMILY',
        logoDomain: 'prenatal.nl',
        website: 'https://prenatal.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'HEMA_FAMILY',
        name: 'HEMA (kids)',
        matchValue: 'HEMA',
        aliases: ['HEMA kids', 'HEMA baby'],
        mcc: '5641',
        jarKey: necessities,
        categoryTemplateKey: 'FAMILY',
        logoDomain: 'hema.nl',
        website: 'https://hema.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'INTERTOYS',
        name: 'Intertoys',
        matchValue: 'Intertoys',
        aliases: ['Intertoys', 'INTERTOYS'],
        mcc: '5945',
        jarKey: necessities,
        categoryTemplateKey: 'FAMILY',
        logoDomain: 'intertoys.nl',
        website: 'https://intertoys.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BART_SMIT',
        name: 'Bart Smit',
        matchValue: 'Bart Smit',
        aliases: ['Bart Smit', 'BART SMIT'],
        mcc: '5945',
        jarKey: necessities,
        categoryTemplateKey: 'FAMILY',
        logoDomain: 'bartsmit.com',
        website: 'https://bartsmit.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'VAN_ASTEN',
        name: 'Van Asten BabySuperstore',
        matchValue: 'Van Asten',
        aliases: ['Van Asten', 'Van Asten BabySuperstore', 'Babysuperstore'],
        mcc: '5641',
        jarKey: necessities,
        categoryTemplateKey: 'FAMILY',
        logoDomain: 'vanasten.nl',
        website: 'https://vanasten.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BABY_DUMP',
        name: 'Baby-Dump',
        matchValue: 'Baby-Dump',
        aliases: ['Baby-Dump', 'Baby Dump', 'BABYDUMP'],
        mcc: '5641',
        jarKey: necessities,
        categoryTemplateKey: 'FAMILY',
        logoDomain: 'babydump.nl',
        website: 'https://babydump.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];
