import type { MerchantSeed } from '../types';
import { necessities } from '../types';

/** family merchant presets */
export const FAMILY_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'PRENATAL',
        name: 'Prenatal',
        matchValue: 'Prenatal',
        aliases: ['Prenatal', 'PRÉNATAL', 'Prenatal NL'],
        mcc: '5641',
        jarKey: necessities,
        categoryTemplateKey: 'FAMILY',
        logoDomain: 'prenatal.nl',
        website: 'https://prenatal.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'HEMA_FAMILY',
        name: 'HEMA (kids)',
        matchValue: 'HEMA kids',
        aliases: ['HEMA baby'],
        mcc: '5641',
        jarKey: necessities,
        categoryTemplateKey: 'FAMILY',
        logoDomain: 'hema.nl',
        website: 'https://hema.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'INTERTOYS',
        name: 'Intertoys',
        matchValue: 'Intertoys',
        aliases: ['Intertoys', 'INTERTOYS'],
        mcc: '5945',
        jarKey: necessities,
        categoryTemplateKey: 'FAMILY',
        logoDomain: 'intertoys.nl',
        website: 'https://intertoys.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BART_SMIT',
        name: 'Bart Smit',
        matchValue: 'Bart Smit',
        aliases: ['Bart Smit', 'BART SMIT'],
        mcc: '5945',
        jarKey: necessities,
        categoryTemplateKey: 'FAMILY',
        logoDomain: 'bartsmit.com',
        website: 'https://bartsmit.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'VAN_ASTEN',
        name: 'Van Asten BabySuperstore',
        matchValue: 'Van Asten',
        aliases: ['Van Asten', 'Van Asten BabySuperstore', 'Babysuperstore'],
        mcc: '5641',
        jarKey: necessities,
        categoryTemplateKey: 'FAMILY',
        logoDomain: 'vanasten.nl',
        website: 'https://vanasten.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BABY_DUMP',
        name: 'Baby-Dump',
        matchValue: 'Baby-Dump',
        aliases: ['Baby-Dump', 'Baby Dump', 'BABYDUMP'],
        mcc: '5641',
        jarKey: necessities,
        categoryTemplateKey: 'FAMILY',
        logoDomain: 'babydump.nl',
        website: 'https://babydump.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'PARTOU',
        name: 'Partou',
        matchValue: 'Partou',
        aliases: ['Partou', 'PARTOU'],
        mcc: '8351',
        jarKey: necessities,
        categoryTemplateKey: 'FAMILY',
        logoDomain: 'partou.nl',
        website: 'https://partou.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'SMALLSTEPS',
        name: 'Smallsteps',
        matchValue: 'Smallsteps',
        aliases: ['Smallsteps', 'SMALLSTEPS', 'Small Steps'],
        mcc: '8351',
        jarKey: necessities,
        categoryTemplateKey: 'FAMILY',
        logoDomain: 'smallsteps.nl',
        website: 'https://smallsteps.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'KIDSFOUNDATION',
        name: 'KidsFoundation',
        matchValue: 'KidsFoundation',
        aliases: ['KidsFoundation', 'KIDSFOUNDATION', 'Kids Foundation'],
        mcc: '8351',
        jarKey: necessities,
        categoryTemplateKey: 'FAMILY',
        logoDomain: 'kidsfoundation.nl',
        website: 'https://kidsfoundation.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'KINDERGARDEN',
        name: 'Kindergarden',
        matchValue: 'Kindergarden',
        aliases: ['Kindergarden', 'KINDERGARDEN'],
        mcc: '8351',
        jarKey: necessities,
        categoryTemplateKey: 'FAMILY',
        logoDomain: 'kindergarden.nl',
        website: 'https://kindergarden.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BINK',
        name: 'Bink',
        matchValue: 'Bink',
        aliases: ['Bink', 'BINK', 'Bink Kinderopvang'],
        mcc: '8351',
        jarKey: necessities,
        categoryTemplateKey: 'FAMILY',
        logoDomain: 'bink.nl',
        website: 'https://bink.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'HUMANITAS',
        name: 'Humanitas Kinderopvang',
        matchValue: 'Humanitas',
        aliases: ['Humanitas', 'Humanitas Kinderopvang', 'HUMANITAS'],
        mcc: '8351',
        jarKey: necessities,
        categoryTemplateKey: 'FAMILY',
        logoDomain: 'humanitas.nl',
        website: 'https://humanitas.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'SKSG',
        name: 'SKSG',
        matchValue: 'SKSG',
        aliases: ['SKSG', 'Stichting Kinderopvang Stad Groningen'],
        mcc: '8351',
        jarKey: necessities,
        categoryTemplateKey: 'FAMILY',
        logoDomain: 'sksg.nl',
        website: 'https://sksg.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'DOREMI',
        name: 'Doremi',
        matchValue: 'Doremi',
        aliases: ['Doremi', 'DOREMI', 'Doremi Kinderopvang'],
        mcc: '8351',
        jarKey: necessities,
        categoryTemplateKey: 'FAMILY',
        logoDomain: 'doremi.nl',
        website: 'https://doremi.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];
