import type { MerchantSeed } from '../types';
import { play } from '../types';

/** fashion merchant presets */
export const FASHION_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'ZEEMAN',
        name: 'Zeeman',
        matchValue: 'Zeeman',
        aliases: ['Zeeman', 'ZEEMAN TEXTIEL'],
        mcc: '5651',
        jarKey: play,
        categoryTemplateKey: 'FASHION',
        logoDomain: 'zeeman.com',
        website: 'https://zeeman.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'H_AND_M',
        name: 'H&M',
        matchValue: 'H&M',
        aliases: ['H&M', 'H AND M', 'Hennes Mauritz'],
        mcc: '5651',
        jarKey: play,
        categoryTemplateKey: 'FASHION',
        logoDomain: 'hm.com',
        website: 'https://hm.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ZARA',
        name: 'Zara',
        matchValue: 'Zara',
        aliases: ['Zara', 'ZARA'],
        mcc: '5651',
        jarKey: play,
        categoryTemplateKey: 'FASHION',
        logoDomain: 'zara.com',
        website: 'https://zara.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'PRIMARK',
        name: 'Primark',
        matchValue: 'Primark',
        aliases: ['Primark', 'PRIMARK'],
        mcc: '5651',
        jarKey: play,
        categoryTemplateKey: 'FASHION',
        logoDomain: 'primark.com',
        website: 'https://primark.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'C_AND_A',
        name: 'C&A',
        matchValue: 'C&A',
        aliases: ['C&A', 'C and A', 'CEA'],
        mcc: '5651',
        jarKey: play,
        categoryTemplateKey: 'FASHION',
        logoDomain: 'c-and-a.com',
        website: 'https://c-and-a.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'WE_FASHION',
        name: 'WE Fashion',
        matchValue: 'WE Fashion',
        aliases: ['WE Fashion', 'WE ', 'WE FASHION'],
        mcc: '5651',
        jarKey: play,
        categoryTemplateKey: 'FASHION',
        logoDomain: 'wefashion.com',
        website: 'https://wefashion.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'COOLCAT',
        name: 'Coolcat',
        matchValue: 'Coolcat',
        aliases: ['Coolcat', 'COOLCAT'],
        mcc: '5651',
        jarKey: play,
        categoryTemplateKey: 'FASHION',
        logoDomain: 'coolcat.nl',
        website: 'https://coolcat.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'UNIQLO',
        name: 'Uniqlo',
        matchValue: 'Uniqlo',
        aliases: ['Uniqlo', 'UNIQLO'],
        mcc: '5651',
        jarKey: play,
        categoryTemplateKey: 'FASHION',
        logoDomain: 'uniqlo.com',
        website: 'https://uniqlo.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'MANGO',
        name: 'Mango',
        matchValue: 'Mango',
        aliases: ['Mango', 'MANGO'],
        mcc: '5651',
        jarKey: play,
        categoryTemplateKey: 'FASHION',
        logoDomain: 'mango.com',
        website: 'https://mango.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'MASSIMO_DUTTI',
        name: 'Massimo Dutti',
        matchValue: 'Massimo Dutti',
        aliases: ['Massimo Dutti', 'MASSIMO DUTTI'],
        mcc: '5651',
        jarKey: play,
        categoryTemplateKey: 'FASHION',
        logoDomain: 'massimodutti.com',
        website: 'https://massimodutti.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ONLY',
        name: 'ONLY',
        matchValue: 'ONLY',
        aliases: ['ONLY', 'Only Fashion'],
        mcc: '5651',
        jarKey: play,
        categoryTemplateKey: 'FASHION',
        logoDomain: 'only.com',
        website: 'https://only.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'VERO_MODA',
        name: 'Vero Moda',
        matchValue: 'Vero Moda',
        aliases: ['Vero Moda', 'VERO MODA'],
        mcc: '5651',
        jarKey: play,
        categoryTemplateKey: 'FASHION',
        logoDomain: 'veromoda.com',
        website: 'https://veromoda.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'SCOTCH_AND_SODA',
        name: 'Scotch & Soda',
        matchValue: 'Scotch & Soda',
        aliases: ['Scotch & Soda', 'Scotch and Soda', 'SCOTCH SODA'],
        mcc: '5651',
        jarKey: play,
        categoryTemplateKey: 'FASHION',
        logoDomain: 'scotch-soda.com',
        website: 'https://scotch-soda.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'SUITSUPPLY',
        name: 'Suitsupply',
        matchValue: 'Suitsupply',
        aliases: ['Suitsupply', 'SUITSUPPLY'],
        mcc: '5651',
        jarKey: play,
        categoryTemplateKey: 'FASHION',
        logoDomain: 'suitsupply.com',
        website: 'https://suitsupply.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BIJENKORF',
        name: 'de Bijenkorf',
        matchValue: 'Bijenkorf',
        aliases: ['de Bijenkorf', 'Bijenkorf', 'BIJENKORF'],
        mcc: '5311',
        jarKey: play,
        categoryTemplateKey: 'FASHION',
        logoDomain: 'debijenkorf.nl',
        website: 'https://debijenkorf.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'HUGO_BOSS',
        name: 'Hugo Boss',
        matchValue: 'Hugo Boss',
        aliases: ['Hugo Boss', 'HUGO BOSS', 'BOSS '],
        mcc: '5651',
        jarKey: play,
        categoryTemplateKey: 'FASHION',
        logoDomain: 'hugoboss.com',
        website: 'https://hugoboss.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'TOMMY_HILFIGER',
        name: 'Tommy Hilfiger',
        matchValue: 'Tommy Hilfiger',
        aliases: ['Tommy Hilfiger', 'TOMMY HILFIGER', 'Tommy'],
        mcc: '5651',
        jarKey: play,
        categoryTemplateKey: 'FASHION',
        logoDomain: 'tommy.com',
        website: 'https://tommy.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'CALVIN_KLEIN',
        name: 'Calvin Klein',
        matchValue: 'Calvin Klein',
        aliases: ['Calvin Klein', 'CALVIN KLEIN', 'CK '],
        mcc: '5651',
        jarKey: play,
        categoryTemplateKey: 'FASHION',
        logoDomain: 'calvinklein.com',
        website: 'https://calvinklein.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'RALPH_LAUREN',
        name: 'Ralph Lauren',
        matchValue: 'Ralph Lauren',
        aliases: ['Ralph Lauren', 'RALPH LAUREN', 'Polo Ralph Lauren'],
        mcc: '5651',
        jarKey: play,
        categoryTemplateKey: 'FASHION',
        logoDomain: 'ralphlauren.com',
        website: 'https://ralphlauren.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'LACOSTE',
        name: 'Lacoste',
        matchValue: 'Lacoste',
        aliases: ['Lacoste', 'LACOSTE'],
        mcc: '5651',
        jarKey: play,
        categoryTemplateKey: 'FASHION',
        logoDomain: 'lacoste.com',
        website: 'https://lacoste.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ARMANI',
        name: 'Armani',
        matchValue: 'Armani',
        aliases: ['Armani', 'Giorgio Armani', 'Emporio Armani', 'ARMANI'],
        mcc: '5651',
        jarKey: play,
        categoryTemplateKey: 'FASHION',
        logoDomain: 'armani.com',
        website: 'https://armani.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'GUCCI',
        name: 'Gucci',
        matchValue: 'Gucci',
        aliases: ['Gucci', 'GUCCI'],
        mcc: '5651',
        jarKey: play,
        categoryTemplateKey: 'FASHION',
        logoDomain: 'gucci.com',
        website: 'https://gucci.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'PRADA',
        name: 'Prada',
        matchValue: 'Prada',
        aliases: ['Prada', 'PRADA'],
        mcc: '5651',
        jarKey: play,
        categoryTemplateKey: 'FASHION',
        logoDomain: 'prada.com',
        website: 'https://prada.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'DIOR',
        name: 'Dior',
        matchValue: 'Dior',
        aliases: ['Dior', 'Christian Dior', 'DIOR'],
        mcc: '5651',
        jarKey: play,
        categoryTemplateKey: 'FASHION',
        logoDomain: 'dior.com',
        website: 'https://dior.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'LOUIS_VUITTON',
        name: 'Louis Vuitton',
        matchValue: 'Louis Vuitton',
        aliases: ['Louis Vuitton', 'LV ', 'LOUIS VUITTON'],
        mcc: '5948',
        jarKey: play,
        categoryTemplateKey: 'FASHION',
        logoDomain: 'louisvuitton.com',
        website: 'https://louisvuitton.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'CHANEL',
        name: 'Chanel',
        matchValue: 'Chanel',
        aliases: ['Chanel', 'CHANEL'],
        mcc: '5977',
        jarKey: play,
        categoryTemplateKey: 'FASHION',
        logoDomain: 'chanel.com',
        website: 'https://chanel.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'HERMES',
        name: 'Hermès',
        matchValue: 'Hermes',
        aliases: ['Hermès', 'Hermes', 'HERMES'],
        mcc: '5948',
        jarKey: play,
        categoryTemplateKey: 'FASHION',
        logoDomain: 'hermes.com',
        website: 'https://hermes.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BURBERRY',
        name: 'Burberry',
        matchValue: 'Burberry',
        aliases: ['Burberry', 'BURBERRY'],
        mcc: '5651',
        jarKey: play,
        categoryTemplateKey: 'FASHION',
        logoDomain: 'burberry.com',
        website: 'https://burberry.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BALENCIAGA',
        name: 'Balenciaga',
        matchValue: 'Balenciaga',
        aliases: ['Balenciaga', 'BALENCIAGA'],
        mcc: '5651',
        jarKey: play,
        categoryTemplateKey: 'FASHION',
        logoDomain: 'balenciaga.com',
        website: 'https://balenciaga.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'VERSACE',
        name: 'Versace',
        matchValue: 'Versace',
        aliases: ['Versace', 'VERSACE'],
        mcc: '5651',
        jarKey: play,
        categoryTemplateKey: 'FASHION',
        logoDomain: 'versace.com',
        website: 'https://versace.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'MICHAEL_KORS',
        name: 'Michael Kors',
        matchValue: 'Michael Kors',
        aliases: ['Michael Kors', 'MICHAEL KORS', 'MK '],
        mcc: '5948',
        jarKey: play,
        categoryTemplateKey: 'FASHION',
        logoDomain: 'michaelkors.com',
        website: 'https://michaelkors.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'COACH',
        name: 'Coach',
        matchValue: 'Coach',
        aliases: ['Coach', 'COACH'],
        mcc: '5948',
        jarKey: play,
        categoryTemplateKey: 'FASHION',
        logoDomain: 'coach.com',
        website: 'https://coach.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];
