import type { MerchantSeed } from '../types';
import { necessities } from '../types';

/** fines merchant presets */
export const FINES_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'CJIB',
        name: 'CJIB',
        matchValue: 'CJIB',
        aliases: ['CJIB', 'Centraal Justitieel Incassobureau', 'CJIB Verkeersboete', 'CJIB Boete'],
        mcc: '9222',
        jarKey: necessities,
        categoryTemplateKey: 'FINES',
        logoDomain: 'cjib.nl',
        website: 'https://cjib.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'POLITIE',
        name: 'Politie',
        matchValue: 'Politie',
        aliases: ['Politie', 'POLITIE NL', 'Nationale Politie', 'Parket'],
        mcc: '9222',
        jarKey: necessities,
        categoryTemplateKey: 'FINES',
        logoDomain: 'politie.nl',
        website: 'https://politie.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'OM',
        name: 'Openbaar Ministerie',
        matchValue: 'Openbaar Ministerie',
        aliases: ['Openbaar Ministerie', 'OM ', 'Parket OM'],
        mcc: '9222',
        jarKey: necessities,
        categoryTemplateKey: 'FINES',
        logoDomain: 'om.nl',
        website: 'https://om.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'GEMEENTE_BOETE',
        name: 'Gemeente (boete)',
        matchValue: 'Naheffingsaanslag',
        aliases: [
            'Nahheffingsaanslag',
            'Naheffingsaanslag',
            'Parkeerboete',
            'Fiscalisatie',
            'Gemeentelijke boete',
            'Parkeernahheffing',
            'Parkeernaheffing',
        ],
        mcc: '9222',
        jarKey: necessities,
        categoryTemplateKey: 'FINES',
        logoDomain: 'rijksoverheid.nl',
        website: 'https://rijksoverheid.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];
