import type { MerchantSeed } from '../types';
import { financialFreedom } from '../types';

/** freedom merchant presets */
export const FREEDOM_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'DEGIRO',
        name: 'DEGIRO',
        matchValue: 'DEGIRO',
        aliases: ['DEGIRO', 'Degiro'],
        mcc: '6211',
        jarKey: financialFreedom,
        categoryTemplateKey: 'INDEX_FUNDS',
        logoDomain: 'degiro.nl',
        website: 'https://degiro.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'TRADING_212',
        name: 'Trading 212',
        matchValue: 'Trading 212',
        aliases: ['Trading 212', 'TRADING212'],
        mcc: '6211',
        jarKey: financialFreedom,
        categoryTemplateKey: 'INDEX_FUNDS',
        logoDomain: 'trading212.com',
        website: 'https://trading212.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BUX',
        name: 'Bux',
        matchValue: 'Bux',
        aliases: ['Bux', 'BUX Zero', 'BUX'],
        mcc: '6211',
        jarKey: financialFreedom,
        categoryTemplateKey: 'INDEX_FUNDS',
        logoDomain: 'getbux.com',
        website: 'https://getbux.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'MEESMAN',
        name: 'Meesman',
        matchValue: 'Meesman',
        aliases: ['Meesman', 'Meesman Indexfonds'],
        mcc: '6211',
        jarKey: financialFreedom,
        categoryTemplateKey: 'INDEX_FUNDS',
        logoDomain: 'meesman.nl',
        website: 'https://meesman.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BRAND_NEW_DAY',
        name: 'Brand New Day',
        matchValue: 'Brand New Day',
        aliases: ['Brand New Day', 'BND '],
        mcc: '6211',
        jarKey: financialFreedom,
        categoryTemplateKey: 'INDEX_FUNDS',
        logoDomain: 'brandnewday.nl',
        website: 'https://brandnewday.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ETORO',
        name: 'eToro',
        matchValue: 'eToro',
        aliases: ['eToro', 'ETORO'],
        mcc: '6211',
        jarKey: financialFreedom,
        categoryTemplateKey: 'STOCKS',
        logoDomain: 'etoro.com',
        website: 'https://etoro.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'INTERACTIVE_BROKERS',
        name: 'Interactive Brokers',
        matchValue: 'Interactive Brokers',
        aliases: ['Interactive Brokers', 'IBKR', 'IBkr'],
        mcc: '6211',
        jarKey: financialFreedom,
        categoryTemplateKey: 'STOCKS',
        logoDomain: 'interactivebrokers.com',
        website: 'https://interactivebrokers.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'SAXO',
        name: 'Saxo',
        matchValue: 'Saxo',
        aliases: ['Saxo Bank', 'Saxo', 'SAXO'],
        mcc: '6211',
        jarKey: financialFreedom,
        categoryTemplateKey: 'STOCKS',
        logoDomain: 'home.saxo',
        website: 'https://home.saxo',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'REVOLUT_TRADING',
        name: 'Revolut Trading',
        matchValue: 'Revolut Trading',
        aliases: ['Revolut Trading', 'REVOLUT*TRADING'],
        mcc: '6211',
        jarKey: financialFreedom,
        categoryTemplateKey: 'STOCKS',
        logoDomain: 'revolut.com',
        website: 'https://revolut.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'PEAKS',
        name: 'Peaks',
        matchValue: 'Peaks',
        aliases: ['Peaks', 'PEAKS'],
        mcc: '6211',
        jarKey: financialFreedom,
        categoryTemplateKey: 'BONDS',
        logoDomain: 'peaks.com',
        website: 'https://peaks.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'KVK',
        name: 'KVK',
        matchValue: 'KVK',
        aliases: ['KVK', 'Kamer van Koophandel', 'KvK'],
        mcc: '9399',
        jarKey: financialFreedom,
        categoryTemplateKey: 'BUSINESS',
        logoDomain: 'kvk.nl',
        website: 'https://kvk.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'MOLLIE',
        name: 'Mollie',
        matchValue: 'Mollie',
        aliases: ['Mollie', 'MOLLIE'],
        mcc: '6012',
        jarKey: financialFreedom,
        categoryTemplateKey: 'BUSINESS',
        logoDomain: 'mollie.com',
        website: 'https://mollie.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'STRIPE',
        name: 'Stripe',
        matchValue: 'Stripe',
        aliases: ['Stripe', 'STRIPE'],
        mcc: '6012',
        jarKey: financialFreedom,
        categoryTemplateKey: 'BUSINESS',
        logoDomain: 'stripe.com',
        website: 'https://stripe.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'SHOPIFY',
        name: 'Shopify',
        matchValue: 'Shopify',
        aliases: ['Shopify', 'SHOPIFY'],
        mcc: '5734',
        jarKey: financialFreedom,
        categoryTemplateKey: 'BUSINESS',
        logoDomain: 'shopify.com',
        website: 'https://shopify.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BOL_PARTNER',
        name: 'Bol Partner',
        matchValue: 'Bol Partner',
        aliases: ['Bol Partner', 'bol.com partner', 'Bol.com Retailer'],
        mcc: '5399',
        jarKey: financialFreedom,
        categoryTemplateKey: 'BUSINESS',
        logoDomain: 'partner.bol.com',
        website: 'https://partner.bol.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'AMAZON_SELLER',
        name: 'Amazon Seller',
        matchValue: 'Amazon Seller',
        aliases: ['Amazon Seller', 'Amazon Services', 'AMZ*SELLER'],
        mcc: '5399',
        jarKey: financialFreedom,
        categoryTemplateKey: 'BUSINESS',
        logoDomain: 'sellercentral.amazon.nl',
        website: 'https://sellercentral.amazon.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'EXACT',
        name: 'Exact',
        matchValue: 'Exact',
        aliases: ['Exact Online', 'Exact', 'EXACT'],
        mcc: '5734',
        jarKey: financialFreedom,
        categoryTemplateKey: 'BUSINESS',
        logoDomain: 'exact.com',
        website: 'https://exact.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'MONEYBIRD',
        name: 'Moneybird',
        matchValue: 'Moneybird',
        aliases: ['Moneybird', 'MONEYBIRD'],
        mcc: '5734',
        jarKey: financialFreedom,
        categoryTemplateKey: 'BUSINESS',
        logoDomain: 'moneybird.nl',
        website: 'https://moneybird.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'WOOCOMMERCE',
        name: 'WooCommerce',
        matchValue: 'WooCommerce',
        aliases: ['WooCommerce', 'Woo '],
        mcc: '5734',
        jarKey: financialFreedom,
        categoryTemplateKey: 'BUSINESS',
        logoDomain: 'woocommerce.com',
        website: 'https://woocommerce.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];
