import type { MerchantSeed } from '../types';
import { play } from '../types';

/** gaming merchant presets */
export const GAMING_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'STEAM',
        name: 'Steam',
        matchValue: 'Steam',
        aliases: ['Steam', 'STEAM GAMES', 'Valve Steam'],
        mcc: '5816',
        jarKey: play,
        categoryTemplateKey: 'GAMING',
        logoDomain: 'steampowered.com',
        website: 'https://steampowered.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'PLAYSTATION',
        name: 'PlayStation',
        matchValue: 'PlayStation',
        aliases: ['PlayStation', 'PSN', 'Sony PlayStation'],
        mcc: '5816',
        jarKey: play,
        categoryTemplateKey: 'GAMING',
        logoDomain: 'playstation.com',
        website: 'https://playstation.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'XBOX',
        name: 'Xbox',
        matchValue: 'Xbox',
        aliases: ['Xbox', 'XBOX', 'Microsoft Xbox'],
        mcc: '5816',
        jarKey: play,
        categoryTemplateKey: 'GAMING',
        logoDomain: 'xbox.com',
        website: 'https://xbox.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 1,
        isActive: true,
    },
    {
        key: 'NINTENDO',
        name: 'Nintendo',
        matchValue: 'Nintendo',
        aliases: ['Nintendo', 'NINTENDO', 'eShop'],
        mcc: '5816',
        jarKey: play,
        categoryTemplateKey: 'GAMING',
        logoDomain: 'nintendo.com',
        website: 'https://nintendo.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'TWITCH',
        name: 'Twitch',
        matchValue: 'Twitch',
        aliases: ['Twitch', 'TWITCH'],
        mcc: '5816',
        jarKey: play,
        categoryTemplateKey: 'GAMING',
        logoDomain: 'twitch.tv',
        website: 'https://twitch.tv',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];
