import type { MerchantSeed } from '../types';
import { give } from '../types';

/** give merchant presets */
export const GIVE_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'GIRO555',
        name: 'Giro555',
        matchValue: 'Giro555',
        aliases: ['Giro555', 'GIRO 555', 'SHO Giro555'],
        mcc: '8398',
        jarKey: give,
        categoryTemplateKey: 'DONATIONS',
        logoDomain: 'giro555.nl',
        website: 'https://giro555.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'KWF',
        name: 'KWF',
        matchValue: 'KWF',
        aliases: ['KWF', 'KWF Kankerbestrijding'],
        mcc: '8398',
        jarKey: give,
        categoryTemplateKey: 'DONATIONS',
        logoDomain: 'kwf.nl',
        website: 'https://kwf.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'UNICEF',
        name: 'Unicef',
        matchValue: 'Unicef',
        aliases: ['Unicef', 'UNICEF NL', 'UNICEF Nederland'],
        mcc: '8398',
        jarKey: give,
        categoryTemplateKey: 'DONATIONS',
        logoDomain: 'unicef.nl',
        website: 'https://unicef.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'RODE_KRUIS',
        name: 'Rode Kruis',
        matchValue: 'Rode Kruis',
        aliases: ['Rode Kruis', 'Nederlandse Rode Kruis', 'Red Cross NL'],
        mcc: '8398',
        jarKey: give,
        categoryTemplateKey: 'DONATIONS',
        logoDomain: 'rodekruis.nl',
        website: 'https://rodekruis.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'AMNESTY',
        name: 'Amnesty International',
        matchValue: 'Amnesty',
        aliases: ['Amnesty', 'Amnesty International', 'AMNESTY'],
        mcc: '8398',
        jarKey: give,
        categoryTemplateKey: 'DONATIONS',
        logoDomain: 'amnesty.nl',
        website: 'https://amnesty.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'WERELD_NATUUR_FONDS',
        name: 'WWF / WNF',
        matchValue: 'Wereld Natuur Fonds',
        aliases: ['Wereld Natuur Fonds', 'WNF', 'WWF NL', 'WWF'],
        mcc: '8398',
        jarKey: give,
        categoryTemplateKey: 'DONATIONS',
        logoDomain: 'wnf.nl',
        website: 'https://wnf.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'GREENPEACE',
        name: 'Greenpeace',
        matchValue: 'Greenpeace',
        aliases: ['Greenpeace', 'GREENPEACE NL'],
        mcc: '8398',
        jarKey: give,
        categoryTemplateKey: 'DONATIONS',
        logoDomain: 'greenpeace.nl',
        website: 'https://greenpeace.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ARTSEN_ZONDER_GRENZEN',
        name: 'Artsen zonder Grenzen',
        matchValue: 'Artsen zonder Grenzen',
        aliases: ['Artsen zonder Grenzen', 'MSF', 'Médecins Sans Frontières'],
        mcc: '8398',
        jarKey: give,
        categoryTemplateKey: 'DONATIONS',
        logoDomain: 'artsenzondergrenzen.nl',
        website: 'https://artsenzondergrenzen.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'LEGER_DES_HEILS',
        name: 'Leger des Heils',
        matchValue: 'Leger des Heils',
        aliases: ['Leger des Heils', 'Salvation Army NL'],
        mcc: '8398',
        jarKey: give,
        categoryTemplateKey: 'DONATIONS',
        logoDomain: 'legerdesheils.nl',
        website: 'https://legerdesheils.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'PLAN_INTERNATIONAL',
        name: 'Plan International',
        matchValue: 'Plan International',
        aliases: ['Plan International', 'Plan Nederland', 'PLAN NL'],
        mcc: '8398',
        jarKey: give,
        categoryTemplateKey: 'DONATIONS',
        logoDomain: 'planinternational.nl',
        website: 'https://planinternational.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'OXFAM_NOVIB',
        name: 'Oxfam Novib',
        matchValue: 'Oxfam Novib',
        aliases: ['Oxfam Novib', 'OXFAM', 'Novib'],
        mcc: '8398',
        jarKey: give,
        categoryTemplateKey: 'DONATIONS',
        logoDomain: 'oxfamnovib.nl',
        website: 'https://oxfamnovib.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BLOOMON',
        name: 'Bloomon',
        matchValue: 'Bloomon',
        aliases: ['Bloomon', 'BLOOMON'],
        mcc: '5992',
        jarKey: give,
        categoryTemplateKey: 'GIFTS',
        logoDomain: 'bloomon.nl',
        website: 'https://bloomon.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BLOEMEN_BUREAU',
        name: 'Bloemenbureau',
        matchValue: 'Bloemen',
        aliases: ['Bloemenbureau', 'Bloemen.nl', 'Flower Company'],
        mcc: '5992',
        jarKey: give,
        categoryTemplateKey: 'GIFTS',
        logoDomain: 'bloemen.nl',
        website: 'https://bloemen.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'GIFT_CARD_NL',
        name: 'VVV Cadeaukaart',
        matchValue: 'VVV Cadeaukaart',
        aliases: ['VVV Cadeaukaart', 'VVV Giftcard', 'Nationale Cadeaukaart'],
        mcc: '5947',
        jarKey: give,
        categoryTemplateKey: 'GIFTS',
        logoDomain: 'vvvcadeaukaarten.nl',
        website: 'https://vvvcadeaukaarten.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BOL_CADEAU',
        name: 'bol.com cadeau',
        matchValue: 'bol.com cadeau',
        aliases: ['bol.com cadeau', 'Bol cadeaukaart', 'bol cadeau'],
        mcc: '5947',
        jarKey: give,
        categoryTemplateKey: 'GIFTS',
        logoDomain: 'bol.com',
        website: 'https://bol.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'RITUALS',
        name: 'Rituals',
        matchValue: 'Rituals',
        aliases: ['Rituals', 'RITUALS'],
        mcc: '5977',
        jarKey: give,
        categoryTemplateKey: 'GIFTS',
        logoDomain: 'rituals.com',
        website: 'https://rituals.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];
