import type { MerchantSeed } from '../types';
import { give } from '../types';

/**
 * Give-jar merchants.
 *
 * DONATIONS = payees we surface on Help me choose. Keep this list short and
 * high-trust only: Doneer Effectief / GiveWell / ACE / Giving Green picks, or
 * CBF-erkend NL orgs with public annual impact reporting. No padding with
 * celebrity brands that lack an independent check. “I know who” is free text.
 *
 * GIFTS = flowers / cards (not charities) — bank matching only.
 */
function donation(row: Omit<MerchantSeed, 'jarKey' | 'categoryTemplateKey' | 'mcc'>): MerchantSeed {
    return {
        ...row,
        mcc: '8398',
        jarKey: give,
        categoryTemplateKey: 'DONATIONS',
        highlight: row.highlight ?? null,
        markets: row.markets ?? ['NL'],
        matchPriority: row.matchPriority ?? 0,
        isActive: row.isActive ?? true,
    };
}

/** give merchant presets */
export const GIVE_MERCHANTS: readonly MerchantSeed[] = [
    // ── Evidence-backed (Coach-aligned) ────────────────────────────────────
    donation({
        key: 'DONEER_EFFECTIEF',
        name: 'Doneer Effectief',
        matchValue: 'Doneer Effectief',
        aliases: ['Doneer Effectief', 'DONEER EFFECTIEF', 'DoneerEffectief'],
        logoDomain: 'doneereffectief.nl',
        website: 'https://doneereffectief.nl',
        highlight: 'FEATURED',
        matchPriority: 20,
    }),
    donation({
        key: 'AGAINST_MALARIA_FOUNDATION',
        name: 'Against Malaria Foundation',
        matchValue: 'Against Malaria',
        aliases: ['Against Malaria Foundation', 'AMF', 'Against Malaria'],
        logoDomain: 'againstmalaria.com',
        website: 'https://www.againstmalaria.com',
        highlight: 'FEATURED',
        matchPriority: 18,
    }),
    donation({
        key: 'GIVEDIRECTLY',
        name: 'GiveDirectly',
        matchValue: 'GiveDirectly',
        aliases: ['GiveDirectly', 'GIVE DIRECTLY'],
        logoDomain: 'givedirectly.org',
        website: 'https://www.givedirectly.org',
        highlight: 'FEATURED',
        matchPriority: 18,
    }),
    donation({
        key: 'HELEN_KELLER_INTL',
        name: 'Helen Keller Intl',
        matchValue: 'Helen Keller',
        aliases: ['Helen Keller Intl', 'Helen Keller International', 'HKI'],
        logoDomain: 'helenkellerintl.org',
        website: 'https://helenkellerintl.org',
        matchPriority: 16,
    }),
    donation({
        key: 'NEW_INCENTIVES',
        name: 'New Incentives',
        matchValue: 'New Incentives',
        aliases: ['New Incentives'],
        logoDomain: 'newincentives.org',
        website: 'https://www.newincentives.org',
        matchPriority: 16,
    }),
    donation({
        key: 'STRONGMINDS',
        name: 'StrongMinds',
        matchValue: 'StrongMinds',
        aliases: ['StrongMinds', 'Strong Minds'],
        logoDomain: 'strongminds.org',
        website: 'https://strongminds.org',
        matchPriority: 16,
    }),
    donation({
        key: 'CLEAN_AIR_TASK_FORCE',
        name: 'Clean Air Task Force',
        matchValue: 'Clean Air Task Force',
        aliases: ['Clean Air Task Force', 'CATF'],
        logoDomain: 'catf.us',
        website: 'https://www.catf.us',
        matchPriority: 14,
    }),
    donation({
        key: 'THE_HUMANE_LEAGUE',
        name: 'The Humane League',
        matchValue: 'The Humane League',
        aliases: ['The Humane League', 'Humane League'],
        logoDomain: 'thehumaneleague.org',
        website: 'https://thehumaneleague.org',
        matchPriority: 14,
    }),
    donation({
        key: 'GOOD_FOOD_INSTITUTE',
        name: 'The Good Food Institute',
        matchValue: 'Good Food Institute',
        aliases: ['The Good Food Institute', 'Good Food Institute', 'GFI'],
        logoDomain: 'gfi.org',
        website: 'https://gfi.org',
        matchPriority: 14,
    }),
    donation({
        key: '100WEEKS',
        name: '100WEEKS',
        matchValue: '100WEEKS',
        aliases: ['100WEEKS', '100 Weeks', 'Honderd Weken'],
        logoDomain: '100weeks.nl',
        website: 'https://www.100weeks.nl',
        highlight: 'FEATURED',
        matchPriority: 15,
    }),

    // ── Transparent NL household names (CBF Erkend + public reporting) ─────
    donation({
        key: 'VOEDSELBANKEN_NEDERLAND',
        name: 'Voedselbanken Nederland',
        matchValue: 'Voedselbanken',
        aliases: ['Voedselbanken Nederland', 'Voedselbank', 'Voedselbanken'],
        logoDomain: 'voedselbankennederland.nl',
        website: 'https://voedselbankennederland.nl',
        matchPriority: 12,
    }),
    donation({
        key: 'STICHTING_VLUCHTELING',
        name: 'Stichting Vluchteling',
        matchValue: 'Stichting Vluchteling',
        aliases: ['Stichting Vluchteling', 'Vluchteling'],
        logoDomain: 'vluchteling.nl',
        website: 'https://www.vluchteling.nl',
        matchPriority: 12,
    }),
    donation({
        key: 'GIRO555',
        name: 'Giro555',
        matchValue: 'Giro555',
        aliases: ['Giro555', 'GIRO 555', 'SHO Giro555'],
        logoDomain: 'giro555.nl',
        website: 'https://giro555.nl',
        matchPriority: 10,
    }),
    donation({
        key: 'ARTSEN_ZONDER_GRENZEN',
        name: 'Artsen zonder Grenzen',
        matchValue: 'Artsen zonder Grenzen',
        aliases: ['Artsen zonder Grenzen', 'MSF', 'Médecins Sans Frontières'],
        logoDomain: 'artsenzondergrenzen.nl',
        website: 'https://artsenzondergrenzen.nl',
        matchPriority: 10,
    }),
    donation({
        key: 'RODE_KRUIS',
        name: 'Rode Kruis',
        matchValue: 'Rode Kruis',
        aliases: ['Rode Kruis', 'Nederlandse Rode Kruis', 'Red Cross NL'],
        logoDomain: 'rodekruis.nl',
        website: 'https://rodekruis.nl',
        matchPriority: 10,
    }),
    donation({
        key: 'UNICEF',
        name: 'Unicef',
        matchValue: 'Unicef',
        aliases: ['Unicef', 'UNICEF NL', 'UNICEF Nederland'],
        logoDomain: 'unicef.nl',
        website: 'https://unicef.nl',
        matchPriority: 8,
    }),
    donation({
        key: 'KWF',
        name: 'KWF',
        matchValue: 'KWF',
        aliases: ['KWF', 'KWF Kankerbestrijding'],
        logoDomain: 'kwf.nl',
        website: 'https://kwf.nl',
        matchPriority: 8,
    }),

    // ── Gifts (not charities) ──────────────────────────────────────────────
    {
        key: 'BLOOMON',
        name: 'Bloomon',
        matchValue: 'Bloomon',
        aliases: ['Bloomon', 'BLOOMON'],
        mcc: '5992',
        jarKey: give,
        categoryTemplateKey: 'GIFTS',
        logoDomain: 'bloomon.nl',
        website: 'https://bloomon.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BLOEMEN_BUREAU',
        name: 'Bloemenbureau',
        matchValue: 'Bloemen',
        aliases: ['Bloemenbureau', 'Bloemen.nl', 'Flower Company'],
        mcc: '5992',
        jarKey: give,
        categoryTemplateKey: 'GIFTS',
        logoDomain: 'bloemen.nl',
        website: 'https://bloemen.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'GIFT_CARD_NL',
        name: 'VVV Cadeaukaart',
        matchValue: 'VVV Cadeaukaart',
        aliases: ['VVV Cadeaukaart', 'VVV Giftcard', 'Nationale Cadeaukaart'],
        mcc: '5947',
        jarKey: give,
        categoryTemplateKey: 'GIFTS',
        logoDomain: 'vvvcadeaukaarten.nl',
        website: 'https://vvvcadeaukaarten.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BOL_CADEAU',
        name: 'bol.com cadeau',
        matchValue: 'bol.com cadeau',
        aliases: ['bol.com cadeau', 'Bol cadeaukaart', 'bol cadeau'],
        mcc: '5947',
        jarKey: give,
        categoryTemplateKey: 'GIFTS',
        logoDomain: 'bol.com',
        website: 'https://bol.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'RITUALS',
        name: 'Rituals',
        matchValue: 'Rituals',
        aliases: ['Rituals', 'RITUALS'],
        mcc: '5977',
        jarKey: give,
        categoryTemplateKey: 'GIFTS',
        logoDomain: 'rituals.com',
        website: 'https://rituals.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];
