import type { MerchantSeed } from '../types';
import { necessities } from '../types';

/** groceries merchant presets */
export const GROCERIES_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'ALBERT_HEIJN',
        name: 'Albert Heijn',
        matchValue: 'Albert Heijn',
        aliases: ['Albert Heijn', 'AH ', 'AH.nl', 'AH TO GO', 'AH to go'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
        logoDomain: 'ah.nl',
        website: 'https://ah.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'JUMBO',
        name: 'Jumbo',
        matchValue: 'Jumbo',
        aliases: ['Jumbo', 'JUMBO SUPERMARKT'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
        logoDomain: 'jumbo.com',
        website: 'https://jumbo.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'LIDL',
        name: 'Lidl',
        matchValue: 'Lidl',
        aliases: ['Lidl', 'LIDL NL'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
        logoDomain: 'lidl.nl',
        website: 'https://lidl.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'PLUS',
        name: 'PLUS',
        matchValue: 'PLUS',
        aliases: ['PLUS supermarket', 'Plus Supermarkt'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
        logoDomain: 'plus.nl',
        website: 'https://plus.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'DIRK',
        name: 'Dirk',
        matchValue: 'Dirk',
        aliases: ['Dirk', 'DIRK VAN DEN BROEK', 'Dirk vd Broek'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
        logoDomain: 'dirk.nl',
        website: 'https://dirk.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ALDI',
        name: 'Aldi',
        matchValue: 'Aldi',
        aliases: ['Aldi', 'ALDI NL', 'ALDI INKOOP'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
        logoDomain: 'aldi.nl',
        website: 'https://aldi.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'SPAR',
        name: 'Spar',
        matchValue: 'Spar',
        aliases: ['Spar', 'SPAR NL', 'SPAR CITY'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
        logoDomain: 'spar.nl',
        website: 'https://spar.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'CRISP',
        name: 'Crisp',
        matchValue: 'Crisp',
        aliases: ['Crisp', 'CRISP NL', 'Crisp B.V.'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
        logoDomain: 'crisp.nl',
        website: 'https://crisp.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'HELLOFRESH',
        name: 'HelloFresh',
        matchValue: 'HelloFresh',
        aliases: ['HelloFresh', 'HELLOFRESH', 'Hello Fresh'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
        logoDomain: 'hellofresh.nl',
        website: 'https://hellofresh.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'MARLEY_SPOON',
        name: 'Marley Spoon',
        matchValue: 'Marley Spoon',
        aliases: ['Marley Spoon', 'MARLEYSPOON', 'MarleySpoon'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
        logoDomain: 'marleyspoon.nl',
        website: 'https://marleyspoon.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'FOODBAG',
        name: 'Foodbag',
        matchValue: 'Foodbag',
        aliases: ['Foodbag', 'FOODBAG', 'Food Bag'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
        logoDomain: 'foodbag.nl',
        website: 'https://foodbag.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];
