import type { MerchantSeed } from '../types';
import { necessities } from '../types';

/** groceries merchant presets */
export const GROCERIES_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'ALBERT_HEIJN',
        name: 'Albert Heijn',
        matchValue: 'Albert Heijn',
        aliases: ['Albert Heijn', 'AH ', 'AH.nl', 'AH TO GO', 'AH to go'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
        logoDomain: 'ah.nl',
        website: 'https://ah.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'JUMBO',
        name: 'Jumbo',
        matchValue: 'Jumbo',
        aliases: ['Jumbo', 'JUMBO SUPERMARKT'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
        logoDomain: 'jumbo.com',
        website: 'https://jumbo.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'LIDL',
        name: 'Lidl',
        matchValue: 'Lidl',
        aliases: ['Lidl', 'LIDL NL'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
        logoDomain: 'lidl.nl',
        website: 'https://lidl.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'PLUS',
        name: 'PLUS',
        matchValue: 'PLUS',
        aliases: ['PLUS supermarket', 'Plus Supermarkt', 'Coop', 'COOP SUPERMARKT'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
        logoDomain: 'plus.nl',
        website: 'https://plus.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'DIRK',
        name: 'Dirk',
        matchValue: 'Dirk',
        aliases: ['Dirk', 'DIRK VAN DEN BROEK', 'Dirk vd Broek'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
        logoDomain: 'dirk.nl',
        website: 'https://dirk.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ALDI',
        name: 'Aldi',
        matchValue: 'Aldi',
        aliases: ['Aldi', 'ALDI NL', 'ALDI INKOOP'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
        logoDomain: 'aldi.nl',
        website: 'https://aldi.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'SPAR',
        name: 'Spar',
        matchValue: 'Spar',
        aliases: ['Spar', 'SPAR NL', 'SPAR CITY'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
        logoDomain: 'spar.nl',
        website: 'https://spar.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'DEKAMARKT',
        name: 'DekaMarkt',
        matchValue: 'DekaMarkt',
        aliases: ['DekaMarkt', 'Dekamarkt', 'DEKA MARKT', 'Deka Markt'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
        // www. — bare dekamarkt.nl often resolves to a tiny generic favicon
        logoDomain: 'www.dekamarkt.nl',
        website: 'https://www.dekamarkt.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'VOMAR',
        name: 'Vomar',
        matchValue: 'Vomar',
        aliases: ['Vomar', 'VOMAR', 'Vomar Voordeelmarkt'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
        logoDomain: 'vomar.nl',
        website: 'https://vomar.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'HOOGVLIET',
        name: 'Hoogvliet',
        matchValue: 'Hoogvliet',
        aliases: ['Hoogvliet', 'HOOGVLIET'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
        logoDomain: 'hoogvliet.nl',
        website: 'https://hoogvliet.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'NETTORAMA',
        name: 'Nettorama',
        matchValue: 'Nettorama',
        aliases: ['Nettorama', 'NETTORAMA', 'Boni'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
        logoDomain: 'nettorama.nl',
        website: 'https://nettorama.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'POIESZ',
        name: 'Poiesz',
        matchValue: 'Poiesz',
        aliases: ['Poiesz', 'POIESZ', 'Poiesz Supermarkten'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
        logoDomain: 'poiesz.nl',
        website: 'https://poiesz.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BOONS_MARKT',
        name: "Boon's Markt",
        matchValue: "Boon's Markt",
        aliases: ["Boon's Markt", 'Boons Markt', 'BOONS MARKT', 'Boon Food Group'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
        logoDomain: 'boonsmarkt.nl',
        website: 'https://boonsmarkt.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'PICNIC',
        name: 'Picnic',
        matchValue: 'Picnic',
        aliases: ['Picnic', 'PICNIC', 'Picnic Technologies'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
        logoDomain: 'picnic.nl',
        website: 'https://picnic.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'FLINK',
        name: 'Flink',
        matchValue: 'Flink',
        aliases: ['Flink', 'FLINK', 'GoFlink'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
        logoDomain: 'flink.nl',
        website: 'https://flink.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'GETIR',
        name: 'Getir',
        matchValue: 'Getir',
        aliases: ['Getir', 'GETIR', 'Getir BV'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
        logoDomain: 'getir.com',
        website: 'https://getir.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        // Left NL (2024) — keep for bank-feed matching on older rows
        isActive: true,
    },
    {
        key: 'GORILLAS',
        name: 'Gorillas',
        matchValue: 'Gorillas',
        aliases: ['Gorillas', 'GORILLAS', 'Gorillas Technologies'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
        logoDomain: 'gorillas.io',
        website: 'https://gorillas.io',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        // Acquired / left NL — keep for bank-feed matching
        isActive: true,
    },
    {
        key: 'ZAPP',
        name: 'Zapp',
        matchValue: 'Zapp',
        aliases: ['Zapp', 'ZAPP', 'Zapp Delivery'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
        logoDomain: 'zapp.com',
        website: 'https://zapp.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'UPFRONT',
        name: 'Upfront',
        matchValue: 'Upfront',
        aliases: ['Upfront', 'UPFRONT', 'UpFront', 'Upfront Foodstore'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
        logoDomain: 'upfront.nl',
        website: 'https://upfront.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ODIN',
        name: 'Odin',
        matchValue: 'Odin',
        aliases: ['Odin', 'ODIN', 'Odin Biologisch'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
        logoDomain: 'odin.nl',
        website: 'https://odin.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'AMAZING_ORIENTAL',
        name: 'Amazing Oriental',
        matchValue: 'Amazing Oriental',
        aliases: ['Amazing Oriental', 'AMAZING ORIENTAL', 'Oriental Group'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
        logoDomain: 'amazingoriental.com',
        website: 'https://amazingoriental.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'CRISP',
        name: 'Crisp',
        matchValue: 'Crisp',
        aliases: ['Crisp', 'CRISP NL', 'Crisp B.V.'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
        logoDomain: 'crisp.nl',
        website: 'https://crisp.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'HELLOFRESH',
        name: 'HelloFresh',
        matchValue: 'HelloFresh',
        aliases: ['HelloFresh', 'HELLOFRESH', 'Hello Fresh'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
        logoDomain: 'hellofresh.nl',
        website: 'https://hellofresh.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'MARLEY_SPOON',
        name: 'Marley Spoon',
        matchValue: 'Marley Spoon',
        aliases: ['Marley Spoon', 'MARLEYSPOON', 'MarleySpoon'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
        logoDomain: 'marleyspoon.nl',
        website: 'https://marleyspoon.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'FOODBAG',
        name: 'Foodbag',
        matchValue: 'Foodbag',
        aliases: ['Foodbag', 'FOODBAG', 'Food Bag'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
        logoDomain: 'foodbag.nl',
        website: 'https://foodbag.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'FACTURIJN',
        name: 'Facturijn',
        matchValue: 'Facturijn',
        aliases: ['Facturijn', 'FACTURIJN', 'HelloFresh Facturijn'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
        logoDomain: 'facturijn.nl',
        website: 'https://facturijn.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'TANGER',
        name: 'Tanger Supermarkten',
        matchValue: 'Tanger',
        aliases: ['Tanger', 'TANGER', 'Tanger Supermarkt'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
        logoDomain: 'tanger.nl',
        website: 'https://tanger.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'SAHAN',
        name: 'Sahan Supermarkt',
        matchValue: 'Sahan',
        aliases: ['Sahan', 'SAHAN', 'Sahan Supermarkt'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
        logoDomain: 'sahansupermarkt.nl',
        website: 'https://sahansupermarkt.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'SLIGRO',
        name: 'Sligro',
        matchValue: 'Sligro',
        aliases: ['Sligro', 'SLIGRO', 'Sligro Food Group'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
        logoDomain: 'sligro.nl',
        website: 'https://sligro.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'MAKRO',
        name: 'Makro',
        matchValue: 'Makro',
        aliases: ['Makro', 'MAKRO', 'Makro Nederland'],
        mcc: '5411',
        jarKey: necessities,
        categoryTemplateKey: 'GROCERIES',
        logoDomain: 'makro.nl',
        website: 'https://makro.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];
