import type { MerchantSeed } from '../types';
import { necessities } from '../types';

/** Web hosting, domains and email hosting (NL-first). */
export const HOSTING_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'TRANSIP',
        name: 'TransIP',
        matchValue: 'TransIP',
        aliases: ['TransIP', 'TRANSIP', 'TransIP B.V.'],
        mcc: '4816',
        jarKey: necessities,
        categoryTemplateKey: 'HOSTING',
        logoDomain: 'transip.nl',
        website: 'https://www.transip.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'HOSTNET',
        name: 'Hostnet',
        matchValue: 'Hostnet',
        aliases: ['Hostnet', 'HOSTNET', 'Hostnet B.V.'],
        mcc: '4816',
        jarKey: necessities,
        categoryTemplateKey: 'HOSTING',
        logoDomain: 'hostnet.nl',
        website: 'https://www.hostnet.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'VERSIO',
        name: 'Versio',
        matchValue: 'Versio',
        aliases: ['Versio', 'VERSIO', 'Versio.nl'],
        mcc: '4816',
        jarKey: necessities,
        categoryTemplateKey: 'HOSTING',
        logoDomain: 'versio.nl',
        website: 'https://www.versio.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ANTAGONIST',
        name: 'Antagonist',
        matchValue: 'Antagonist',
        aliases: ['Antagonist', 'ANTAGONIST'],
        mcc: '4816',
        jarKey: necessities,
        categoryTemplateKey: 'HOSTING',
        logoDomain: 'antagonist.nl',
        website: 'https://www.antagonist.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ONE_COM',
        name: 'one.com',
        matchValue: 'one.com',
        aliases: ['one.com', 'ONE.COM', 'One Com'],
        mcc: '4816',
        jarKey: necessities,
        categoryTemplateKey: 'HOSTING',
        logoDomain: 'one.com',
        website: 'https://www.one.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'STRATO',
        name: 'STRATO',
        matchValue: 'STRATO',
        aliases: ['STRATO', 'Strato', 'STRATO NL'],
        mcc: '4816',
        jarKey: necessities,
        categoryTemplateKey: 'HOSTING',
        logoDomain: 'strato.nl',
        website: 'https://www.strato.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'VIMEXX',
        name: 'Vimexx',
        matchValue: 'Vimexx',
        aliases: ['Vimexx', 'VIMEXX'],
        mcc: '4816',
        jarKey: necessities,
        categoryTemplateKey: 'HOSTING',
        logoDomain: 'vimexx.nl',
        website: 'https://www.vimexx.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'MIJNDOMEIN',
        name: 'Mijndomein',
        matchValue: 'Mijndomein',
        aliases: ['Mijndomein', 'MIJNDOMEIN', 'Mijn Domein'],
        mcc: '4816',
        jarKey: necessities,
        categoryTemplateKey: 'HOSTING',
        logoDomain: 'mijndomein.nl',
        website: 'https://www.mijndomein.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'CLOUDFLARE',
        name: 'Cloudflare',
        matchValue: 'Cloudflare',
        aliases: ['Cloudflare', 'CLOUDFLARE'],
        mcc: '4816',
        jarKey: necessities,
        categoryTemplateKey: 'HOSTING',
        logoDomain: 'cloudflare.com',
        website: 'https://www.cloudflare.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'VERCEL',
        name: 'Vercel',
        matchValue: 'Vercel',
        aliases: ['Vercel', 'VERCEL'],
        mcc: '4816',
        jarKey: necessities,
        categoryTemplateKey: 'HOSTING',
        logoDomain: 'vercel.com',
        website: 'https://vercel.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'RAILWAY',
        name: 'Railway',
        matchValue: 'Railway',
        aliases: ['Railway', 'RAILWAY', 'Railway.app', 'Railway.app Inc'],
        mcc: '4816',
        jarKey: necessities,
        categoryTemplateKey: 'HOSTING',
        logoDomain: 'railway.app',
        website: 'https://railway.app',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'NETLIFY',
        name: 'Netlify',
        matchValue: 'Netlify',
        aliases: ['Netlify', 'NETLIFY'],
        mcc: '4816',
        jarKey: necessities,
        categoryTemplateKey: 'HOSTING',
        logoDomain: 'netlify.com',
        website: 'https://www.netlify.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'HETZNER',
        name: 'Hetzner',
        matchValue: 'Hetzner',
        aliases: ['Hetzner', 'HETZNER', 'Hetzner Online'],
        mcc: '4816',
        jarKey: necessities,
        categoryTemplateKey: 'HOSTING',
        logoDomain: 'hetzner.com',
        website: 'https://www.hetzner.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'DIGITALOCEAN',
        name: 'DigitalOcean',
        matchValue: 'DigitalOcean',
        aliases: ['DigitalOcean', 'DIGITALOCEAN', 'DO '],
        mcc: '4816',
        jarKey: necessities,
        categoryTemplateKey: 'HOSTING',
        logoDomain: 'digitalocean.com',
        website: 'https://www.digitalocean.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'GOOGLE_WORKSPACE',
        name: 'Google Workspace',
        matchValue: 'Google Workspace',
        aliases: [
            'Google Workspace',
            'GOOGLE WORKSPACE',
            'G Suite',
            'GSUITE',
            'Google Workspace NL',
        ],
        mcc: '4816',
        jarKey: necessities,
        categoryTemplateKey: 'HOSTING',
        logoDomain: 'workspace.google.com',
        website: 'https://workspace.google.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'MICROSOFT_365',
        name: 'Microsoft 365',
        matchValue: 'Microsoft 365',
        aliases: ['Microsoft 365', 'MICROSOFT 365', 'Office 365', 'OFFICE 365', 'MS 365', 'M365'],
        mcc: '4816',
        jarKey: necessities,
        categoryTemplateKey: 'HOSTING',
        logoDomain: 'microsoft.com',
        website: 'https://www.microsoft.com/microsoft-365',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'PROTON_MAIL',
        name: 'Proton Mail',
        matchValue: 'Proton Mail',
        aliases: ['Proton Mail', 'ProtonMail', 'PROTON MAIL', 'Proton AG Mail'],
        mcc: '4816',
        jarKey: necessities,
        categoryTemplateKey: 'HOSTING',
        logoDomain: 'proton.me',
        website: 'https://proton.me/mail',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];
