import type { MerchantSeed } from '../types';
import { necessities } from '../types';

/** housing merchant presets */
export const HOUSING_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'VESTIA',
        name: 'Vestia',
        matchValue: 'Vestia',
        aliases: ['Vestia', 'VESTIA WONEN'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'vestia.nl',
        website: 'https://vestia.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'YOMERE',
        name: 'Ymere',
        matchValue: 'Ymere',
        aliases: ['Ymere', 'YMERE'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'ymere.nl',
        website: 'https://ymere.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ROCHDALE',
        name: 'Rochdale',
        matchValue: 'Rochdale',
        aliases: ['Rochdale', 'ROCHDALE'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'rochdale.nl',
        website: 'https://rochdale.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'EIGEN_HAARD',
        name: 'Eigen Haard',
        matchValue: 'Eigen Haard',
        aliases: ['Eigen Haard', 'EIGEN HAARD'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'eigenhaard.nl',
        website: 'https://eigenhaard.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'PORTAAL',
        name: 'Portaal',
        matchValue: 'Portaal',
        aliases: ['Portaal', 'PORTAAL'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'portaal.nl',
        website: 'https://portaal.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'STADGENOOT',
        name: 'Stadgenoot',
        matchValue: 'Stadgenoot',
        aliases: ['Stadgenoot', 'STADGENOOT'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'stadgenoot.nl',
        website: 'https://stadgenoot.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'DE_ALLIANTIE',
        name: 'de Alliantie',
        matchValue: 'de Alliantie',
        aliases: ['de Alliantie', 'De Alliantie', 'Alliantie'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'de-alliantie.nl',
        website: 'https://de-alliantie.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'DE_KEY',
        name: 'de Key',
        matchValue: 'de Key',
        aliases: ['de Key', 'De Key', 'Woningstichting de Key'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'dekey.nl',
        website: 'https://dekey.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'LIEVEN_DE_KEY',
        name: 'Lieven de Key',
        matchValue: 'Lieven de Key',
        aliases: ['Lieven de Key', 'Lieven De Key', 'LdK'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'lievendekey.nl',
        website: 'https://lievendekey.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'HAVENSTEDER',
        name: 'Havensteder',
        matchValue: 'Havensteder',
        aliases: ['Havensteder', 'HAVENSTEDER'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'havensteder.nl',
        website: 'https://havensteder.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'WOONBRON',
        name: 'Woonbron',
        matchValue: 'Woonbron',
        aliases: ['Woonbron', 'WOONBRON'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'woonbron.nl',
        website: 'https://woonbron.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'STAEDION',
        name: 'Staedion',
        matchValue: 'Staedion',
        aliases: ['Staedion', 'STAEDION'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'staedion.nl',
        website: 'https://staedion.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'WOONIN',
        name: 'Woonin',
        matchValue: 'Woonin',
        aliases: ['Woonin', 'Mitros', 'WOONIN'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'woonin.nl',
        website: 'https://woonin.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'WOONSTAD_ROTTERDAM',
        name: 'Woonstad Rotterdam',
        matchValue: 'Woonstad Rotterdam',
        aliases: ['Woonstad Rotterdam', 'Woonstad', 'WOONSTAD ROTTERDAM'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'woonstad-rotterdam.nl',
        website: 'https://woonstad-rotterdam.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'LEFIER',
        name: 'Lefier',
        matchValue: 'Lefier',
        aliases: ['Lefier', 'LEFIER'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'lefier.nl',
        website: 'https://lefier.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ACCOLADE',
        name: 'Accolade',
        matchValue: 'Accolade',
        aliases: ['Accolade', 'ACCOLADE', 'Accolade Wonen'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'accolade.nl',
        website: 'https://accolade.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'NIJESTEE',
        name: 'Nijestee',
        matchValue: 'Nijestee',
        aliases: ['Nijestee', 'NIJESTEE'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'nijestee.nl',
        website: 'https://nijestee.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'WOONBEDRIJF',
        name: 'Woonbedrijf',
        matchValue: 'Woonbedrijf',
        aliases: ['Woonbedrijf', 'WOONBEDRIJF'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'woonbedrijf.nl',
        website: 'https://woonbedrijf.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'WOONZORG',
        name: 'Woonzorg Nederland',
        matchValue: 'Woonzorg',
        aliases: ['Woonzorg', 'Woonzorg Nederland', 'WOONZORG'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'woonzorg.nl',
        website: 'https://woonzorg.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'HABION',
        name: 'Habion',
        matchValue: 'Habion',
        aliases: ['Habion', 'HABION'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'habion.nl',
        website: 'https://habion.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'PATRIMONIUM',
        name: 'Patrimonium',
        matchValue: 'Patrimonium',
        aliases: ['Patrimonium', 'PATRIMONIUM', 'Patrimonium Groningen'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'patrimonium.nl',
        website: 'https://patrimonium.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'IDEALIS',
        name: 'Idealis',
        matchValue: 'Idealis',
        aliases: ['Idealis', 'IDEALIS'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'idealis.nl',
        website: 'https://idealis.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'AREA',
        name: 'Area',
        matchValue: 'Area',
        aliases: ['Area', 'AREA', 'Area Wonen'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'area.nl',
        website: 'https://area.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'TRUDO',
        name: 'Trudo',
        matchValue: 'Trudo',
        aliases: ['Trudo', 'TRUDO'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'trudo.nl',
        website: 'https://trudo.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'WONEN_LIMBURG',
        name: 'Wonen Limburg',
        matchValue: 'Wonen Limburg',
        aliases: ['Wonen Limburg', 'WONEN LIMBURG'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'wonenlimburg.nl',
        website: 'https://wonenlimburg.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'DOMIJN',
        name: 'Domijn',
        matchValue: 'Domijn',
        aliases: ['Domijn', 'DOMIJN'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'domijn.nl',
        website: 'https://domijn.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'PARTEON',
        name: 'Parteon',
        matchValue: 'Parteon',
        aliases: ['Parteon', 'PARTEON'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'parteon.nl',
        website: 'https://parteon.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'DUDOK_WONEN',
        name: 'Dudok Wonen',
        matchValue: 'Dudok Wonen',
        aliases: ['Dudok Wonen', 'DUDOK WONEN', 'Dudok'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'dudokwonen.nl',
        website: 'https://dudokwonen.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'MOZAIEK_WONEN',
        name: 'Mozaïek Wonen',
        matchValue: 'Mozaïek Wonen',
        aliases: ['Mozaïek Wonen', 'Mozaiek Wonen', 'MOZAIEK WONEN'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'mozaiekwonen.nl',
        website: 'https://mozaiekwonen.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'WONINGNET',
        name: 'WoningNet',
        matchValue: 'WoningNet',
        aliases: ['WoningNet', 'Woningnet', 'WONINGNET'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'woningnet.nl',
        website: 'https://woningnet.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'FUNDA',
        name: 'Funda',
        matchValue: 'Funda',
        aliases: ['Funda', 'FUNDA'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'funda.nl',
        website: 'https://funda.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'PARARIUS',
        name: 'Pararius',
        matchValue: 'Pararius',
        aliases: ['Pararius', 'PARARIUS'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'pararius.nl',
        website: 'https://pararius.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'KAMERNET',
        name: 'Kamernet',
        matchValue: 'Kamernet',
        aliases: ['Kamernet', 'KAMERNET'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'kamernet.nl',
        website: 'https://kamernet.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'IKEA',
        name: 'IKEA',
        matchValue: 'IKEA',
        aliases: ['IKEA', 'IKEA NL', 'IKEA Nederland'],
        mcc: '5712',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'ikea.com',
        website: 'https://ikea.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'PRAXIS',
        name: 'Praxis',
        matchValue: 'Praxis',
        aliases: ['Praxis', 'PRAXIS'],
        mcc: '5200',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'praxis.nl',
        website: 'https://praxis.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'GAMMA',
        name: 'Gamma',
        matchValue: 'Gamma',
        aliases: ['Gamma', 'GAMMA'],
        mcc: '5200',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'gamma.nl',
        website: 'https://gamma.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'KARWEI',
        name: 'Karwei',
        matchValue: 'Karwei',
        aliases: ['Karwei', 'KARWEI'],
        mcc: '5200',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'karwei.nl',
        website: 'https://karwei.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'HORNBACH',
        name: 'Hornbach',
        matchValue: 'Hornbach',
        aliases: ['Hornbach', 'HORNBACH'],
        mcc: '5200',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'hornbach.nl',
        website: 'https://hornbach.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'LEEN_BAKKER',
        name: 'Leen Bakker',
        matchValue: 'Leen Bakker',
        aliases: ['Leen Bakker', 'LEEN BAKKER'],
        mcc: '5712',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'leenbakker.nl',
        website: 'https://leenbakker.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'KWANTUM',
        name: 'Kwantum',
        matchValue: 'Kwantum',
        aliases: ['Kwantum', 'KWANTUM'],
        mcc: '5712',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'kwantum.nl',
        website: 'https://kwantum.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'JYSK',
        name: 'JYSK',
        matchValue: 'JYSK',
        aliases: ['JYSK', 'Jysk'],
        mcc: '5712',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'jysk.nl',
        website: 'https://jysk.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'DUWO',
        name: 'DUWO',
        matchValue: 'DUWO',
        aliases: ['DUWO', 'DUWO Student Housing'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'duwo.nl',
        website: 'https://duwo.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'SSH',
        name: 'SSH',
        matchValue: 'SSH',
        aliases: ['SSH', 'SSH Student Housing', 'Stichting Studenten Huisvesting'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'sshxl.nl',
        website: 'https://sshxl.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'SHURGARD',
        name: 'Shurgard',
        matchValue: 'Shurgard',
        aliases: ['Shurgard', 'SHURGARD', 'Shurgard Self Storage'],
        mcc: '4225',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'shurgard.com',
        website: 'https://shurgard.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ALLSAFE',
        name: 'Allsafe',
        matchValue: 'Allsafe',
        aliases: ['Allsafe', 'ALLSAFE'],
        mcc: '4225',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'allsafe.nl',
        website: 'https://allsafe.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'EXTRA_SPACE',
        name: 'Extra Space Storage',
        matchValue: 'Extra Space',
        aliases: ['Extra Space Storage', 'ExtraSpace', 'Extra Space'],
        mcc: '4225',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'extraspace.nl',
        website: 'https://extraspace.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'MYSTORAGE',
        name: 'MyStorage',
        matchValue: 'MyStorage',
        aliases: ['MyStorage', 'MYSTORAGE'],
        mcc: '4225',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'mystorage.nl',
        website: 'https://mystorage.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];
