import type { MerchantSeed } from '../types';
import { necessities } from '../types';

/** housing merchant presets */
export const HOUSING_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'VESTIA',
        name: 'Vestia',
        matchValue: 'Vestia',
        aliases: ['Vestia', 'VESTIA WONEN'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'vestia.nl',
        website: 'https://vestia.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'YOMERE',
        name: 'Ymere',
        matchValue: 'Ymere',
        aliases: ['Ymere', 'YMERE'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'ymere.nl',
        website: 'https://ymere.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ROCHDALE',
        name: 'Rochdale',
        matchValue: 'Rochdale',
        aliases: ['Rochdale', 'ROCHDALE'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'rochdale.nl',
        website: 'https://rochdale.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'EIGEN_HAARD',
        name: 'Eigen Haard',
        matchValue: 'Eigen Haard',
        aliases: ['Eigen Haard', 'EIGEN HAARD'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'eigenhaard.nl',
        website: 'https://eigenhaard.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'PORTAAL',
        name: 'Portaal',
        matchValue: 'Portaal',
        aliases: ['Portaal', 'PORTAAL'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'portaal.nl',
        website: 'https://portaal.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'WONINGNET',
        name: 'WoningNet',
        matchValue: 'WoningNet',
        aliases: ['WoningNet', 'Woningnet', 'WONINGNET'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'woningnet.nl',
        website: 'https://woningnet.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'FUNDA',
        name: 'Funda',
        matchValue: 'Funda',
        aliases: ['Funda', 'FUNDA'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'funda.nl',
        website: 'https://funda.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'PARARIUS',
        name: 'Pararius',
        matchValue: 'Pararius',
        aliases: ['Pararius', 'PARARIUS'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'pararius.nl',
        website: 'https://pararius.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'KAMERNET',
        name: 'Kamernet',
        matchValue: 'Kamernet',
        aliases: ['Kamernet', 'KAMERNET'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'kamernet.nl',
        website: 'https://kamernet.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'IKEA',
        name: 'IKEA',
        matchValue: 'IKEA',
        aliases: ['IKEA', 'IKEA NL', 'IKEA Nederland'],
        mcc: '5712',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'ikea.com',
        website: 'https://ikea.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'PRAXIS',
        name: 'Praxis',
        matchValue: 'Praxis',
        aliases: ['Praxis', 'PRAXIS'],
        mcc: '5200',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'praxis.nl',
        website: 'https://praxis.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'GAMMA',
        name: 'Gamma',
        matchValue: 'Gamma',
        aliases: ['Gamma', 'GAMMA'],
        mcc: '5200',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'gamma.nl',
        website: 'https://gamma.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'KARWEI',
        name: 'Karwei',
        matchValue: 'Karwei',
        aliases: ['Karwei', 'KARWEI'],
        mcc: '5200',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'karwei.nl',
        website: 'https://karwei.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'HORNBACH',
        name: 'Hornbach',
        matchValue: 'Hornbach',
        aliases: ['Hornbach', 'HORNBACH'],
        mcc: '5200',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'hornbach.nl',
        website: 'https://hornbach.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'LEEN_BAKKER',
        name: 'Leen Bakker',
        matchValue: 'Leen Bakker',
        aliases: ['Leen Bakker', 'LEEN BAKKER'],
        mcc: '5712',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'leenbakker.nl',
        website: 'https://leenbakker.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'KWANTUM',
        name: 'Kwantum',
        matchValue: 'Kwantum',
        aliases: ['Kwantum', 'KWANTUM'],
        mcc: '5712',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'kwantum.nl',
        website: 'https://kwantum.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'JYSK',
        name: 'JYSK',
        matchValue: 'JYSK',
        aliases: ['JYSK', 'Jysk'],
        mcc: '5712',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'jysk.nl',
        website: 'https://jysk.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'DUWO',
        name: 'DUWO',
        matchValue: 'DUWO',
        aliases: ['DUWO', 'DUWO Student Housing'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'duwo.nl',
        website: 'https://duwo.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'SSH',
        name: 'SSH',
        matchValue: 'SSH',
        aliases: ['SSH', 'SSH Student Housing', 'Stichting Studenten Huisvesting'],
        mcc: '6513',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'sshxl.nl',
        website: 'https://sshxl.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'SHURGARD',
        name: 'Shurgard',
        matchValue: 'Shurgard',
        aliases: ['Shurgard', 'SHURGARD', 'Shurgard Self Storage'],
        mcc: '4225',
        jarKey: necessities,
        categoryTemplateKey: 'HOUSING',
        logoDomain: 'shurgard.com',
        website: 'https://shurgard.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];
