import type { MerchantSeed } from '../types';
import { necessities } from '../types';

/** insurance merchant presets */
export const INSURANCE_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'ACHMEA',
        name: 'Achmea',
        matchValue: 'Achmea',
        aliases: ['Achmea', 'ACHMEA BV'],
        mcc: '6300',
        jarKey: necessities,
        categoryTemplateKey: 'INSURANCE',
        logoDomain: 'achmea.nl',
        website: 'https://achmea.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'CENTRAAL_BEHEER',
        name: 'Centraal Beheer',
        matchValue: 'Centraal Beheer',
        aliases: ['Centraal Beheer', 'CENTRAAL BEHEER', 'CB Achmea'],
        mcc: '6300',
        jarKey: necessities,
        categoryTemplateKey: 'INSURANCE',
        logoDomain: 'centraalbeheer.nl',
        website: 'https://centraalbeheer.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 1,
        isActive: true,
    },
    {
        key: 'INTERPOLIS',
        name: 'Interpolis',
        matchValue: 'Interpolis',
        aliases: ['Interpolis', 'INTERPOLIS'],
        mcc: '6300',
        jarKey: necessities,
        categoryTemplateKey: 'INSURANCE',
        logoDomain: 'interpolis.nl',
        website: 'https://interpolis.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'OHRA',
        name: 'OHRA',
        matchValue: 'OHRA',
        aliases: ['OHRA', 'OHRA Verzekeringen'],
        mcc: '6300',
        jarKey: necessities,
        categoryTemplateKey: 'INSURANCE',
        logoDomain: 'ohra.nl',
        website: 'https://ohra.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ZILVEREN_KRUIS',
        name: 'Zilveren Kruis',
        matchValue: 'Zilveren Kruis',
        aliases: ['Zilveren Kruis', 'ZILVEREN KRUIS', 'ZK Achmea'],
        mcc: '6300',
        jarKey: necessities,
        categoryTemplateKey: 'INSURANCE',
        logoDomain: 'zilverenkruis.nl',
        website: 'https://zilverenkruis.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 1,
        isActive: true,
    },
    {
        key: 'VGZ',
        name: 'VGZ',
        matchValue: 'VGZ',
        aliases: ['VGZ', 'VGZ Zorgverzekeraar', 'Coöperatie VGZ'],
        mcc: '6300',
        jarKey: necessities,
        categoryTemplateKey: 'INSURANCE',
        logoDomain: 'vgz.nl',
        website: 'https://vgz.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'CZ',
        name: 'CZ',
        matchValue: 'CZ ',
        aliases: ['CZ ', 'CZ Groep', 'CZ Zorgverzekeringen'],
        mcc: '6300',
        jarKey: necessities,
        categoryTemplateKey: 'INSURANCE',
        logoDomain: 'cz.nl',
        website: 'https://cz.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'MENZIS',
        name: 'Menzis',
        matchValue: 'Menzis',
        aliases: ['Menzis', 'MENZIS', 'Anderzorg'],
        mcc: '6300',
        jarKey: necessities,
        categoryTemplateKey: 'INSURANCE',
        logoDomain: 'menzis.nl',
        website: 'https://menzis.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'FBTO',
        name: 'FBTO',
        matchValue: 'FBTO',
        aliases: ['FBTO', 'FBTO Verzekeringen'],
        mcc: '6300',
        jarKey: necessities,
        categoryTemplateKey: 'INSURANCE',
        logoDomain: 'fbto.nl',
        website: 'https://fbto.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'NN',
        name: 'Nationale-Nederlanden',
        matchValue: 'Nationale-Nederlanden',
        aliases: ['Nationale-Nederlanden', 'Nationale Nederlanden', 'NN ', 'NN Group'],
        mcc: '6300',
        jarKey: necessities,
        categoryTemplateKey: 'INSURANCE',
        logoDomain: 'nn.nl',
        website: 'https://nn.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'AEGON',
        name: 'Aegon',
        matchValue: 'Aegon',
        aliases: ['Aegon', 'AEGON', 'a.s.r. Aegon'],
        mcc: '6300',
        jarKey: necessities,
        categoryTemplateKey: 'INSURANCE',
        logoDomain: 'aegon.nl',
        website: 'https://aegon.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ASR',
        name: 'a.s.r.',
        matchValue: 'a.s.r.',
        aliases: ['a.s.r.', 'ASR Nederland', 'ASR Verzekeringen'],
        mcc: '6300',
        jarKey: necessities,
        categoryTemplateKey: 'INSURANCE',
        logoDomain: 'asr.nl',
        website: 'https://asr.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ALLIANZ',
        name: 'Allianz',
        matchValue: 'Allianz',
        aliases: ['Allianz', 'ALLIANZ NL', 'Allianz Nederland'],
        mcc: '6300',
        jarKey: necessities,
        categoryTemplateKey: 'INSURANCE',
        logoDomain: 'allianz.nl',
        website: 'https://allianz.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'UNIVE',
        name: 'Univé',
        matchValue: 'Univé',
        aliases: ['Univé', 'UNIVE', 'Unive'],
        mcc: '6300',
        jarKey: necessities,
        categoryTemplateKey: 'INSURANCE',
        logoDomain: 'unive.nl',
        website: 'https://unive.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'INSHARED',
        name: 'InShared',
        matchValue: 'InShared',
        aliases: ['InShared', 'INSHARED', 'inShared'],
        mcc: '6300',
        jarKey: necessities,
        categoryTemplateKey: 'INSURANCE',
        logoDomain: 'inshared.nl',
        website: 'https://inshared.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'DITZO',
        name: 'Ditzo',
        matchValue: 'Ditzo',
        aliases: ['Ditzo', 'DITZO'],
        mcc: '6300',
        jarKey: necessities,
        categoryTemplateKey: 'INSURANCE',
        logoDomain: 'ditzo.nl',
        website: 'https://ditzo.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'JUST',
        name: 'Just',
        matchValue: 'Just',
        aliases: ['Just ', 'Just Zorgverzekering', 'Just.nl'],
        mcc: '6300',
        jarKey: necessities,
        categoryTemplateKey: 'INSURANCE',
        logoDomain: 'just.nl',
        website: 'https://just.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ONVZ',
        name: 'ONVZ',
        matchValue: 'ONVZ',
        aliases: ['ONVZ', 'ONVZ Zorgverzekeraar'],
        mcc: '6300',
        jarKey: necessities,
        categoryTemplateKey: 'INSURANCE',
        logoDomain: 'onvz.nl',
        website: 'https://onvz.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ZORG_EN_ZEKERHEID',
        name: 'Zorg en Zekerheid',
        matchValue: 'Zorg en Zekerheid',
        aliases: ['Zorg en Zekerheid', 'Zorg&Zekerheid', 'ZEZ'],
        mcc: '6300',
        jarKey: necessities,
        categoryTemplateKey: 'INSURANCE',
        logoDomain: 'zorgenzekerheid.nl',
        website: 'https://zorgenzekerheid.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'SALLAND',
        name: 'Salland',
        matchValue: 'Salland',
        aliases: ['Salland', 'SALLAND', 'Salland Zorgverzekeringen'],
        mcc: '6300',
        jarKey: necessities,
        categoryTemplateKey: 'INSURANCE',
        logoDomain: 'salland.nl',
        website: 'https://salland.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'IZA',
        name: 'IZA',
        matchValue: 'IZA',
        aliases: ['IZA', 'IZA Zorgverzekeraar'],
        mcc: '6300',
        jarKey: necessities,
        categoryTemplateKey: 'INSURANCE',
        logoDomain: 'iza.nl',
        website: 'https://iza.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'UNITED_CONSUMERS',
        name: 'UnitedConsumers',
        matchValue: 'UnitedConsumers',
        aliases: ['UnitedConsumers', 'United Consumers', 'UC Verzekeringen'],
        mcc: '6300',
        jarKey: necessities,
        categoryTemplateKey: 'INSURANCE',
        logoDomain: 'unitedconsumers.com',
        website: 'https://unitedconsumers.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ANWB_VERZEKEREN',
        name: 'ANWB Verzekeren',
        matchValue: 'ANWB Verzekeren',
        aliases: ['ANWB Verzekeren', 'ANWB Verzekeringen'],
        mcc: '6300',
        jarKey: necessities,
        categoryTemplateKey: 'INSURANCE',
        logoDomain: 'anwb.nl',
        website: 'https://anwb.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 1,
        isActive: true,
    },
    {
        key: 'UNIGARANT',
        name: 'Unigarant',
        matchValue: 'Unigarant',
        aliases: ['Unigarant', 'UNIGARANT'],
        mcc: '6300',
        jarKey: necessities,
        categoryTemplateKey: 'INSURANCE',
        logoDomain: 'unigarant.nl',
        website: 'https://unigarant.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'HEMA_VERZEKERINGEN',
        name: 'HEMA Verzekeringen',
        matchValue: 'HEMA Verzekeringen',
        aliases: ['HEMA Verzekeringen', 'HEMA Verzekering'],
        mcc: '6300',
        jarKey: necessities,
        categoryTemplateKey: 'INSURANCE',
        logoDomain: 'hema.nl',
        website: 'https://hema.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'LEMONADE',
        name: 'Lemonade',
        matchValue: 'Lemonade',
        aliases: ['Lemonade', 'LEMONADE'],
        mcc: '6300',
        jarKey: necessities,
        categoryTemplateKey: 'INSURANCE',
        logoDomain: 'lemonade.com',
        website: 'https://lemonade.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'DE_GOUDSE',
        name: 'De Goudse',
        matchValue: 'De Goudse',
        aliases: ['De Goudse', 'Goudse Verzekeringen'],
        mcc: '6300',
        jarKey: necessities,
        categoryTemplateKey: 'INSURANCE',
        logoDomain: 'goudse.nl',
        website: 'https://goudse.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BOVEMIJ',
        name: 'Bovemij',
        matchValue: 'Bovemij',
        aliases: ['Bovemij', 'BOVEMIJ'],
        mcc: '6300',
        jarKey: necessities,
        categoryTemplateKey: 'INSURANCE',
        logoDomain: 'bovemij.nl',
        website: 'https://bovemij.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'TIPIQ',
        name: 'Tipiq',
        matchValue: 'Tipiq',
        aliases: ['Tipiq', 'TIPIQ', 'Tip!'],
        mcc: '6300',
        jarKey: necessities,
        categoryTemplateKey: 'INSURANCE',
        logoDomain: 'tipiq.nl',
        website: 'https://tipiq.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'PETPLAN',
        name: 'PetPlan',
        matchValue: 'PetPlan',
        aliases: ['PetPlan', 'PETPLAN', 'Petplan'],
        mcc: '6300',
        jarKey: necessities,
        categoryTemplateKey: 'INSURANCE',
        logoDomain: 'petplan.nl',
        website: 'https://petplan.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ARAG',
        name: 'ARAG',
        matchValue: 'ARAG',
        aliases: ['ARAG', 'ARAG Rechtsbijstand'],
        mcc: '6300',
        jarKey: necessities,
        categoryTemplateKey: 'INSURANCE',
        logoDomain: 'arag.nl',
        website: 'https://arag.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'DAS',
        name: 'DAS',
        matchValue: 'DAS',
        aliases: ['DAS', 'DAS Rechtsbijstand'],
        mcc: '6300',
        jarKey: necessities,
        categoryTemplateKey: 'INSURANCE',
        logoDomain: 'das.nl',
        website: 'https://das.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];
