import type { MerchantSeed } from '../types';
import { play } from '../types';

/** media merchant presets */
export const MEDIA_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'SPOTIFY',
        name: 'Spotify',
        matchValue: 'Spotify',
        aliases: ['Spotify', 'SPOTIFY AB', 'Spotify P', 'SPOTIFY*'],
        mcc: '4899',
        jarKey: play,
        categoryTemplateKey: 'MEDIA',
        logoDomain: 'spotify.com',
        website: 'https://spotify.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'NETFLIX',
        name: 'Netflix',
        matchValue: 'Netflix',
        aliases: ['Netflix', 'NETFLIX.COM', 'NETFLIX COM'],
        mcc: '4899',
        jarKey: play,
        categoryTemplateKey: 'MEDIA',
        logoDomain: 'netflix.com',
        website: 'https://netflix.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'DISNEY_PLUS',
        name: 'Disney+',
        matchValue: 'Disney',
        aliases: ['Disney+', 'Disney Plus', 'DISNEYPLUS', 'Disney*'],
        mcc: '4899',
        jarKey: play,
        categoryTemplateKey: 'MEDIA',
        logoDomain: 'disneyplus.com',
        website: 'https://disneyplus.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'VIAPLAY',
        name: 'Viaplay',
        matchValue: 'Viaplay',
        aliases: ['Viaplay', 'VIAPLAY', 'Viaplay NL'],
        mcc: '4899',
        jarKey: play,
        categoryTemplateKey: 'MEDIA',
        logoDomain: 'viaplay.com',
        website: 'https://viaplay.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'PRIME_VIDEO',
        name: 'Prime Video',
        matchValue: 'Prime Video',
        aliases: ['Prime Video', 'AMAZON PRIME', 'AmazonPrime', 'Prime Video*'],
        mcc: '4899',
        jarKey: play,
        categoryTemplateKey: 'MEDIA',
        logoDomain: 'primevideo.com',
        website: 'https://primevideo.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'YOUTUBE_PREMIUM',
        name: 'YouTube Premium',
        matchValue: 'YouTube',
        aliases: ['YouTube Premium', 'YOUTUBEPREMIUM', 'Google YouTube'],
        mcc: '4899',
        jarKey: play,
        categoryTemplateKey: 'MEDIA',
        logoDomain: 'youtube.com',
        website: 'https://youtube.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];
