import type { MerchantSeed } from '../types';
import { necessities } from '../types';

/** Optician — brillen / lenzen. */
export const OPTICIAN_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'PEARLE',
        name: 'Pearle',
        matchValue: 'Pearle',
        aliases: ['Pearle', 'PEARLE', 'Pearle Opticiens'],
        mcc: '8043',
        jarKey: necessities,
        categoryTemplateKey: 'OPTICIAN',
        logoDomain: 'pearle.nl',
        website: 'https://pearle.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'SPECSAVERS',
        name: 'Specsavers',
        matchValue: 'Specsavers',
        aliases: ['Specsavers', 'SPECSAVERS'],
        mcc: '8043',
        jarKey: necessities,
        categoryTemplateKey: 'OPTICIAN',
        logoDomain: 'specsavers.nl',
        website: 'https://specsavers.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'EYE_WISH',
        name: 'Eye Wish',
        matchValue: 'Eye Wish',
        aliases: ['Eye Wish', 'EyeWish', 'EYE WISH', 'Eye Wish Opticiens'],
        mcc: '8043',
        jarKey: necessities,
        categoryTemplateKey: 'OPTICIAN',
        logoDomain: 'eyewish.nl',
        website: 'https://eyewish.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'HANS_ANDERS',
        name: 'Hans Anders',
        matchValue: 'Hans Anders',
        aliases: ['Hans Anders', 'HANS ANDERS', 'HansAnders'],
        mcc: '8043',
        jarKey: necessities,
        categoryTemplateKey: 'OPTICIAN',
        logoDomain: 'hansanders.nl',
        website: 'https://hansanders.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];
