import type { MerchantSeed } from '../types';
import { necessities } from '../types';

/** pets merchant presets */
export const PETS_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'ZOO_PLUS',
        name: 'Zooplus',
        matchValue: 'Zooplus',
        aliases: ['Zooplus', 'ZOOPLUS', 'bitiba'],
        mcc: '5995',
        jarKey: necessities,
        categoryTemplateKey: 'PETS',
        logoDomain: 'zooplus.nl',
        website: 'https://zooplus.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'PETSPLANET',
        name: 'Pets Place',
        matchValue: 'Pets Place',
        aliases: ['Pets Place', 'PETS PLACE', 'PetsPlace'],
        mcc: '5995',
        jarKey: necessities,
        categoryTemplateKey: 'PETS',
        logoDomain: 'petsplace.nl',
        website: 'https://petsplace.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'AVI',
        name: 'Avi',
        matchValue: 'Avi',
        aliases: ['Avi', 'AVI Dierenwinkel'],
        mcc: '5995',
        jarKey: necessities,
        categoryTemplateKey: 'PETS',
        logoDomain: 'avi.nl',
        website: 'https://avi.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'WELKOOP',
        name: 'Welkoop',
        matchValue: 'Welkoop',
        aliases: ['Welkoop', 'WELKOOP'],
        mcc: '5995',
        jarKey: necessities,
        categoryTemplateKey: 'PETS',
        logoDomain: 'welkoop.nl',
        website: 'https://welkoop.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'MAXI_ZOO',
        name: 'Maxi Zoo',
        matchValue: 'Maxi Zoo',
        aliases: ['Maxi Zoo', 'MAXIZOO', 'MaxiZoo'],
        mcc: '5995',
        jarKey: necessities,
        categoryTemplateKey: 'PETS',
        logoDomain: 'maxizoo.nl',
        website: 'https://maxizoo.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'FRESSNAPF',
        name: 'Fressnapf',
        matchValue: 'Fressnapf',
        aliases: ['Fressnapf', 'FRESSNAPF'],
        mcc: '5995',
        jarKey: necessities,
        categoryTemplateKey: 'PETS',
        logoDomain: 'fressnapf.nl',
        website: 'https://fressnapf.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ANICURA',
        name: 'AniCura',
        matchValue: 'AniCura',
        aliases: ['AniCura', 'ANICURA'],
        mcc: '0742',
        jarKey: necessities,
        categoryTemplateKey: 'PETS',
        logoDomain: 'anicura.nl',
        website: 'https://anicura.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'IVC_EVIDENSIA',
        name: 'Evidensia',
        matchValue: 'Evidensia',
        aliases: ['Evidensia', 'EVIDENSIA', 'IVC Evidensia'],
        mcc: '0742',
        jarKey: necessities,
        categoryTemplateKey: 'PETS',
        logoDomain: 'evidensia.nl',
        website: 'https://evidensia.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];
