import type { MerchantSeed } from '../types';
import { necessities } from '../types';

/** Pharmacy — apotheek / prescription retail */
export const PHARMACY_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'APOTHEEK',
        name: 'Apotheek',
        matchValue: 'Apotheek',
        aliases: ['Apotheek', 'APOTHEEK', 'Service Apotheek'],
        mcc: '5912',
        jarKey: necessities,
        categoryTemplateKey: 'PHARMACY',
        logoDomain: 'apotheek.nl',
        website: 'https://apotheek.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'MEDIQ',
        name: 'Mediq',
        matchValue: 'Mediq',
        aliases: ['Mediq', 'MEDIQ'],
        mcc: '5912',
        jarKey: necessities,
        categoryTemplateKey: 'PHARMACY',
        logoDomain: 'mediq.com',
        website: 'https://mediq.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'CAK',
        name: 'CAK',
        matchValue: 'CAK',
        aliases: ['CAK', 'Centraal Administratie Kantoor'],
        mcc: '8099',
        jarKey: necessities,
        categoryTemplateKey: 'MEDICAL',
        logoDomain: 'cak.nl',
        website: 'https://cak.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'OPENUP',
        name: 'OpenUp',
        matchValue: 'OpenUp',
        aliases: ['OpenUp', 'OPENUP', 'Open Up'],
        mcc: '8099',
        jarKey: necessities,
        categoryTemplateKey: 'THERAPY',
        logoDomain: 'openup.com',
        website: 'https://openup.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];
