import type { MerchantSeed } from '../types';
import { necessities } from '../types';

/** Post & parcels — verzenden / ontvangen. */
export const POST_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'POSTNL',
        name: 'PostNL',
        matchValue: 'PostNL',
        aliases: ['PostNL', 'POSTNL', 'Post NL'],
        mcc: '9402',
        jarKey: necessities,
        categoryTemplateKey: 'POST',
        logoDomain: 'postnl.nl',
        website: 'https://postnl.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'DHL',
        name: 'DHL',
        matchValue: 'DHL',
        aliases: ['DHL', 'DHL Express', 'DHL Parcel'],
        mcc: '4215',
        jarKey: necessities,
        categoryTemplateKey: 'POST',
        logoDomain: 'dhl.nl',
        website: 'https://dhl.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'DPD',
        name: 'DPD',
        matchValue: 'DPD',
        aliases: ['DPD', 'DPD NL'],
        mcc: '4215',
        jarKey: necessities,
        categoryTemplateKey: 'POST',
        logoDomain: 'dpd.nl',
        website: 'https://dpd.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BUDBEE',
        name: 'Budbee',
        matchValue: 'Budbee',
        aliases: ['Budbee', 'BUDBEE'],
        mcc: '4215',
        jarKey: necessities,
        categoryTemplateKey: 'POST',
        logoDomain: 'budbee.com',
        website: 'https://budbee.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'UPS',
        name: 'UPS',
        matchValue: 'UPS',
        aliases: ['UPS', 'United Parcel Service'],
        mcc: '4215',
        jarKey: necessities,
        categoryTemplateKey: 'POST',
        logoDomain: 'ups.com',
        website: 'https://ups.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];
