import type { MerchantSeed } from '../types';
import { play } from '../types';

/** shopping merchant presets */
export const SHOPPING_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'BLOKKER',
        name: 'Blokker',
        matchValue: 'Blokker',
        aliases: ['Blokker', 'BLOKKER'],
        mcc: '5719',
        jarKey: play,
        categoryTemplateKey: 'SHOPPING',
        logoDomain: 'blokker.nl',
        website: 'https://blokker.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ACTION',
        name: 'Action',
        matchValue: 'Action',
        aliases: ['Action', 'ACTION NL'],
        mcc: '5331',
        jarKey: play,
        categoryTemplateKey: 'SHOPPING',
        logoDomain: 'action.nl',
        website: 'https://action.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'HEMA',
        name: 'HEMA',
        matchValue: 'HEMA',
        aliases: ['HEMA', 'HEMA NL'],
        mcc: '5311',
        jarKey: play,
        categoryTemplateKey: 'SHOPPING',
        logoDomain: 'hema.nl',
        website: 'https://hema.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BOL',
        name: 'bol.com',
        matchValue: 'bol.com',
        aliases: ['bol.com', 'BOL.COM', 'Bol Com', 'BOL COM BV'],
        mcc: '5399',
        jarKey: play,
        categoryTemplateKey: 'SHOPPING',
        logoDomain: 'bol.com',
        website: 'https://bol.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'AMAZON',
        name: 'Amazon',
        matchValue: 'Amazon',
        aliases: ['Amazon', 'AMAZON EU', 'AMZN', 'Amazon.nl', 'AMAZON PAYMENTS'],
        mcc: '5399',
        jarKey: play,
        categoryTemplateKey: 'SHOPPING',
        logoDomain: 'amazon.nl',
        website: 'https://amazon.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'TEMU',
        name: 'Temu',
        matchValue: 'Temu',
        aliases: ['Temu', 'TEMU', 'TEMU.COM'],
        mcc: '5311',
        jarKey: play,
        categoryTemplateKey: 'SHOPPING',
        logoDomain: 'temu.com',
        website: 'https://temu.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ALIEXPRESS',
        name: 'AliExpress',
        matchValue: 'AliExpress',
        aliases: ['AliExpress', 'ALIEXPRESS', 'Alibaba AliExpress'],
        mcc: '5311',
        jarKey: play,
        categoryTemplateKey: 'SHOPPING',
        logoDomain: 'aliexpress.com',
        website: 'https://aliexpress.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'MARKTPLAATS',
        name: 'Marktplaats',
        matchValue: 'Marktplaats',
        aliases: ['Marktplaats', 'MARKTPLAATS', 'MP '],
        mcc: '5999',
        jarKey: play,
        categoryTemplateKey: 'SHOPPING',
        logoDomain: 'marktplaats.nl',
        website: 'https://marktplaats.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'VINTED',
        name: 'Vinted',
        matchValue: 'Vinted',
        aliases: ['Vinted', 'VINTED'],
        mcc: '5699',
        jarKey: play,
        categoryTemplateKey: 'SHOPPING',
        logoDomain: 'vinted.nl',
        website: 'https://vinted.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];
