import type { MerchantSeed } from '../types';
import { play } from '../types';

/**
 * Spa & massage — optional chain chips; local therapists are free-typed.
 * MCC 7297 = spa; 7298 = health & beauty services.
 */
export const SPA_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'THERMEN',
        name: 'Thermen',
        matchValue: 'Thermen',
        aliases: ['Thermen', 'THERMEN', 'Thermen Soesterberg', 'Thermen Berendonck'],
        mcc: '7297',
        jarKey: play,
        categoryTemplateKey: 'SPA',
        logoDomain: 'thermen.nl',
        website: 'https://thermen.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'SAUNA_DECO',
        name: 'Sauna Deco',
        matchValue: 'Sauna Deco',
        aliases: ['Sauna Deco', 'SaunaDeco', 'SAUNA DECO'],
        mcc: '7297',
        jarKey: play,
        categoryTemplateKey: 'SPA',
        logoDomain: 'saunadeco.nl',
        website: 'https://saunadeco.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'MASSAGE_EASY',
        name: 'Massage Easy',
        matchValue: 'Massage Easy',
        aliases: ['Massage Easy', 'MassageEasy', 'MASSAGE EASY'],
        mcc: '7298',
        jarKey: play,
        categoryTemplateKey: 'SPA',
        logoDomain: 'massageeasy.nl',
        website: 'https://massageeasy.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'THE_MASSAGE_COMPANY',
        name: 'The Massage Company',
        matchValue: 'The Massage Company',
        aliases: ['The Massage Company', 'Massage Company', 'THE MASSAGE COMPANY'],
        mcc: '7298',
        jarKey: play,
        categoryTemplateKey: 'SPA',
        logoDomain: 'themassagecompany.nl',
        website: 'https://themassagecompany.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BODY_AND_MIND',
        name: 'Body & Mind',
        matchValue: 'Body & Mind',
        aliases: ['Body & Mind', 'Body and Mind', 'BODY AND MIND'],
        mcc: '7298',
        jarKey: play,
        categoryTemplateKey: 'SPA',
        logoDomain: 'bodyandmind.nl',
        website: 'https://bodyandmind.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];
