import type { MerchantSeed } from '../types';
import { play } from '../types';

/** sport merchant presets */
export const SPORT_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'BASIC_FIT',
        name: 'Basic-Fit',
        matchValue: 'Basic-Fit',
        aliases: ['Basic-Fit', 'Basic Fit', 'BASICFIT', 'BasicFit'],
        mcc: '7997',
        jarKey: play,
        categoryTemplateKey: 'SPORT',
        logoDomain: 'basic-fit.com',
        website: 'https://basic-fit.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'SPORTCITY',
        name: 'SportCity',
        matchValue: 'SportCity',
        aliases: ['SportCity', 'SPORTCITY', 'Sport City'],
        mcc: '7997',
        jarKey: play,
        categoryTemplateKey: 'SPORT',
        logoDomain: 'sportcity.nl',
        website: 'https://sportcity.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'FIT_FOR_FREE',
        name: 'Fit For Free',
        matchValue: 'Fit For Free',
        aliases: ['Fit For Free', 'FIT FOR FREE', 'FitForFree'],
        mcc: '7997',
        jarKey: play,
        categoryTemplateKey: 'SPORT',
        logoDomain: 'fitforfree.nl',
        website: 'https://fitforfree.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ORANJE_FITNESS',
        name: 'Orangefitness',
        matchValue: 'Orangefitness',
        aliases: ['Orangefitness', 'Orange Fitness', 'ORANGEFITNESS'],
        mcc: '7997',
        jarKey: play,
        categoryTemplateKey: 'SPORT',
        logoDomain: 'orangefitness.nl',
        website: 'https://orangefitness.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'TRAINMORE',
        name: 'TrainMore',
        matchValue: 'TrainMore',
        aliases: ['TrainMore', 'TRAINMORE', 'Train More'],
        mcc: '7997',
        jarKey: play,
        categoryTemplateKey: 'SPORT',
        logoDomain: 'trainmore.nl',
        website: 'https://trainmore.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'CLUBSPORTIVE',
        name: 'ClubSportive',
        matchValue: 'ClubSportive',
        aliases: ['ClubSportive', 'Club Sportive', 'CLUBSPORTIVE'],
        mcc: '7997',
        jarKey: play,
        categoryTemplateKey: 'SPORT',
        logoDomain: 'clubsportive.nl',
        website: 'https://clubsportive.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ANYTIME_FITNESS',
        name: 'Anytime Fitness',
        matchValue: 'Anytime Fitness',
        aliases: ['Anytime Fitness', 'ANYTIME FITNESS'],
        mcc: '7997',
        jarKey: play,
        categoryTemplateKey: 'SPORT',
        logoDomain: 'anytimefitness.nl',
        website: 'https://anytimefitness.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'SNAP_FITNESS',
        name: 'Snap Fitness',
        matchValue: 'Snap Fitness',
        aliases: ['Snap Fitness', 'SNAP FITNESS'],
        mcc: '7997',
        jarKey: play,
        categoryTemplateKey: 'SPORT',
        logoDomain: 'snapfitness.nl',
        website: 'https://snapfitness.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'DAVID_LLOYD',
        name: 'David Lloyd',
        matchValue: 'David Lloyd',
        aliases: ['David Lloyd', 'DAVID LLOYD'],
        mcc: '7997',
        jarKey: play,
        categoryTemplateKey: 'SPORT',
        logoDomain: 'davidlloyd.nl',
        website: 'https://davidlloyd.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'OPTISPORT',
        name: 'Optisport',
        matchValue: 'Optisport',
        aliases: ['Optisport', 'OPTISPORT'],
        mcc: '7997',
        jarKey: play,
        categoryTemplateKey: 'SPORT',
        logoDomain: 'optisport.nl',
        website: 'https://optisport.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'DECATHLON',
        name: 'Decathlon',
        matchValue: 'Decathlon',
        aliases: ['Decathlon', 'DECATHLON NL'],
        mcc: '5941',
        jarKey: play,
        categoryTemplateKey: 'SPORT',
        logoDomain: 'decathlon.nl',
        website: 'https://decathlon.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'INTERSPORT',
        name: 'Intersport',
        matchValue: 'Intersport',
        aliases: ['Intersport', 'INTERSPORT'],
        mcc: '5941',
        jarKey: play,
        categoryTemplateKey: 'SPORT',
        logoDomain: 'intersport.nl',
        website: 'https://intersport.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'AKTIESPORT',
        name: 'Aktiesport',
        matchValue: 'Aktiesport',
        aliases: ['Aktiesport', 'AKTIESPORT'],
        mcc: '5941',
        jarKey: play,
        categoryTemplateKey: 'SPORT',
        logoDomain: 'aktiesport.nl',
        website: 'https://aktiesport.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BEVER',
        name: 'Bever',
        matchValue: 'Bever',
        aliases: ['Bever', 'BEVER'],
        mcc: '5941',
        jarKey: play,
        categoryTemplateKey: 'SPORT',
        logoDomain: 'bever.nl',
        website: 'https://bever.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'NIKE',
        name: 'Nike',
        matchValue: 'Nike',
        aliases: ['Nike', 'NIKE', 'Nike Store'],
        mcc: '5661',
        jarKey: play,
        categoryTemplateKey: 'SPORT',
        logoDomain: 'nike.com',
        website: 'https://nike.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ADIDAS',
        name: 'Adidas',
        matchValue: 'Adidas',
        aliases: ['Adidas', 'ADIDAS'],
        mcc: '5661',
        jarKey: play,
        categoryTemplateKey: 'SPORT',
        logoDomain: 'adidas.nl',
        website: 'https://adidas.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'PURE_GYM',
        name: 'PureGym',
        matchValue: 'PureGym',
        aliases: ['PureGym', 'Pure Gym', 'PUREGYM'],
        mcc: '7997',
        jarKey: play,
        categoryTemplateKey: 'SPORT',
        logoDomain: 'puregym.com',
        website: 'https://puregym.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'FIT20',
        name: 'Fit20',
        matchValue: 'Fit20',
        aliases: ['Fit20', 'FIT20', 'Fit 20'],
        mcc: '7997',
        jarKey: play,
        categoryTemplateKey: 'SPORT',
        logoDomain: 'fit20.nl',
        website: 'https://fit20.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];
