import type { MerchantSeed } from '../types';
import { necessities } from '../types';

/** Telco / ISP — internet & mobile bills. */
const TELCO_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'VODAFONE',
        name: 'Vodafone',
        matchValue: 'Vodafone',
        aliases: ['Vodafone', 'VODAFONE NL'],
        mcc: '4814',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'vodafone.nl',
        website: 'https://vodafone.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'KPN',
        name: 'KPN',
        matchValue: 'KPN',
        aliases: ['KPN', 'KPN BV', 'KPN Mobiel'],
        mcc: '4814',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'kpn.com',
        website: 'https://kpn.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ZIGGO',
        name: 'Ziggo',
        matchValue: 'Ziggo',
        aliases: ['Ziggo', 'ZIGGO BV'],
        mcc: '4899',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'ziggo.nl',
        website: 'https://ziggo.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ODIDO',
        name: 'Odido',
        matchValue: 'Odido',
        aliases: ['Odido', 'ODIDO', 'T-Mobile NL', 'T-Mobile Netherlands', 'Tele2 NL'],
        mcc: '4814',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'odido.nl',
        website: 'https://odido.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'LEBARA',
        name: 'Lebara',
        matchValue: 'Lebara',
        aliases: ['Lebara', 'LEBARA', 'Lebara Mobile'],
        mcc: '4814',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'lebara.nl',
        website: 'https://lebara.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'LYCAMOBILE',
        name: 'Lycamobile',
        matchValue: 'Lycamobile',
        aliases: ['Lycamobile', 'LYCAMOBILE', 'Lyca Mobile'],
        mcc: '4814',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'lycamobile.nl',
        website: 'https://lycamobile.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'SIMYO',
        name: 'Simyo',
        matchValue: 'Simyo',
        aliases: ['Simyo', 'SIMYO'],
        mcc: '4814',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'simyo.nl',
        website: 'https://simyo.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BEN',
        name: 'Ben',
        matchValue: 'Ben',
        aliases: ['Ben', 'BEN Mobiel', 'Ben.nl', 'Ben Mobile'],
        mcc: '4814',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'ben.nl',
        website: 'https://ben.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'YOUFONE',
        name: 'Youfone',
        matchValue: 'Youfone',
        aliases: ['Youfone', 'YOUFONE', 'Youfone Mobiel'],
        mcc: '4814',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'youfone.nl',
        website: 'https://youfone.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'SIMPEL',
        name: 'Simpel',
        matchValue: 'Simpel',
        aliases: ['Simpel', 'SIMPEL', 'Simpel Mobiel'],
        mcc: '4814',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'simpel.nl',
        website: 'https://simpel.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'HOLLANDSNIEUWE',
        name: 'hollandsnieuwe',
        matchValue: 'hollandsnieuwe',
        aliases: ['hollandsnieuwe', 'Hollandsnieuwe', 'Hollands Nieuwe'],
        mcc: '4814',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'hollandsnieuwe.nl',
        website: 'https://hollandsnieuwe.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BUDGET_MOBIEL',
        name: 'Budget Mobiel',
        matchValue: 'Budget Mobiel',
        aliases: ['Budget Mobiel', 'BUDGET MOBIEL', 'BudgetMobile'],
        mcc: '4814',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'budgetmobiel.nl',
        website: 'https://budgetmobiel.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'AH_MOBIEL',
        name: 'AH Mobiel',
        matchValue: 'AH Mobiel',
        aliases: ['AH Mobiel', 'Albert Heijn Mobiel', 'AH Mobiel', 'AH Mobile'],
        mcc: '4814',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'ah.nl',
        website: 'https://www.ah.nl/over-ah/ah-mobiel',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ORTEL',
        name: 'Ortel Mobile',
        matchValue: 'Ortel',
        aliases: ['Ortel', 'Ortel Mobile', 'ORTEL'],
        mcc: '4814',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'ortelmobile.nl',
        website: 'https://ortelmobile.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ROBIN_MOBILE',
        name: 'Robin Mobile',
        matchValue: 'Robin Mobile',
        aliases: ['Robin Mobile', 'ROBIN MOBILE', 'RobinMobile'],
        mcc: '4814',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'robinmobile.nl',
        website: 'https://robinmobile.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'FIFTYPLUS_MOBIEL',
        name: '50plusMobiel',
        matchValue: '50plusMobiel',
        aliases: ['50plusMobiel', '50+ Mobiel', '50 plus mobiel', '50PLUSMOBIEL'],
        mcc: '4814',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: '50plusmobiel.nl',
        website: 'https://50plusmobiel.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'SPEYD',
        name: 'Speyd',
        matchValue: 'Speyd',
        aliases: ['Speyd', 'SPEYD'],
        mcc: '4814',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'speyd.nl',
        website: 'https://speyd.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'MOBILE_VIKINGS',
        name: 'Mobile Vikings',
        matchValue: 'Mobile Vikings',
        aliases: ['Mobile Vikings', 'MOBILE VIKINGS'],
        mcc: '4814',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'mobilevikings.nl',
        website: 'https://mobilevikings.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    // ISPs
    {
        key: 'DELTA',
        name: 'Delta',
        matchValue: 'Delta',
        aliases: ['Delta', 'Delta Fiber', 'DELTA'],
        mcc: '4899',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'delta.nl',
        website: 'https://delta.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'CAIWAY',
        name: 'Caiway',
        matchValue: 'Caiway',
        aliases: ['Caiway', 'CAIWAY'],
        mcc: '4899',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'caiway.nl',
        website: 'https://caiway.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'FREEDOM_INTERNET',
        name: 'Freedom Internet',
        matchValue: 'Freedom Internet',
        aliases: ['Freedom Internet', 'FREEDOM INTERNET', 'Freedom.nl'],
        mcc: '4899',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'freedom.nl',
        website: 'https://freedom.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ONLINE_NL',
        name: 'Online.nl',
        matchValue: 'Online.nl',
        aliases: ['Online.nl', 'ONLINE.NL'],
        mcc: '4899',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'online.nl',
        website: 'https://online.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];

/** SaaS / cloud — software & storage bills. */
const SOFTWARE_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'APPLE',
        name: 'Apple',
        matchValue: 'Apple',
        aliases: ['Apple', 'APPLE.COM', 'APPLE.COM/BILL', 'Apple Services'],
        mcc: '5815',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'apple.com',
        website: 'https://apple.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'GOOGLE',
        name: 'Google',
        matchValue: 'Google',
        aliases: ['Google', 'GOOGLE *', 'Google Payment', 'GOOGLE PLAY'],
        mcc: '5815',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'google.com',
        website: 'https://google.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'MICROSOFT',
        name: 'Microsoft',
        matchValue: 'Microsoft',
        aliases: ['Microsoft', 'MICROSOFT*', 'MSFT'],
        mcc: '5815',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'microsoft.com',
        website: 'https://microsoft.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ADOBE',
        name: 'Adobe',
        matchValue: 'Adobe',
        aliases: ['Adobe', 'ADOBE*', 'Adobe Creative Cloud'],
        mcc: '5815',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'adobe.com',
        website: 'https://adobe.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'DROPBOX',
        name: 'Dropbox',
        matchValue: 'Dropbox',
        aliases: ['Dropbox', 'DROPBOX*'],
        mcc: '5815',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'dropbox.com',
        website: 'https://dropbox.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'OPENAI',
        name: 'OpenAI',
        matchValue: 'OpenAI',
        aliases: ['OpenAI', 'OPENAI*', 'ChatGPT', 'ChatGPT Plus'],
        mcc: '5815',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'openai.com',
        website: 'https://openai.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 1,
        isActive: true,
    },
    {
        key: 'ANTHROPIC',
        name: 'Anthropic',
        matchValue: 'Anthropic',
        aliases: ['Anthropic', 'ANTHROPIC*', 'Claude', 'Claude.ai', 'Claude Pro'],
        mcc: '5815',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'anthropic.com',
        website: 'https://claude.ai',
        highlight: null,
        markets: ['NL'],
        matchPriority: 1,
        isActive: true,
    },
    {
        key: 'GOOGLE_GEMINI',
        name: 'Google Gemini',
        matchValue: 'Google Gemini',
        aliases: ['Google Gemini', 'Gemini', 'Gemini Advanced', 'Google One AI'],
        mcc: '5815',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'gemini.google.com',
        website: 'https://gemini.google.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'PERPLEXITY',
        name: 'Perplexity',
        matchValue: 'Perplexity',
        aliases: ['Perplexity', 'PERPLEXITY*', 'Perplexity AI', 'Perplexity Pro'],
        mcc: '5815',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'perplexity.ai',
        website: 'https://perplexity.ai',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'CURSOR',
        name: 'Cursor',
        matchValue: 'Cursor',
        aliases: ['Cursor', 'CURSOR*', 'Cursor AI', 'Cursor.sh', 'Anysphere'],
        mcc: '5815',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'cursor.com',
        website: 'https://cursor.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 1,
        isActive: true,
    },
    {
        key: 'WINDSURF',
        name: 'Windsurf',
        matchValue: 'Windsurf',
        aliases: ['Windsurf', 'WINDSURF*', 'Codeium', 'Windsurf Editor'],
        mcc: '5815',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'windsurf.com',
        website: 'https://windsurf.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'GITHUB',
        name: 'GitHub',
        matchValue: 'GitHub',
        aliases: ['GitHub', 'GITHUB*', 'GitHub Inc', 'GitHub Copilot', 'Copilot'],
        mcc: '5815',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'github.com',
        website: 'https://github.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'GRAMMARLY',
        name: 'Grammarly',
        matchValue: 'Grammarly',
        aliases: ['Grammarly', 'GRAMMARLY*', 'Grammarly Inc'],
        mcc: '5815',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'grammarly.com',
        website: 'https://grammarly.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ONEPASSWORD',
        name: '1Password',
        matchValue: '1Password',
        aliases: ['1Password', '1PASSWORD', 'AgileBits', '1Password.com'],
        mcc: '5815',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: '1password.com',
        website: 'https://1password.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 1,
        isActive: true,
    },
    {
        key: 'BITWARDEN',
        name: 'Bitwarden',
        matchValue: 'Bitwarden',
        aliases: ['Bitwarden', 'BITWARDEN*', 'Bitwarden Inc'],
        mcc: '5815',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'bitwarden.com',
        website: 'https://bitwarden.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'LASTPASS',
        name: 'LastPass',
        matchValue: 'LastPass',
        aliases: ['LastPass', 'LASTPASS*', 'LastPass.com'],
        mcc: '5815',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'lastpass.com',
        website: 'https://lastpass.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'JETBRAINS',
        name: 'JetBrains',
        matchValue: 'JetBrains',
        aliases: [
            'JetBrains',
            'JETBRAINS*',
            'IntelliJ',
            'WebStorm',
            'PyCharm',
            'PhpStorm',
            'Rider',
        ],
        mcc: '5815',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'jetbrains.com',
        website: 'https://jetbrains.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];

/** VPN providers — only suggested for the VPN bill preset. */
const VPN_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'NORDVPN',
        name: 'NordVPN',
        matchValue: 'NordVPN',
        aliases: ['NordVPN', 'NORDVPN', 'Nord Security', 'nordvpn.com'],
        mcc: '5817',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'nordvpn.com',
        website: 'https://nordvpn.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'PROTON_VPN',
        name: 'Proton VPN',
        matchValue: 'Proton VPN',
        aliases: ['Proton VPN', 'ProtonVPN', 'PROTONVPN', 'Proton AG'],
        mcc: '5817',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'protonvpn.com',
        website: 'https://protonvpn.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'MULLVAD',
        name: 'Mullvad',
        matchValue: 'Mullvad',
        aliases: ['Mullvad', 'MULLVAD VPN', 'Mullvad VPN'],
        mcc: '5817',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'mullvad.net',
        website: 'https://mullvad.net',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'SURFSHARK',
        name: 'Surfshark',
        matchValue: 'Surfshark',
        aliases: ['Surfshark', 'SURFSHARK'],
        mcc: '5817',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'surfshark.com',
        website: 'https://surfshark.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'EXPRESSVPN',
        name: 'ExpressVPN',
        matchValue: 'ExpressVPN',
        aliases: ['ExpressVPN', 'EXPRESSVPN', 'Express VPN'],
        mcc: '5817',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'expressvpn.com',
        website: 'https://expressvpn.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'CYBERGHOST',
        name: 'CyberGhost',
        matchValue: 'CyberGhost',
        aliases: ['CyberGhost', 'CYBERGHOST', 'CyberGhost VPN'],
        mcc: '5817',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'cyberghostvpn.com',
        website: 'https://cyberghostvpn.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];

/** News / press subscriptions. */
const NEWS_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'VOLKSKRANT',
        name: 'de Volkskrant',
        matchValue: 'Volkskrant',
        aliases: ['Volkskrant', 'de Volkskrant', 'VOLKSKRANT'],
        mcc: '5967',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'volkskrant.nl',
        website: 'https://volkskrant.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'NRC',
        name: 'NRC',
        matchValue: 'NRC',
        aliases: ['NRC', 'NRC Handelsblad', 'NRC.nl'],
        mcc: '5967',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'nrc.nl',
        website: 'https://nrc.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'AD',
        name: 'AD',
        matchValue: 'AD',
        aliases: ['AD', 'Algemeen Dagblad', 'AD.nl'],
        mcc: '5967',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'ad.nl',
        website: 'https://ad.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];

/** Subscriptions merchant presets (telco, software, VPN, news). */
export const SUBSCRIPTIONS_MERCHANTS: readonly MerchantSeed[] = [
    ...TELCO_MERCHANTS,
    ...SOFTWARE_MERCHANTS,
    ...VPN_MERCHANTS,
    ...NEWS_MERCHANTS,
];
