import type { MerchantSeed } from '../types';
import { necessities } from '../types';

/** Telco / ISP — internet & mobile bills. */
const TELCO_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'VODAFONE',
        name: 'Vodafone',
        matchValue: 'Vodafone',
        aliases: ['Vodafone', 'VODAFONE NL'],
        mcc: '4814',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'vodafone.nl',
        website: 'https://vodafone.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'KPN',
        name: 'KPN',
        matchValue: 'KPN',
        aliases: ['KPN', 'KPN BV', 'KPN Mobiel'],
        mcc: '4814',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'kpn.com',
        website: 'https://kpn.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ZIGGO',
        name: 'Ziggo',
        matchValue: 'Ziggo',
        aliases: ['Ziggo', 'ZIGGO BV'],
        mcc: '4899',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'ziggo.nl',
        website: 'https://ziggo.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ODIDO',
        name: 'Odido',
        matchValue: 'Odido',
        aliases: ['Odido', 'ODIDO', 'T-Mobile NL', 'T-Mobile Netherlands'],
        mcc: '4814',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'odido.nl',
        website: 'https://odido.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];

/** SaaS / cloud — software & storage bills. */
const SOFTWARE_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'APPLE',
        name: 'Apple',
        matchValue: 'Apple',
        aliases: ['Apple', 'APPLE.COM', 'APPLE.COM/BILL', 'Apple Services'],
        mcc: '5815',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'apple.com',
        website: 'https://apple.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'GOOGLE',
        name: 'Google',
        matchValue: 'Google',
        aliases: ['Google', 'GOOGLE *', 'Google Payment', 'GOOGLE PLAY'],
        mcc: '5815',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'google.com',
        website: 'https://google.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'MICROSOFT',
        name: 'Microsoft',
        matchValue: 'Microsoft',
        aliases: ['Microsoft', 'MICROSOFT*', 'MSFT'],
        mcc: '5815',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'microsoft.com',
        website: 'https://microsoft.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ADOBE',
        name: 'Adobe',
        matchValue: 'Adobe',
        aliases: ['Adobe', 'ADOBE*', 'Adobe Creative Cloud'],
        mcc: '5815',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'adobe.com',
        website: 'https://adobe.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'DROPBOX',
        name: 'Dropbox',
        matchValue: 'Dropbox',
        aliases: ['Dropbox', 'DROPBOX*'],
        mcc: '5815',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'dropbox.com',
        website: 'https://dropbox.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'OPENAI',
        name: 'OpenAI',
        matchValue: 'OpenAI',
        aliases: ['OpenAI', 'OPENAI*', 'ChatGPT', 'ChatGPT Plus'],
        mcc: '5815',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'openai.com',
        website: 'https://openai.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 1,
        isActive: true,
    },
    {
        key: 'GITHUB',
        name: 'GitHub',
        matchValue: 'GitHub',
        aliases: ['GitHub', 'GITHUB*', 'GitHub Inc'],
        mcc: '5815',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'github.com',
        website: 'https://github.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];

/** VPN providers — only suggested for the VPN bill preset. */
const VPN_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'NORDVPN',
        name: 'NordVPN',
        matchValue: 'NordVPN',
        aliases: ['NordVPN', 'NORDVPN', 'Nord Security', 'nordvpn.com'],
        mcc: '5817',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'nordvpn.com',
        website: 'https://nordvpn.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'PROTON_VPN',
        name: 'Proton VPN',
        matchValue: 'Proton VPN',
        aliases: ['Proton VPN', 'ProtonVPN', 'PROTONVPN', 'Proton AG'],
        mcc: '5817',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'protonvpn.com',
        website: 'https://protonvpn.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'MULLVAD',
        name: 'Mullvad',
        matchValue: 'Mullvad',
        aliases: ['Mullvad', 'MULLVAD VPN', 'Mullvad VPN'],
        mcc: '5817',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'mullvad.net',
        website: 'https://mullvad.net',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'SURFSHARK',
        name: 'Surfshark',
        matchValue: 'Surfshark',
        aliases: ['Surfshark', 'SURFSHARK'],
        mcc: '5817',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'surfshark.com',
        website: 'https://surfshark.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'EXPRESSVPN',
        name: 'ExpressVPN',
        matchValue: 'ExpressVPN',
        aliases: ['ExpressVPN', 'EXPRESSVPN', 'Express VPN'],
        mcc: '5817',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'expressvpn.com',
        website: 'https://expressvpn.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'CYBERGHOST',
        name: 'CyberGhost',
        matchValue: 'CyberGhost',
        aliases: ['CyberGhost', 'CYBERGHOST', 'CyberGhost VPN'],
        mcc: '5817',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'cyberghostvpn.com',
        website: 'https://cyberghostvpn.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];

/** News / press subscriptions. */
const NEWS_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'VOLKSKRANT',
        name: 'de Volkskrant',
        matchValue: 'Volkskrant',
        aliases: ['Volkskrant', 'de Volkskrant', 'VOLKSKRANT'],
        mcc: '5967',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'volkskrant.nl',
        website: 'https://volkskrant.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'NRC',
        name: 'NRC',
        matchValue: 'NRC',
        aliases: ['NRC', 'NRC Handelsblad', 'NRC.nl'],
        mcc: '5967',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'nrc.nl',
        website: 'https://nrc.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'AD',
        name: 'AD',
        matchValue: 'AD',
        aliases: ['AD', 'Algemeen Dagblad', 'AD.nl'],
        mcc: '5967',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'ad.nl',
        website: 'https://ad.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];

/** Subscriptions merchant presets (telco, software, VPN, news). */
export const SUBSCRIPTIONS_MERCHANTS: readonly MerchantSeed[] = [
    ...TELCO_MERCHANTS,
    ...SOFTWARE_MERCHANTS,
    ...VPN_MERCHANTS,
    ...NEWS_MERCHANTS,
];
