import type { MerchantSeed } from '../types';
import { necessities } from '../types';

/** subscriptions merchant presets */
export const SUBSCRIPTIONS_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'VODAFONE',
        name: 'Vodafone',
        matchValue: 'Vodafone',
        aliases: ['Vodafone', 'VODAFONE NL', 'VodafoneZiggo'],
        mcc: '4814',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'vodafone.nl',
        website: 'https://vodafone.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'KPN',
        name: 'KPN',
        matchValue: 'KPN',
        aliases: ['KPN', 'KPN BV', 'KPN Mobiel'],
        mcc: '4814',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'kpn.com',
        website: 'https://kpn.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ZIGGO',
        name: 'Ziggo',
        matchValue: 'Ziggo',
        aliases: ['Ziggo', 'ZIGGO BV', 'VodafoneZiggo'],
        mcc: '4899',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'ziggo.nl',
        website: 'https://ziggo.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ODIDO',
        name: 'Odido',
        matchValue: 'Odido',
        aliases: ['Odido', 'ODIDO', 'T-Mobile NL', 'T-Mobile Netherlands'],
        mcc: '4814',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'odido.nl',
        website: 'https://odido.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'APPLE',
        name: 'Apple',
        matchValue: 'Apple',
        aliases: ['Apple', 'APPLE.COM', 'APPLE.COM/BILL', 'Apple Services'],
        mcc: '5815',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'apple.com',
        website: 'https://apple.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'GOOGLE',
        name: 'Google',
        matchValue: 'Google',
        aliases: ['Google', 'GOOGLE *', 'Google Payment', 'GOOGLE PLAY'],
        mcc: '5815',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'google.com',
        website: 'https://google.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'MICROSOFT',
        name: 'Microsoft',
        matchValue: 'Microsoft',
        aliases: ['Microsoft', 'MICROSOFT*', 'MSFT', 'Xbox'],
        mcc: '5815',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'microsoft.com',
        website: 'https://microsoft.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ADOBE',
        name: 'Adobe',
        matchValue: 'Adobe',
        aliases: ['Adobe', 'ADOBE*', 'Adobe Creative Cloud'],
        mcc: '5815',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'adobe.com',
        website: 'https://adobe.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'DROPBOX',
        name: 'Dropbox',
        matchValue: 'Dropbox',
        aliases: ['Dropbox', 'DROPBOX*'],
        mcc: '5815',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'dropbox.com',
        website: 'https://dropbox.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'OPENAI',
        name: 'OpenAI',
        matchValue: 'OpenAI',
        aliases: ['OpenAI', 'OPENAI*', 'ChatGPT', 'ChatGPT Plus'],
        mcc: '5815',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'openai.com',
        website: 'https://openai.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'GITHUB',
        name: 'GitHub',
        matchValue: 'GitHub',
        aliases: ['GitHub', 'GITHUB*', 'GitHub Inc'],
        mcc: '5815',
        jarKey: necessities,
        categoryTemplateKey: 'SUBSCRIPTIONS',
        logoDomain: 'github.com',
        website: 'https://github.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];
