import type { MerchantSeed } from '../types';
import { necessities } from '../types';

/** taxes merchant presets */
export const TAXES_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'BELASTINGDIENST',
        name: 'Belastingdienst',
        matchValue: 'Belastingdienst',
        aliases: ['Belastingdienst', 'BELASTINGDIENST', 'Belasting Dienst', 'Tax and Customs'],
        mcc: '9311',
        jarKey: necessities,
        categoryTemplateKey: 'TAXES',
        logoDomain: 'belastingdienst.nl',
        website: 'https://belastingdienst.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'DOUANE',
        name: 'Douane',
        matchValue: 'Douane',
        aliases: ['Douane', 'DOUANE NL', 'Customs NL'],
        mcc: '9311',
        jarKey: necessities,
        categoryTemplateKey: 'TAXES',
        logoDomain: 'douane.nl',
        website: 'https://douane.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'DUO',
        name: 'DUO',
        matchValue: 'DUO',
        aliases: ['DUO', 'DUO IB-Groep', 'Dienst Uitvoering Onderwijs'],
        mcc: '9311',
        jarKey: necessities,
        categoryTemplateKey: 'TAXES',
        logoDomain: 'duo.nl',
        website: 'https://duo.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'RDW',
        name: 'RDW',
        matchValue: 'RDW',
        aliases: ['RDW', 'RDW.nl', 'Rijksdienst voor het Wegverkeer'],
        mcc: '9399',
        jarKey: necessities,
        categoryTemplateKey: 'TAXES',
        logoDomain: 'rdw.nl',
        website: 'https://rdw.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'CBR',
        name: 'CBR',
        matchValue: 'CBR',
        aliases: ['CBR', 'CBR.nl', 'Centraal Bureau Rijvaardigheid'],
        mcc: '9399',
        jarKey: necessities,
        categoryTemplateKey: 'TAXES',
        logoDomain: 'cbr.nl',
        website: 'https://cbr.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'UWV',
        name: 'UWV',
        matchValue: 'UWV',
        aliases: ['UWV', 'UWV NL', 'Uitvoeringsinstituut Werknemersverzekeringen'],
        mcc: '9399',
        jarKey: necessities,
        categoryTemplateKey: 'TAXES',
        logoDomain: 'uwv.nl',
        website: 'https://uwv.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'SVB',
        name: 'SVB',
        matchValue: 'SVB',
        aliases: ['SVB', 'Sociale Verzekeringsbank'],
        mcc: '9399',
        jarKey: necessities,
        categoryTemplateKey: 'TAXES',
        logoDomain: 'svb.nl',
        website: 'https://svb.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'KADASTER',
        name: 'Kadaster',
        matchValue: 'Kadaster',
        aliases: ['Kadaster', 'KADASTER', 'Het Kadaster'],
        mcc: '9399',
        jarKey: necessities,
        categoryTemplateKey: 'TAXES',
        logoDomain: 'kadaster.nl',
        website: 'https://kadaster.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];
