import type { MerchantSeed } from '../types';
import { necessities } from '../types';

/** transport merchant presets */
export const TRANSPORT_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'NS',
        name: 'NS',
        matchValue: 'NS ',
        aliases: ['NS ', 'NS Groep', 'Nederlandse Spoorwegen', 'OV-chipkaart NS'],
        mcc: '4111',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'ns.nl',
        website: 'https://ns.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'GVB',
        name: 'GVB',
        matchValue: 'GVB',
        aliases: ['GVB', 'GVB Amsterdam', 'Gemeente Vervoerbedrijf'],
        mcc: '4111',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'gvb.nl',
        website: 'https://gvb.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'RET',
        name: 'RET',
        matchValue: 'RET',
        aliases: ['RET', 'RET Rotterdam', 'RET OV'],
        mcc: '4111',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'ret.nl',
        website: 'https://ret.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'SHELL',
        name: 'Shell',
        matchValue: 'Shell',
        aliases: ['Shell', 'SHELL NL', 'Shell Station'],
        mcc: '5541',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'shell.nl',
        website: 'https://shell.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BP',
        name: 'BP',
        matchValue: 'BP ',
        aliases: ['BP ', 'BP Station', 'BP EXPRESS'],
        mcc: '5541',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'bp.com',
        website: 'https://bp.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'TOTALENERGIES',
        name: 'TotalEnergies',
        matchValue: 'TotalEnergies',
        aliases: ['TotalEnergies', 'TOTAL ', 'Total NL', 'TOTALEnergies'],
        mcc: '5541',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'totalenergies.nl',
        website: 'https://totalenergies.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'UBER',
        name: 'Uber',
        matchValue: 'Uber',
        aliases: ['Uber', 'UBER BV', 'UBER *TRIP', 'UBER TRIP'],
        mcc: '4121',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'uber.com',
        website: 'https://uber.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ANWB',
        name: 'ANWB',
        matchValue: 'ANWB',
        aliases: ['ANWB', 'ANWB B.V.', 'ANWB Wegenwacht'],
        mcc: '5533',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'anwb.nl',
        website: 'https://anwb.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'YELLOWBRICK_FINE',
        name: 'Yellowbrick',
        matchValue: 'Yellowbrick',
        aliases: ['Yellowbrick', 'YELLOWBRICK', 'YB Parking'],
        mcc: '7523',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'yellowbrick.nl',
        website: 'https://yellowbrick.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'PARKMOBILE',
        name: 'Parkmobile',
        matchValue: 'Parkmobile',
        aliases: ['Parkmobile', 'PARKMOBILE', 'Park Mobile'],
        mcc: '7523',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'parkmobile.nl',
        website: 'https://parkmobile.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'SWAPFIETS',
        name: 'Swapfiets',
        matchValue: 'Swapfiets',
        aliases: ['Swapfiets', 'SWAPFIETS', 'Swap fiets'],
        mcc: '7999',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'swapfiets.nl',
        website: 'https://swapfiets.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'LEASEPLAN',
        name: 'LeasePlan',
        matchValue: 'LeasePlan',
        aliases: ['LeasePlan', 'LEASEPLAN', 'Ayvens'],
        mcc: '7512',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'leaseplan.com',
        website: 'https://leaseplan.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ALPHERA',
        name: 'Alphera',
        matchValue: 'Alphera',
        aliases: ['Alphera', 'ALPHERA', 'Alphera Financial Services'],
        mcc: '7512',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'alphera.nl',
        website: 'https://alphera.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'Q_PARK',
        name: 'Q-Park',
        matchValue: 'Q-Park',
        aliases: ['Q-Park', 'QPARK', 'Q Park'],
        mcc: '7523',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'q-park.nl',
        website: 'https://q-park.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ALLEGO',
        name: 'Allego',
        matchValue: 'Allego',
        aliases: ['Allego', 'ALLEGO', 'Allego Charging'],
        mcc: '5542',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'allego.eu',
        website: 'https://allego.eu',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];
