import type { MerchantSeed } from '../types';
import { necessities } from '../types';
import { AUTO_FINANCE_MERCHANTS } from './auto-finance';

/** transport merchant presets */
export const TRANSPORT_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'NS',
        name: 'NS',
        matchValue: 'NS ',
        aliases: ['NS ', 'NS Groep', 'Nederlandse Spoorwegen', 'OV-chipkaart NS'],
        mcc: '4111',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'ns.nl',
        website: 'https://ns.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'GVB',
        name: 'GVB',
        matchValue: 'GVB',
        aliases: ['GVB', 'GVB Amsterdam', 'Gemeente Vervoerbedrijf'],
        mcc: '4111',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'gvb.nl',
        website: 'https://gvb.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'RET',
        name: 'RET',
        matchValue: 'RET',
        aliases: ['RET', 'RET Rotterdam', 'RET OV'],
        mcc: '4111',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'ret.nl',
        website: 'https://ret.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'SHELL',
        name: 'Shell',
        matchValue: 'Shell',
        aliases: ['Shell', 'SHELL NL', 'Shell Station'],
        mcc: '5541',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'shell.nl',
        website: 'https://shell.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BP',
        name: 'BP',
        matchValue: 'BP ',
        aliases: ['BP ', 'BP Station', 'BP EXPRESS'],
        mcc: '5541',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'bp.com',
        website: 'https://bp.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'TOTALENERGIES',
        name: 'TotalEnergies',
        matchValue: 'TotalEnergies',
        aliases: ['TotalEnergies', 'TOTAL ', 'Total NL', 'TOTALEnergies'],
        mcc: '5541',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'totalenergies.nl',
        website: 'https://totalenergies.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'UBER',
        name: 'Uber',
        matchValue: 'Uber',
        aliases: ['Uber', 'UBER BV', 'UBER *TRIP', 'UBER TRIP'],
        mcc: '4121',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'uber.com',
        website: 'https://uber.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ANWB',
        name: 'ANWB',
        matchValue: 'ANWB',
        aliases: ['ANWB', 'ANWB B.V.', 'ANWB Wegenwacht'],
        mcc: '5533',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'anwb.nl',
        website: 'https://anwb.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'YELLOWBRICK_FINE',
        name: 'Yellowbrick',
        matchValue: 'Yellowbrick',
        aliases: ['Yellowbrick', 'YELLOWBRICK', 'YB Parking'],
        mcc: '7523',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'yellowbrick.nl',
        website: 'https://yellowbrick.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'PARKMOBILE',
        name: 'Parkmobile',
        matchValue: 'Parkmobile',
        aliases: ['Parkmobile', 'PARKMOBILE', 'Park Mobile'],
        mcc: '7523',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'parkmobile.nl',
        website: 'https://parkmobile.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'SWAPFIETS',
        name: 'Swapfiets',
        matchValue: 'Swapfiets',
        aliases: ['Swapfiets', 'SWAPFIETS', 'Swap fiets'],
        mcc: '7999',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'swapfiets.nl',
        website: 'https://swapfiets.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'LEASEPLAN',
        name: 'LeasePlan',
        matchValue: 'LeasePlan',
        aliases: ['LeasePlan', 'LEASEPLAN', 'Ayvens'],
        mcc: '7512',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'leaseplan.com',
        website: 'https://leaseplan.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ALPHERA',
        name: 'Alphera',
        matchValue: 'Alphera',
        aliases: ['Alphera', 'ALPHERA', 'Alphera Financial Services'],
        mcc: '7512',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'alphera.nl',
        website: 'https://alphera.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'Q_PARK',
        name: 'Q-Park',
        matchValue: 'Q-Park',
        aliases: ['Q-Park', 'QPARK', 'Q Park'],
        mcc: '7523',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'q-park.nl',
        website: 'https://q-park.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ALLEGO',
        name: 'Allego',
        matchValue: 'Allego',
        aliases: ['Allego', 'ALLEGO', 'Allego Charging'],
        mcc: '5542',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'allego.eu',
        website: 'https://allego.eu',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'HTM',
        name: 'HTM',
        matchValue: 'HTM',
        aliases: ['HTM', 'HTM Personenvervoer', 'HTM Den Haag'],
        mcc: '4111',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'htm.nl',
        website: 'https://htm.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ARRIVA',
        name: 'Arriva',
        matchValue: 'Arriva',
        aliases: ['Arriva', 'ARRIVA NL'],
        mcc: '4111',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'arriva.nl',
        website: 'https://arriva.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'CONNEXXION',
        name: 'Connexxion',
        matchValue: 'Connexxion',
        aliases: ['Connexxion', 'CONNEXXION', 'Transdev NL'],
        mcc: '4111',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'connexxion.nl',
        website: 'https://connexxion.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'EBS',
        name: 'EBS',
        matchValue: 'EBS',
        aliases: ['EBS', 'EBS OV', 'Elektriciteitsbedrijf Stadsregio'],
        mcc: '4111',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'ebs-ov.nl',
        website: 'https://ebs-ov.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'QBUZZ',
        name: 'Qbuzz',
        matchValue: 'Qbuzz',
        aliases: ['Qbuzz', 'QBUZZ'],
        mcc: '4111',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'qbuzz.nl',
        website: 'https://qbuzz.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'KEOLIS',
        name: 'Keolis',
        matchValue: 'Keolis',
        aliases: ['Keolis', 'KEOLIS NL'],
        mcc: '4111',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'keolis.nl',
        website: 'https://keolis.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BRAVO',
        name: 'Bravo',
        matchValue: 'Bravo',
        aliases: ['Bravo', 'BRAVO', 'Bravo OV', 'BravoOV'],
        mcc: '4111',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'bravoov.nl',
        website: 'https://bravoov.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    // EV charging
    {
        key: 'FASTNED',
        name: 'Fastned',
        matchValue: 'Fastned',
        aliases: ['Fastned', 'FASTNED'],
        mcc: '5542',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'fastned.nl',
        website: 'https://fastned.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'IONITY',
        name: 'Ionity',
        matchValue: 'Ionity',
        aliases: ['Ionity', 'IONITY'],
        mcc: '5542',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'ionity.eu',
        website: 'https://ionity.eu',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'PLUGSURFING',
        name: 'Plugsurfing',
        matchValue: 'Plugsurfing',
        aliases: ['Plugsurfing', 'PLUGSURFING'],
        mcc: '5542',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'plugsurfing.com',
        website: 'https://plugsurfing.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'NEWMOTION',
        name: 'NewMotion',
        matchValue: 'NewMotion',
        aliases: ['NewMotion', 'Shell Recharge', 'ShellRecharge'],
        mcc: '5542',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'newmotion.com',
        website: 'https://newmotion.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'TESLA_SUPERCHARGER',
        name: 'Tesla Supercharger',
        matchValue: 'Tesla Supercharger',
        aliases: ['Tesla Supercharger', 'Tesla Charging', 'Supercharger'],
        mcc: '5542',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'tesla.com',
        website: 'https://tesla.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    // Parking
    {
        key: 'LEKKER_PARKEREN',
        name: 'Lekker Parkeren',
        matchValue: 'Lekker Parkeren',
        aliases: ['Lekker Parkeren', 'LekkerParkeren'],
        mcc: '7523',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'lekkerparkeren.nl',
        website: 'https://lekkerparkeren.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'P1',
        name: 'P1',
        matchValue: 'P1',
        aliases: ['P1', 'P1 Parkeren', 'P1 Parking'],
        mcc: '7523',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'p1.nl',
        website: 'https://p1.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'APCOA',
        name: 'APCOA',
        matchValue: 'APCOA',
        aliases: ['APCOA', 'Apcoa Parking'],
        mcc: '7523',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'apcoa.nl',
        website: 'https://apcoa.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    // Fuel stations
    {
        key: 'TINQ',
        name: 'TinQ',
        matchValue: 'TinQ',
        aliases: ['TinQ', 'TINQ'],
        mcc: '5541',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'tinq.nl',
        website: 'https://tinq.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'TANGO',
        name: 'Tango',
        matchValue: 'Tango',
        aliases: ['Tango', 'TANGO'],
        mcc: '5541',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'tango.nl',
        website: 'https://tango.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ESSO',
        name: 'Esso',
        matchValue: 'Esso',
        aliases: ['Esso', 'ESSO'],
        mcc: '5541',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'esso.nl',
        website: 'https://esso.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'AVIA',
        name: 'AVIA',
        matchValue: 'AVIA',
        aliases: ['AVIA', 'Avia Station'],
        mcc: '5541',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'avia.nl',
        website: 'https://avia.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'FIREZONE',
        name: 'Firezone',
        matchValue: 'Firezone',
        aliases: ['Firezone', 'FIREZONE'],
        mcc: '5541',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'firezone.nl',
        website: 'https://firezone.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    // Bike lease
    {
        key: 'BUSINESS_BIKE',
        name: 'Business Bike',
        matchValue: 'Business Bike',
        aliases: ['Business Bike', 'BusinessBike'],
        mcc: '7999',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'businessbike.nl',
        website: 'https://businessbike.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'LEASE_A_BIKE',
        name: 'Lease a Bike',
        matchValue: 'Lease a Bike',
        aliases: ['Lease a Bike', 'LeaseABike'],
        mcc: '7999',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'lease-a-bike.nl',
        website: 'https://lease-a-bike.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'CYCLIS',
        name: 'Cyclis',
        matchValue: 'Cyclis',
        aliases: ['Cyclis', 'CYCLIS'],
        mcc: '7999',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'cyclis.nl',
        website: 'https://cyclis.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    // Car rental / car sharing
    {
        key: 'SIXT',
        name: 'Sixt',
        matchValue: 'Sixt',
        aliases: ['Sixt', 'SIXT', 'Sixt Rent a Car'],
        mcc: '7512',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'sixt.nl',
        website: 'https://sixt.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'EUROPCAR',
        name: 'Europcar',
        matchValue: 'Europcar',
        aliases: ['Europcar', 'EUROPCAR'],
        mcc: '7512',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'europcar.nl',
        website: 'https://europcar.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'AVIS',
        name: 'Avis',
        matchValue: 'Avis',
        aliases: ['Avis', 'AVIS', 'Avis Rent a Car'],
        mcc: '7512',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'avis.nl',
        website: 'https://avis.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'HERTZ',
        name: 'Hertz',
        matchValue: 'Hertz',
        aliases: ['Hertz', 'HERTZ'],
        mcc: '7512',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'hertz.nl',
        website: 'https://hertz.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BUDGET_RENTAL',
        name: 'Budget',
        matchValue: 'Budget Car Rental',
        aliases: ['Budget Car Rental', 'Budget Rent a Car', 'BUDGET RENTAL'],
        mcc: '7512',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'budget.nl',
        website: 'https://budget.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ENTERPRISE',
        name: 'Enterprise',
        matchValue: 'Enterprise',
        aliases: ['Enterprise', 'ENTERPRISE', 'Enterprise Rent-A-Car'],
        mcc: '7512',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'enterprise.nl',
        website: 'https://enterprise.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'GREENWHEELS',
        name: 'Greenwheels',
        matchValue: 'Greenwheels',
        aliases: ['Greenwheels', 'GREENWHEELS', 'Green Wheels'],
        mcc: '7512',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'greenwheels.nl',
        website: 'https://greenwheels.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'MYWHEELS',
        name: 'MyWheels',
        matchValue: 'MyWheels',
        aliases: ['MyWheels', 'MYWHEELS', 'My Wheels'],
        mcc: '7512',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'mywheels.nl',
        website: 'https://mywheels.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'SNAPPCAR',
        name: 'SnappCar',
        matchValue: 'SnappCar',
        aliases: ['SnappCar', 'SNAPPCAR', 'Snapp Car'],
        mcc: '7512',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'snappcar.nl',
        website: 'https://snappcar.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'AMBER',
        name: 'Amber',
        matchValue: 'Amber',
        aliases: ['Amber', 'AMBER', 'Amber Mobility'],
        mcc: '7512',
        jarKey: necessities,
        categoryTemplateKey: 'TRANSPORT',
        logoDomain: 'driveamber.com',
        website: 'https://driveamber.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    ...AUTO_FINANCE_MERCHANTS,
];
