import type { MerchantSeed } from '../types';
import { play } from '../types';

/** travel merchant presets */
export const TRAVEL_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'KLM',
        name: 'KLM',
        matchValue: 'KLM',
        aliases: ['KLM', 'KLM Royal Dutch'],
        mcc: '4511',
        jarKey: play,
        categoryTemplateKey: 'TRAVEL',
        logoDomain: 'klm.com',
        website: 'https://klm.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'TRANSAVIA',
        name: 'Transavia',
        matchValue: 'Transavia',
        aliases: ['Transavia', 'TRANSAVIA'],
        mcc: '4511',
        jarKey: play,
        categoryTemplateKey: 'TRAVEL',
        logoDomain: 'transavia.com',
        website: 'https://transavia.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'EASYJET',
        name: 'easyJet',
        matchValue: 'easyJet',
        aliases: ['easyJet', 'EASYJET'],
        mcc: '4511',
        jarKey: play,
        categoryTemplateKey: 'TRAVEL',
        logoDomain: 'easyjet.com',
        website: 'https://easyjet.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'RYANAIR',
        name: 'Ryanair',
        matchValue: 'Ryanair',
        aliases: ['Ryanair', 'RYANAIR'],
        mcc: '4511',
        jarKey: play,
        categoryTemplateKey: 'TRAVEL',
        logoDomain: 'ryanair.com',
        website: 'https://ryanair.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BOOKING',
        name: 'Booking.com',
        matchValue: 'Booking',
        aliases: ['Booking.com', 'BOOKING.COM', 'Booking.com BV'],
        mcc: '7011',
        jarKey: play,
        categoryTemplateKey: 'TRAVEL',
        logoDomain: 'booking.com',
        website: 'https://booking.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'AIRBNB',
        name: 'Airbnb',
        matchValue: 'Airbnb',
        aliases: ['Airbnb', 'AIRBNB'],
        mcc: '7011',
        jarKey: play,
        categoryTemplateKey: 'TRAVEL',
        logoDomain: 'airbnb.com',
        website: 'https://airbnb.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'HOTELS_COM',
        name: 'Hotels.com',
        matchValue: 'Hotels.com',
        aliases: ['Hotels.com', 'HOTELS.COM'],
        mcc: '7011',
        jarKey: play,
        categoryTemplateKey: 'TRAVEL',
        logoDomain: 'hotels.com',
        website: 'https://hotels.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'NS_INTERNATIONAL',
        name: 'NS International',
        matchValue: 'NS International',
        aliases: ['NS International', 'NS Internationaal', 'Eurostar NS'],
        mcc: '4112',
        jarKey: play,
        categoryTemplateKey: 'TRAVEL',
        logoDomain: 'nsinternational.com',
        website: 'https://nsinternational.com',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];
