import type { MerchantSeed } from '../types';
import { necessities } from '../types';

/** utilities merchant presets */
export const UTILITIES_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'VATTENFALL',
        name: 'Vattenfall',
        matchValue: 'Vattenfall',
        aliases: ['Vattenfall', 'VATTENFALL NL', 'Nuon'],
        mcc: '4900',
        jarKey: necessities,
        categoryTemplateKey: 'UTILITIES',
        logoDomain: 'vattenfall.nl',
        website: 'https://vattenfall.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ENECO',
        name: 'Eneco',
        matchValue: 'Eneco',
        aliases: ['Eneco', 'ENECO BV', 'Eneco Energy'],
        mcc: '4900',
        jarKey: necessities,
        categoryTemplateKey: 'UTILITIES',
        logoDomain: 'eneco.nl',
        website: 'https://eneco.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ESSENT',
        name: 'Essent',
        matchValue: 'Essent',
        aliases: ['Essent', 'ESSENT NL', 'Essent Retail'],
        mcc: '4900',
        jarKey: necessities,
        categoryTemplateKey: 'UTILITIES',
        logoDomain: 'essent.nl',
        website: 'https://essent.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'WATERNET',
        name: 'Waternet',
        matchValue: 'Waternet',
        aliases: ['Waternet', 'WATERNET', 'Waterschap'],
        mcc: '4900',
        jarKey: necessities,
        categoryTemplateKey: 'UTILITIES',
        logoDomain: 'waternet.nl',
        website: 'https://waternet.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BUDGET_THUIS',
        name: 'Budget Thuis',
        matchValue: 'Budget Thuis',
        aliases: ['Budget Thuis', 'BUDGET THUIS', 'BudgetEnergie'],
        mcc: '4900',
        jarKey: necessities,
        categoryTemplateKey: 'UTILITIES',
        logoDomain: 'budgetthuis.nl',
        website: 'https://budgetthuis.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'GREENCHOICE',
        name: 'Greenchoice',
        matchValue: 'Greenchoice',
        aliases: ['Greenchoice', 'GREENCHOICE'],
        mcc: '4900',
        jarKey: necessities,
        categoryTemplateKey: 'UTILITIES',
        logoDomain: 'greenchoice.nl',
        website: 'https://greenchoice.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'VANDEBRON',
        name: 'Vandebron',
        matchValue: 'Vandebron',
        aliases: ['Vandebron', 'VANDEBRON'],
        mcc: '4900',
        jarKey: necessities,
        categoryTemplateKey: 'UTILITIES',
        logoDomain: 'vandebron.nl',
        website: 'https://vandebron.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'OXXIO',
        name: 'Oxxio',
        matchValue: 'Oxxio',
        aliases: ['Oxxio', 'OXXIO'],
        mcc: '4900',
        jarKey: necessities,
        categoryTemplateKey: 'UTILITIES',
        logoDomain: 'oxxio.nl',
        website: 'https://oxxio.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ENGIE',
        name: 'ENGIE',
        matchValue: 'ENGIE',
        aliases: ['ENGIE', 'Engie NL', 'Electrabel'],
        mcc: '4900',
        jarKey: necessities,
        categoryTemplateKey: 'UTILITIES',
        logoDomain: 'engie.nl',
        website: 'https://engie.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];
