import type { MerchantSeed } from '../types';
import { necessities } from '../types';

/** utilities merchant presets */
export const UTILITIES_MERCHANTS: readonly MerchantSeed[] = [
    {
        key: 'VATTENFALL',
        name: 'Vattenfall',
        matchValue: 'Vattenfall',
        aliases: ['Vattenfall', 'VATTENFALL NL', 'Nuon'],
        mcc: '4900',
        jarKey: necessities,
        categoryTemplateKey: 'UTILITIES',
        logoDomain: 'vattenfall.nl',
        website: 'https://vattenfall.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ENECO',
        name: 'Eneco',
        matchValue: 'Eneco',
        aliases: ['Eneco', 'ENECO BV', 'Eneco Energy'],
        mcc: '4900',
        jarKey: necessities,
        categoryTemplateKey: 'UTILITIES',
        logoDomain: 'eneco.nl',
        website: 'https://eneco.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ESSENT',
        name: 'Essent',
        matchValue: 'Essent',
        aliases: ['Essent', 'ESSENT NL', 'Essent Retail'],
        mcc: '4900',
        jarKey: necessities,
        categoryTemplateKey: 'UTILITIES',
        logoDomain: 'essent.nl',
        website: 'https://essent.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'WATERNET',
        name: 'Waternet',
        matchValue: 'Waternet',
        aliases: ['Waternet', 'WATERNET', 'Waterschap'],
        mcc: '4900',
        jarKey: necessities,
        categoryTemplateKey: 'UTILITIES',
        logoDomain: 'waternet.nl',
        website: 'https://waternet.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BUDGET_THUIS',
        name: 'Budget Thuis',
        matchValue: 'Budget Thuis',
        aliases: ['Budget Thuis', 'BUDGET THUIS', 'BudgetEnergie'],
        mcc: '4900',
        jarKey: necessities,
        categoryTemplateKey: 'UTILITIES',
        logoDomain: 'budgetthuis.nl',
        website: 'https://budgetthuis.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'GREENCHOICE',
        name: 'Greenchoice',
        matchValue: 'Greenchoice',
        aliases: ['Greenchoice', 'GREENCHOICE'],
        mcc: '4900',
        jarKey: necessities,
        categoryTemplateKey: 'UTILITIES',
        logoDomain: 'greenchoice.nl',
        website: 'https://greenchoice.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'VANDEBRON',
        name: 'Vandebron',
        matchValue: 'Vandebron',
        aliases: ['Vandebron', 'VANDEBRON'],
        mcc: '4900',
        jarKey: necessities,
        categoryTemplateKey: 'UTILITIES',
        logoDomain: 'vandebron.nl',
        website: 'https://vandebron.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'OXXIO',
        name: 'Oxxio',
        matchValue: 'Oxxio',
        aliases: ['Oxxio', 'OXXIO'],
        mcc: '4900',
        jarKey: necessities,
        categoryTemplateKey: 'UTILITIES',
        logoDomain: 'oxxio.nl',
        website: 'https://oxxio.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ENGIE',
        name: 'ENGIE',
        matchValue: 'ENGIE',
        aliases: ['ENGIE', 'Engie NL', 'Electrabel'],
        mcc: '4900',
        jarKey: necessities,
        categoryTemplateKey: 'UTILITIES',
        logoDomain: 'engie.nl',
        website: 'https://engie.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'COOLBLUE_ENERGIE',
        name: 'Coolblue Energie',
        matchValue: 'Coolblue Energie',
        aliases: ['Coolblue Energie', 'Coolblue Energy'],
        mcc: '4900',
        jarKey: necessities,
        categoryTemplateKey: 'UTILITIES',
        logoDomain: 'coolblue.nl',
        website: 'https://energie.coolblue.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'INNOVA',
        name: 'Innova Energie',
        matchValue: 'Innova Energie',
        aliases: ['Innova Energie', 'Innova Energy', 'INNOVA'],
        mcc: '4900',
        jarKey: necessities,
        categoryTemplateKey: 'UTILITIES',
        logoDomain: 'innovaenergie.nl',
        website: 'https://innovaenergie.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'PURE_ENERGIE',
        name: 'Pure Energie',
        matchValue: 'Pure Energie',
        aliases: ['Pure Energie', 'PURE ENERGIE'],
        mcc: '4900',
        jarKey: necessities,
        categoryTemplateKey: 'UTILITIES',
        logoDomain: 'pure-energie.nl',
        website: 'https://pure-energie.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ENERGIEDIRECT',
        name: 'Energiedirect',
        matchValue: 'Energiedirect',
        aliases: ['Energiedirect', 'ENERGIEDIRECT'],
        mcc: '4900',
        jarKey: necessities,
        categoryTemplateKey: 'UTILITIES',
        logoDomain: 'energiedirect.nl',
        website: 'https://energiedirect.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'ANWB_ENERGIE',
        name: 'ANWB Energie',
        matchValue: 'ANWB Energie',
        aliases: ['ANWB Energie', 'ANWB Energy'],
        mcc: '4900',
        jarKey: necessities,
        categoryTemplateKey: 'UTILITIES',
        logoDomain: 'anwb.nl',
        website: 'https://anwb.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'EVIDES',
        name: 'Evides',
        matchValue: 'Evides',
        aliases: ['Evides', 'EVIDES', 'Evides Waterbedrijf'],
        mcc: '4900',
        jarKey: necessities,
        categoryTemplateKey: 'UTILITIES',
        logoDomain: 'evides.nl',
        website: 'https://evides.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'PWN',
        name: 'PWN',
        matchValue: 'PWN',
        aliases: ['PWN', 'PWN Waterleidingbedrijf', 'PWN Noord-Holland'],
        mcc: '4900',
        jarKey: necessities,
        categoryTemplateKey: 'UTILITIES',
        logoDomain: 'pwn.nl',
        website: 'https://pwn.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'VITENS',
        name: 'Vitens',
        matchValue: 'Vitens',
        aliases: ['Vitens', 'VITENS'],
        mcc: '4900',
        jarKey: necessities,
        categoryTemplateKey: 'UTILITIES',
        logoDomain: 'vitens.nl',
        website: 'https://vitens.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'BRABANT_WATER',
        name: 'Brabant Water',
        matchValue: 'Brabant Water',
        aliases: ['Brabant Water', 'BRABANT WATER', 'BrabantWater'],
        mcc: '4900',
        jarKey: necessities,
        categoryTemplateKey: 'UTILITIES',
        logoDomain: 'brabantwater.nl',
        website: 'https://brabantwater.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'DUNEA',
        name: 'Dunea',
        matchValue: 'Dunea',
        aliases: ['Dunea', 'DUNEA', 'Dunea Duin & Water'],
        mcc: '4900',
        jarKey: necessities,
        categoryTemplateKey: 'UTILITIES',
        logoDomain: 'dunea.nl',
        website: 'https://dunea.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'WML',
        name: 'WML',
        matchValue: 'WML',
        aliases: ['WML', 'Waterleiding Maatschappij Limburg'],
        mcc: '4900',
        jarKey: necessities,
        categoryTemplateKey: 'UTILITIES',
        logoDomain: 'wml.nl',
        website: 'https://wml.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'OASEN',
        name: 'Oasen',
        matchValue: 'Oasen',
        aliases: ['Oasen', 'OASEN'],
        mcc: '4900',
        jarKey: necessities,
        categoryTemplateKey: 'UTILITIES',
        logoDomain: 'oasen.nl',
        website: 'https://oasen.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'WATERBEDRIJF_GRONINGEN',
        name: 'Waterbedrijf Groningen',
        matchValue: 'Waterbedrijf Groningen',
        aliases: ['Waterbedrijf Groningen', 'WATERBEDRIJF GRONINGEN'],
        mcc: '4900',
        jarKey: necessities,
        categoryTemplateKey: 'UTILITIES',
        logoDomain: 'waterbedrijfgroningen.nl',
        website: 'https://waterbedrijfgroningen.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
    {
        key: 'WMD',
        name: 'WMD',
        matchValue: 'WMD',
        aliases: ['WMD', 'WMD Drinkwater', 'Watermaatschappij Drenthe'],
        mcc: '4900',
        jarKey: necessities,
        categoryTemplateKey: 'UTILITIES',
        logoDomain: 'wmd.nl',
        website: 'https://wmd.nl',
        highlight: null,
        markets: ['NL'],
        matchPriority: 0,
        isActive: true,
    },
];
