#!/usr/bin/env node
/**
 * Build a local `.env.{staging|production}` from the GitHub Environment sync files
 * (same values CI uses). Keep root `.env` for local Docker;
 * use NODE_ENV=staging|production to load the remote target.
 *
 *   pnpm env:use production
 *   pnpm env:use staging
 *   NODE_ENV=production pnpm db:push
 *
 * Source files (gitignored):
 *   .env.github.secrets.{staging|production}
 *   .env.github.vars.{staging|production}
 *
 * Output (gitignored):
 *   .env.{staging|production}
 */

const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.join(__dirname, '..');
const TARGETS = new Set(['staging', 'production']);

function parseEnv(content) {
    const out = {};
    for (const line of content.split(/\r?\n/)) {
        const t = line.trim();
        if (!t || t.startsWith('#')) continue;
        const eq = t.indexOf('=');
        if (eq <= 0) continue;
        const key = t.slice(0, eq).trim();
        if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) continue;
        let val = t.slice(eq + 1).trim();
        if (
            (val.startsWith('"') && val.endsWith('"') && val.length >= 2) ||
            (val.startsWith("'") && val.endsWith("'") && val.length >= 2)
        ) {
            val = val.slice(1, -1);
        }
        if (val.trim() === '') continue;
        out[key] = val;
    }
    return out;
}

function encode(key, value) {
    const v = String(value);
    if (/[\r\n"#]/.test(v) || /\s/.test(v)) {
        const esc = v
            .replace(/\\/g, '\\\\')
            .replace(/"/g, '\\"')
            .replace(/\r/g, '\\r')
            .replace(/\n/g, '\\n');
        return `${key}="${esc}"`;
    }
    return `${key}=${v}`;
}

function main() {
    const target = (process.argv[2] || '').trim().toLowerCase();
    if (!TARGETS.has(target)) {
        console.error('Usage: pnpm env:use <staging|production>');
        process.exit(1);
    }

    const secretsPath = path.join(ROOT, `.env.github.secrets.${target}`);
    const varsPath = path.join(ROOT, `.env.github.vars.${target}`);
    if (!fs.existsSync(secretsPath) || !fs.existsSync(varsPath)) {
        console.error(`Missing GitHub env files for ${target}.`);
        console.error(`  Expected: ${path.basename(secretsPath)}`);
        console.error(`            ${path.basename(varsPath)}`);
        console.error('Run: pnpm sync:github-secrets:init  then fill values.');
        process.exit(1);
    }

    const secrets = parseEnv(fs.readFileSync(secretsPath, 'utf8'));
    const vars = parseEnv(fs.readFileSync(varsPath, 'utf8'));
    const merged = { ...vars, ...secrets };

    if (!merged.DATABASE_URL) {
        console.error(`DATABASE_URL is empty in ${path.basename(secretsPath)}.`);
        process.exit(1);
    }
    if (/\.railway\.internal(?::|\/|$)/i.test(merged.DATABASE_URL)) {
        console.error(
            'DATABASE_URL still uses *.railway.internal — use the public TCP proxy (*.proxy.rlwy.net).'
        );
        process.exit(1);
    }

    // Local process still listens here; remote URLs come from GitHub files.
    merged.NODE_ENV = target;
    merged.PORT = merged.PORT || '3002';
    merged.LOG_LEVEL = merged.LOG_LEVEL || (target === 'production' ? 'info' : 'debug');
    merged.DATABASE_SYNC = 'false';
    if (merged.DATABASE_SSL === undefined) merged.DATABASE_SSL = 'true';

    // Mirror public domains for Next apps when only DOMAIN_* is set.
    if (merged.DOMAIN_APP && !merged.NEXT_PUBLIC_DOMAIN_APP) {
        merged.NEXT_PUBLIC_DOMAIN_APP = merged.DOMAIN_APP;
    }
    if (merged.DOMAIN_WEB && !merged.NEXT_PUBLIC_DOMAIN_WEB) {
        merged.NEXT_PUBLIC_DOMAIN_WEB = merged.DOMAIN_WEB;
    }
    if ((merged.DOMAIN_BACK_PUBLIC || merged.DOMAIN_BACK) && !merged.NEXT_PUBLIC_DOMAIN_BACK) {
        merged.NEXT_PUBLIC_DOMAIN_BACK = merged.DOMAIN_BACK_PUBLIC || merged.DOMAIN_BACK;
    }

    const preferredOrder = [
        'NODE_ENV',
        'PORT',
        'LOG_LEVEL',
        'DOMAIN_APP',
        'DOMAIN_WEB',
        'DOMAIN_BACK',
        'DOMAIN_BACK_PUBLIC',
        'NEXT_PUBLIC_DOMAIN_APP',
        'NEXT_PUBLIC_DOMAIN_WEB',
        'NEXT_PUBLIC_DOMAIN_BACK',
        'DATABASE_URL',
        'DATABASE_SSL',
        'DATABASE_SYNC',
        'DATABASE_REDIS_URL',
        'BETTER_AUTH_SECRET',
        'EMAIL_VERIFICATION_ENABLED',
        'EMAIL_PROVIDER',
        'RESEND_API_KEY',
        'EMAIL_LOG_ONLY',
        'EMAIL_FROM',
    ];

    const keys = [
        ...preferredOrder.filter(k => merged[k] !== undefined),
        ...Object.keys(merged)
            .filter(k => !preferredOrder.includes(k))
            .sort(),
    ];

    const outPath = path.join(ROOT, `.env.${target}`);
    const body = [
        `# Generated by pnpm env:use ${target} — DO NOT COMMIT`,
        `# Source: .env.github.secrets.${target} + .env.github.vars.${target}`,
        `# Load with: NODE_ENV=${target} pnpm …`,
        `# Keep root .env for local Docker/dev.`,
        '',
        ...keys.map(k => encode(k, merged[k])),
        '',
    ].join('\n');

    fs.writeFileSync(outPath, body, 'utf8');

    let host = '(unknown)';
    try {
        host = new URL(merged.DATABASE_URL.replace(/^postgresql:/, 'postgres:')).hostname;
    } catch {
        /* ignore */
    }

    console.log(`✅ Wrote ${path.basename(outPath)}`);
    console.log(`   DATABASE host: ${host}`);
    console.log(
        `   Domains: ${merged.DOMAIN_APP || '—'} / ${merged.DOMAIN_BACK_PUBLIC || merged.DOMAIN_BACK || '—'}`
    );
    console.log('');
    console.log('Examples:');
    console.log(`  NODE_ENV=${target} pnpm db:push`);
    console.log(`  NODE_ENV=${target} pnpm --filter @rumtelo/backend start`);
    console.log(`  pnpm db:push:${target === 'production' ? 'prod' : 'stag'}`);
}

main();
