/**
 * User-facing API error keys — leaf names under `common.message.error.api` in @rumtelo/i18n.
 * Backend throws these (not English prose). Client translates via next-intl.
 */
export const API_ERROR_MESSAGES = [
    'goal_save_only_jar_focus',
    'goal_save_needs_jar_focus',
    'goal_only_active_focus',
    'goal_save_only_achieved',
    'goal_not_active',
    'goal_no_jar_spend',
    'payment_amount_positive',
    'bill_paused_no_settlement',
    'due_month_required',
    'income_kind_cadence_locked',
    'party_or_merchant',
    'party_name_taken',
    'party_not_found',
    'party_merge_same',
    'party_already_suggested',
    'party_already_in_catalog',
    'period_closed',
    'month_close_incomplete',
    'month_close_prior_open',
    'bill_link_outflow',
    'bill_link_inflow',
    'asset_not_found',
    'bank_account_not_found',
    'iban_already_linked',
    'account_name_taken',
    'primary_account_required',
    'bank_not_found',
    'bank_required',
    'statement_bank_mismatch',
    'settlement_account_invalid',
    'invalid_iban',
    'bank_sync_disabled',
    'bank_sync_failed',
    'bank_sync_redirect_not_allowed',
    'bank_sync_account_required',
    'plan_downgrade_max_only',
    'demo_no_plan_change',
    'invitation_create_failed',
    'already_household_member',
    'invitation_not_found',
    'invitation_accept_failed',
    'jar_split_total',
    'jar_placement_account_invalid',
    'book_catalog_unavailable',
    'contact_send_failed',
    'contact_message_rejected',
    'not_authenticated',
    'no_household_selected',
    'not_household_member',
    'household_mismatch',
    'plan_missing_capability',
    'plan_limit_reached',
    'capability_unavailable',
    'feature_not_implemented',
    'viewer_read_only',
    'role_permission_denied',
    'practice_not_found',
    'practice_not_member',
    'practice_forbidden',
    'practice_client_link_not_found',
    'practice_client_link_not_active',
    'practice_client_link_not_invited',
    'practice_household_forbidden',
    'practice_slug_taken',
    'practice_invite_user_not_found',
    'practice_client_invite_not_found',
    'practice_client_invite_expired',
    'practice_client_invite_email_mismatch',
    'household_not_found',
    'household_create_failed',
    'household_context_required',
    'auth_not_ready',
    'time_entry_not_found',
    'account_settings_not_found',
    'device_not_found',
    'device_kind_invalid',
    // Better Auth / rate limit — prefer mapping by `code`, English is fallback only
    'invalid_email_or_password',
    'user_not_found',
    'email_not_verified',
    'too_many_requests',
    'password_too_short',
    'user_already_exists',
    'user_already_exists_use_another_email',
    'invalid_token',
    'token_expired',
] as const;

export type ApiErrorMessageKey = (typeof API_ERROR_MESSAGES)[number];

const API_ERROR_KEY_SET = new Set<string>(API_ERROR_MESSAGES);

export function isApiErrorMessageKey(value: string): value is ApiErrorMessageKey {
    return API_ERROR_KEY_SET.has(value);
}
